// <auto-generated />

#nullable enable

using AVFoundation;
using CoreGraphics;
using Foundation;
using ObjCBindings;
using ObjCRuntime;
using System;
using System.Runtime.Versioning;

namespace TestNamespace;

public partial class EventTests
{
	[Register]
	internal class _RgenNSKeyedArchiverDelegate: NSObject, IRgenNSKeyedArchiverDelegate
	{
		public _RgenNSKeyedArchiverDelegate () { IsDirectBinding = false; }

	}
}
