// <auto-generated />

#nullable enable

using CoreGraphics;
using Foundation;
using Metal;
using ObjCBindings;
using System;
using System.Runtime.Versioning;

namespace TestNamespace;

public partial class CARendererOptions : DictionaryContainer
{

	// TODO: implement default constructors.


	// TODO: implement properties.


	// Emit code for property: ColorSpace


	// Emit code for property: MetalCommandQueue

}
