<?xml version="1.0" encoding="utf-8"?>
<Project>
	<PropertyGroup>
		<OutputType>Exe</OutputType>

		<ApplicationTitle>EnsureUIThreadApp</ApplicationTitle>
		<ApplicationId>com.xamarin.ensureuithreadapp</ApplicationId>
		<ApplicationVersion>3.14</ApplicationVersion>
	</PropertyGroup>

	<Import Project="../../common/shared-dotnet.csproj" />

	<ItemGroup>
		<Compile Include="../*.cs" />
	</ItemGroup>
</Project>
