<?xml version="1.0" encoding="utf-8"?>
<!-- This test can be removed in .NET 7 -->
<Project>
	<PropertyGroup>
		<OutputType>Exe</OutputType>

		<ApplicationId>com.xamarin.centralpackageversionsapp</ApplicationId>
		<ExcludeNUnitLiteReference>true</ExcludeNUnitLiteReference>
		<ExcludeTouchUnitReference>true</ExcludeTouchUnitReference>
		<!-- Newtonsoft.Json produces ILLink trim analysis warnings that we can't fix -->
		<NoWarn>$(NoWarn);IL2026;IL2055;IL2057;IL2060;IL2070;IL2072;IL2075;IL2080</NoWarn>
	</PropertyGroup>

	<Import Project="../../common/shared-dotnet.csproj" />

	<ItemGroup>
		<Compile Include="../*.cs" />
	</ItemGroup>

	<PropertyGroup>
		<CentralPackagesFile>$(MSBuildThisFileDirectory)Packages.props</CentralPackagesFile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json" />
	</ItemGroup>
</Project>
