parameters:

- name: provisionatorChannel
  type: string
  default: 'latest'

- name: pool
  type: string
  default: automatic
  values:
  - pr
  - ci
  - automatic

- name: isPR
  type: boolean

- name: repositoryAlias
  type: string
  default: self

- name: commit
  type: string
  default: HEAD

- name: macOSName
  type: string

# Ideally we should read/get the list of platforms from somewhere else, instead of hardcoding them here.
# Note that this is _all_ the platforms we support (not just the enabled ones).
- name: supportedPlatforms
  type: object
  default: [
    {
      platform: iOS,
      isDotNetPlatform: true,
      isLegacyPlatform: true
    },
    {
      platform: macOS,
      isDotNetPlatform: true,
      isLegacyPlatform: true
    },
    {
      platform: tvOS,
      isDotNetPlatform: true,
      isLegacyPlatform: true
    },
    {
      platform: watchOS,
      isDotNetPlatform: false,
      isLegacyPlatform: true
    },
    {
      platform: MacCatalyst,
      isDotNetPlatform: true,
      isLegacyPlatform: false
    },
    {
      # when running platform-specific test runs, we also need a special test run that executes tests that only runs when multiple platforms are enabled
      platform: Multiple,
      isDotNetPlatform: true,
      isLegacyPlatform: true
    }
  ]

- name: testConfigurations
  type: object
  default: [
    # Disabled by default #
    # {
    #   label: bcl,
    #   splitByPlatforms: false,
    # },
    {
      label: cecil,
      splitByPlatforms: false,
      containsDotNetTests: true,
      containsLegacyTests: false,
      testPrefix: 'simulator_tests',
    },
    {
      label: dotnettests,
      splitByPlatforms: true,
      containsDotNetTests: true,
      containsLegacyTests: false,
      needsMultiplePlatforms: true,
      testPrefix: 'simulator_tests',
    },
    {
      label: fsharp,
      splitByPlatforms: false,
      containsDotNetTests: true,
      containsLegacyTests: true,
      testPrefix: 'simulator_tests',
    },
    {
      label: framework,
      splitByPlatforms: false,
      containsDotNetTests: true,
      containsLegacyTests: true,
      testPrefix: 'simulator_tests',
    },
    {
      label: generator,
      splitByPlatforms: false,
      containsDotNetTests: true,
      containsLegacyTests: true,
      testPrefix: 'simulator_tests',
    },
    {
      label: interdependent-binding-projects,
      splitByPlatforms: false,
      containsDotNetTests: true,
      containsLegacyTests: true,
      testPrefix: 'simulator_tests',
    },
    {
      label: install-source,
      splitByPlatforms: false,
      containsDotNetTests: false,
      containsLegacyTests: true,
      testPrefix: 'simulator_tests',
    },
    {
      label: introspection,
      splitByPlatforms: false,
      containsDotNetTests: true,
      containsLegacyTests: true,
      testPrefix: 'simulator_tests',
    },
    {
      label: linker,
      splitByPlatforms: false,
      containsDotNetTests: true,
      containsLegacyTests: true,
      testPrefix: 'simulator_tests',
    },
    {
      label: mac-binding-project,
      splitByPlatforms: false,
      containsDotNetTests: false,
      containsLegacyTests: true,
      testPrefix: 'simulator_tests',
    },
    {
      label: mmp,
      splitByPlatforms: false,
      containsDotNetTests: false,
      containsLegacyTests: true,
      testPrefix: 'simulator_tests',
    },
    {
      label: mononative,
      splitByPlatforms: false,
      containsDotNetTests: false,
      containsLegacyTests: true,
      testPrefix: 'simulator_tests',
    },
    {
      label: monotouch,
      splitByPlatforms: true,
      containsDotNetTests: true,
      containsLegacyTests: true,
      needsMultiplePlatforms: false,
      testPrefix: 'simulator_tests',
    },
    {
      label: msbuild,
      splitByPlatforms: false,
      containsDotNetTests: true,
      containsLegacyTests: true,
      testPrefix: 'simulator_tests',
    },
    {
      label: mtouch,
      splitByPlatforms: false,
      containsDotNetTests: false,
      containsLegacyTests: true,
      testPrefix: 'simulator_tests',
    },
    {
      label: xammac,
      splitByPlatforms: false,
      containsDotNetTests: false,
      containsLegacyTests: true,
      testPrefix: 'simulator_tests',
    },
    {
      label: xcframework,
      splitByPlatforms: false,
      containsDotNetTests: true,
      containsLegacyTests: true,
      testPrefix: 'simulator_tests',
    },
    {
      label: xtro,
      splitByPlatforms: false,
      containsDotNetTests: true,
      containsLegacyTests: true,
      testPrefix: 'simulator_tests',
    },
  ]

stages:

- ${{ if parameters.isPR }}:
  - stage: clean
    displayName: 'Clean up'
    dependsOn: []
    jobs:
    - job:
      displayName: 'Clean comments'
      pool:
        vmImage: windows-latest
      steps:
      - template: ./common/clean.yml

- stage: configure_build
  displayName: 'Configure'
  jobs:

  - ${{ if eq(parameters.pool, 'automatic') }}:
    - job: AgentPoolSelector       # https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml
      pool:                        # Consider using an agentless (server) job here, but would need to host selection logic as an Azure function: https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#server
        vmImage: ubuntu-latest
      steps:
      - checkout: none             # https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#checkout

      # Selects appropriate agent pool based on trigger type (PR or CI); manually triggered builds target the PR pool
      - template: azure-devops-pools/agent-pool-selector.yml@yaml-templates
        parameters:
          agentPoolPR: $(PRBuildPool)
          agentPoolPRUrl: $(PRBuildPoolUrl)
          agentPoolCI: $(CIBuildPool)
          agentPoolCIUrl: $(CIBuildPoolUrl)

  - job: configure
    displayName: 'Configure build'
    pool:
      vmImage: windows-latest

    variables:
      isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
      isScheduled: $[eq(variables['Build.Reason'], 'Schedule')]
      BRANCH_NAME: $[ replace(variables['Build.SourceBranch'], 'refs/heads/', '') ]

    steps:
    - template: common/configure.yml
      parameters: 
        repositoryAlias: ${{ parameters.repositoryAlias }}
        commit: ${{ parameters.commit }}
        testConfigurations: ${{ parameters.testConfigurations }}
        supportedPlatforms: ${{ parameters.supportedPlatforms }}
        testsLabels: '--label=skip-all-tests,run-ios-tests,run-ios-simulator-tests,run-tvos-tests,run-watchos-tests,run-mac-tests,run-maccatalyst-tests,run-dotnet-tests,run-system-permission-tests,run-legacy-xamarin-tests'
        statusContext: 'VSTS: simulator tests' 
        uploadArtifacts: true

- stage: generate_api_diff
  displayName: 'API diff'
  dependsOn: [ configure_build ]
  jobs:
  - template: ./build/api-diff-stage.yml
    parameters:
      xcodeChannel: ${{ parameters.xcodeChannel }}
      macOSName: ${{ parameters.macOSName }}
      isPR: ${{ parameters.isPR }}
      repositoryAlias: ${{ parameters.repositoryAlias }}
      commit: ${{ parameters.commit }}
      vsdropsPrefix: ${{ variables.vsdropsPrefix }}
      keyringPass: $(pass--lab--mac--builder--keychain)
      gitHubToken: $(Github.Token)
      xqaCertPass: $(xqa--certificates--password)
      pool: ${{ parameters.pool }}
