# extension of the download-artifacts template that adds artifacts that are needed when building the packages
# but not needed when testing on devices

steps:

- template: download-artifacts.yml 

- task: DownloadPipelineArtifact@2
  displayName: Download API diff 
  inputs:
    patterns: '**/APIDiff-stable.zip'
    allowFailedBuilds: true
    path: $(System.DefaultWorkingDirectory)/Reports

- task: ExtractFiles@1
  displayName: 'Extract HmlReport'
  inputs:
    archiveFilePatterns: '$(System.DefaultWorkingDirectory)/Reports/APIDiff/APIDiff-stable.zip'
    destinationFolder: '$(System.DefaultWorkingDirectory)/APIDiff-stable'

- powershell: |
    echo "##vso[task.setvariable variable=APIDIFF_PATH]$Env:SYSTEM_DEFAULTWORKINGDIRECTORY\APIDiff-stable"
  displayName: Pusblish apidiff paths
  name: apidiff