steps:

- checkout: self
  persistCredentials: true

# Download the Html Report that was added by the tests job.
- task: DownloadPipelineArtifact@2
  displayName: Download packages
  inputs:
    patterns: '**'
    allowFailedBuilds: true
    path: $(Build.SourcesDirectory)/packages

- task: AzureFileCopy@3
  displayName: 'Publish package to Azure'
  name: upload
  inputs:
    SourcePath: $(Build.SourcesDirectory)/packages
    azureSubscription:  'Azure Releng (7b4817ae-218f-464a-bab1-a9df2d99e1e5)'
    Destination: AzureBlob
    storage: bosstoragemirror
    ContainerName: wrench
    BlobPrefix: $(Build.SourceBranchName)/$(Build.SourceVersion)/$(Build.BuildId)  # ideally, we would use a variable for this
    outputStorageUri: PackageUrl
    outputStorageContainerSasToken: PackageSasToken

# IMPORTANT - Artifacts have to be uploaded to azure before this step is executed

- template: generate-workspace-info.yml@templates
  parameters:
    GitHubToken: $(GitHub.Token)
    ArtifactDirectory: $(Build.SourcesDirectory)/package-internal

- powershell:
    $execPath=[System.IO.Path]::Combine(
      "$Env:BUILD_SOURCESDIRECTORY",
      "Xamarin.Build.Tasks",
      "tools",
      "BuildTasks",
      "build-tasks.exe")

    $maciosPath=[System.IO.Path]::Combine("$Env:BUILD_SOURCESDIRECTORY", "xamarin-macios")

    Write-Host "Contents"
    Dir $Env:BUILD_SOURCESDIRECTORY | Get-Childitem

    Write-Host "Xamarin-macios path $maciosPath"
    Write-Host "Exe path is $execPath"

    Start-Process -FilePath "$execPath" -ArgumentList "artifacts", "-s", "$maciosPath", "-a", "bosstoragemirror", "-c", "$Env:STORAGE_PASS", "-u", "wrench/$Env:VIRTUAL_PATH/package"
  env:
    VIRTUAL_PATH: $(Build.SourceBranchName)/$(Build.SourceVersion)/$(Build.BuildId)
    GITHUB_AUTH_TOKEN: $(GitHub.Token)
    STORAGE_PASS: $(auth-xamarin-bosstoragemirror-account-key)
  displayName: 'Generate artifacts.json'

- powershell: |
    ls $Env:SYSTEM_DEFAULTWORKINGDIRECTORY

    Import-Module $Env:SYSTEM_DEFAULTWORKINGDIRECTORY\xamarin-macios\tools\devops\device-tests\scripts\GitHub.psm1
    Import-Module $Env:SYSTEM_DEFAULTWORKINGDIRECTORY\xamarin-macios\tools\devops\device-tests\scripts\VSTS.psm1

  displayName: 'Set GithubStatus'