<?xml version="1.0" encoding="utf-8"?>
<Project>
	<PropertyGroup>
		<OutputType>Exe</OutputType>

		<ApplicationTitle>MyTrimmedRegistrarApp</ApplicationTitle>
		<ApplicationId>com.xamarin.mytrimmedregistrarapp</ApplicationId>
		<ApplicationVersion>3.14</ApplicationVersion>
	</PropertyGroup>

	<Import Project="../../common/shared-dotnet.csproj" />

	<ItemGroup>
		<Compile Include="$(MSBuildThisFileDirectory)AppDelegate.cs" />
	</ItemGroup>
</Project>
