parameters:

- name: isPR
  type: boolean

- name: repositoryAlias
  type: string
  default: self

- name: commit
  type: string
  default: HEAD

steps:

- template: ../common/checkout.yml
  parameters:
    isPR: ${{ parameters.isPR }}
    repositoryAlias: ${{ parameters.repositoryAlias }}
    commit: ${{ parameters.commit }}

- pwsh: $(System.DefaultWorkingDirectory)/xamarin-macios/tools/devops/automation/scripts/show_env.ps1
  displayName: 'Dump Environment'

- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'Xamarin - SDK Engineering - macios-team-pair-to-mac-ci'
    KeyVaultName: 'xamarin-ios-vault'
    SecretsFilter: 'RemoteMacIdRsa'
  displayName: 'Download id_rsa'

- pwsh: |
    $idRsaPath = "$(Get-Location)\id_rsa"
    Write-Host "##vso[task.setvariable variable=ID_RSA_PATH]$idRsaPath"
    Add-Content -Path "id_rsa"  -Value "$(RemoteMacIdRsa)"
    # We need to make sure the private key is only accessible by the current user,
    # otherwise ssh will complain and not use it.
    icacls id_rsa /inheritance:r
    $grant="$Env:USERNAME" + ":(R)"
    icacls id_rsa /grant:r $grant
  displayName: "Write and verify id_rsa"
  continueOnError: true

- pwsh: |
    ssh -v -i "$(ID_RSA_PATH)" -o IdentitiesOnly=yes -o StrictHostKeyChecking=no builder@$Env:MAC_AGENT_IP -- rm -f "/Users/$($Env:MAC_AGENT_USER)/remote_build_testing/BuildId.txt"
  displayName: 'Remove BuildId from macOS bot'
  condition: always()
  continueOnError: true

- template: azure-tools/az-client-update.yml@templates    # AzureCLI step below requires that AzClient 2.x is installed on the agent
  parameters:
    platform: 'All'       # Update Az tools for both Windows and Mac agents
    version: '2.62.0'

# https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/1es-security-configuration/configuration-guides/pat-burndown-guidance#authentication-from-pipelines
# Requires Azure client 2.x
- task: AzureCLI@2
  displayName: 'AzDO.BearerToken based on service connection'
  enabled: true
  inputs:
    azureSubscription: 'DevDiv - SharedUntrustedAgentPool-Manage'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # if this fails, check out this bash script that includes diagnostics:
      # https://gist.github.com/johnterickson/19f80a3e969e39f1000d118739176e62

      # Note that the resource is specified to limit the token to Azure DevOps
      $token = az account get-access-token --query accessToken --resource 499b84ac-1321-427f-aa17-267ca6975798 -o tsv

      Write-Host "Setting AzDO.BearerToken"
      Write-Host "##vso[task.setvariable variable=AzDO.BearerToken;issecret=true]${token}"

- pwsh: |
    Import-Module $Env:SYSTEM_DEFAULTWORKINGDIRECTORY\xamarin-macios\tools\devops\automation\scripts\MaciosCI.psd1

    $azdoBearerToken = "$(AzDO.BearerToken)"
    $azdoBearerTokenHint = $azdoBearerToken.Substring(0, 8)
    Write-Host "AzDO.BearerToken (hint): ${azdoBearerTokenHint}"

    $vsts = New-VSTS -Org "devdiv" -Project "DevDiv" -Token $azdoBearerToken

    # get the pool and the agent objects and enable the bot
    $pool = $vsts.Pools.GetPool("$Env:MAC_AGENT_POOL")
    $agent = $vsts.Agents.GetAgent($pool, $Env:MAC_AGENT_NAME)
    $vsts.Agents.SetEnabled($pool, $agent, $True)
  displayName: 'Re-enabled macOS bot from pool'
  condition: always()

- pwsh: |
    Remove-Item "$(ID_RSA_PATH)"
  displayName: "Remove secrets"
  condition: always()
  continueOnError: true
