parameters:
# name of the pool that contains the iOS devices
- name: pool
  type: string

- name: stageName
  type: string

- name: displayName
  type: string

- name: statusContext
  type: string
  default: 'Windows Integration Tests'

- name: macPool
  type: string
  default: "VSEng-VSMac-Xamarin-Shared"

stages:
- stage: ${{ parameters.stageName }}
  displayName: ${{ parameters.displayName }}
  dependsOn: []

  jobs:
  - job: mac_reservation
    displayName: "Reserve bot for tests"
    timeoutInMinutes: 1000
    workspace:
      clean: all
    pool: ${{ parameters.macPool }}

    steps:
    - template: reserve-mac.yml
      parameters:
        macPool: ${{ parameters.macPool }}

  - job: run_tests
    dependsOn:
    - mac_reservation
    displayName: 'Dotnet tests'
    timeoutInMinutes: 1000
    workspace:
      clean: all

    pool:
      vmImage: windows-latest

    variables:
      MAC_AGENT_NAME: $[ dependencies.mac_reservation.outputs['macInfo.AGENT_NAME'] ]
      MAC_AGENT_POOL: $[ dependencies.mac_reservation.outputs['macInfo.AGENT_POOL'] ]
      MAC_AGENT_IP: $[ dependencies.mac_reservation.outputs['macInfo.AGENT_IP'] ]

    steps:
    - template: build.yml
      parameters:
        statusContext: ${{ parameters.statusContext }}
