<?xml version="1.0" encoding="utf-8"?>
<Project>
	<PropertyGroup>
		<OutputType>Exe</OutputType>

		<ApplicationTitle>NativeMergeableFrameworkReferencesApp</ApplicationTitle>
		<ApplicationId>com.xamarin.nativemergeableframeworkreferences</ApplicationId>
		<ApplicationVersion>1.0</ApplicationVersion>
	</PropertyGroup>

	<Import Project="../../common/shared-dotnet.csproj" />

	<ItemGroup>
		<NativeReference Include="..\..\..\test-libraries\.libs\$(NativeLibName)\XMergeableTest.framework" Kind="Framework" />
	</ItemGroup>

	<ItemGroup>
		<Compile Include="../*.cs" />
	</ItemGroup>
</Project>
