# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

TOP=../../../../..
DOTNET_TEST_PLATFORMS=$(filter tvOS,$(DOTNET_PLATFORMS))
DOTNET_TEST_DESKTOP_PLATFORMS=

include $(TOP)/tests/common/shared-dotnet-test.mk

TESTNAME=monotouch-test-tv-top-shelf-extension
