TOP=../../xamarin-macios
include $(TOP)/Make.config

release package:
	$(MAKE) bundle.zip msbuild.zip

# msbuild.zip and bundle.zip are uploaded to wrench and packaged into the VS plugin
msbuild.zip:
	@echo "do we still need this?"
	exit 1

bundle.zip:
	@echo "do we still need this?"
	exit 1
