
# job that downloads the html report from the artifacts and uploads them into vsdrops.
parameters:

- name: vsdropsPrefix
  type: string

steps:

- checkout: self
  persistCredentials: true

- template: download-artifacts.yml 

# Upload full report to vsdrops using the the build numer and id as uudis.
- task: ms-vscs-artifact.build-tasks.artifactDropTask-1.artifactDropTask@0
  displayName: 'Publish to Artifact Services Drop'
  inputs:
    dropServiceURI: 'https://devdiv.artifacts.visualstudio.com/DefaultCollection'
    buildNumber: 'xamarin-macios/device-tests/$(Build.BuildNumber)/$(Build.BuildId)'
    sourcePath: $(HTML_REPORT_PATH)
    detailedLog: true
    usePat: true 

- pwsh: |
    echo "##vso[task.setvariable variable=VSDROPS_INDEX];isOutput=true]$Env:VSDROPS_INDEX"
  displayName: Publis vsdrops path
  name: vsdrops # not to be confused with the displayName, this is used to later use the name of the step to access the output variables from an other job
  env:
    VSDROPS_INDEX: '${{ parameters.vsdropsPrefix }}/$(Build.BuildNumber)/$(Build.BuildId);/tests/vsdrops_index.html' # url to the vsdrops generated index file
