
# job that downloads the html report from the artifacts and uploads them into vsdrops.
steps:

- checkout: self
  persistCredentials: true

- template: download-artifacts.yml 

# Upload full report to vsdrops using the the build numer and id as uudis.
- task: ms-vscs-artifact.build-tasks.artifactDropTask-1.artifactDropTask@0
  displayName: 'Publish to Artifact Services Drop'
  inputs:
    dropServiceURI: 'https://devdiv.artifacts.visualstudio.com/DefaultCollection'
    buildNumber: 'xamarin-macios/device-tests/$(Build.BuildNumber)/$(Build.BuildId)'
    sourcePath: $(HTML_REPORT_PATH)
    detailedLog: true
    usePat: true 