using System.Collections.Generic;
namespace Cecil.Tests {
	public partial class HandleSafetyTest {
		static HashSet<string> knownFailuresHandleSafety = new HashSet<string> {
			"AudioUnit.AUScheduledAudioFileRegion.GetAudioFileRegion ()",
			"AudioUnit.SamplerInstrumentData.ToStruct ()",
			"CoreImage.CIImage.FromCGImage (CoreGraphics.CGImage, CoreGraphics.CGColorSpace)",
			"CoreMidi.MidiCIDeviceInfo..ctor (CoreMidi.MidiEndpoint, Foundation.NSData, Foundation.NSData, Foundation.NSData, Foundation.NSData)",
			"CoreText.Adapter.GetHandles`1 (System.Collections.Generic.IEnumerable`1<T>)",
			"CoreText.CTBaselineClassID.FromHandle (System.IntPtr)",
			"CoreText.CTFontCollectionOptionsExtensions.GetHandle (CoreText.CTFontCollectionOptions)",
			"CoreText.CTFrameAttributesExtensions.GetHandle (CoreText.CTFrameAttributes)",
			"CoreText.CTParagraphStyleSettings.CreateValue (CoreText.CTParagraphStyleSpecifier, System.Collections.Generic.IEnumerable`1<CoreText.CTTextTab>)",
			"CoreText.CTParagraphStyleSpecifierIntPtrsValue.WriteValue (CoreText.CTParagraphStyleSettingValue[], System.Int32)",
			"CoreText.CTTextTabOptionsExtensions.GetHandle (CoreText.CTTextTabOptions)",
			"CoreText.CTTypesetterOptionsExtensions.GetHandle (CoreText.CTTypesetterOptions)",
			"Foundation.DictionaryContainer.TryGetNativeValue (ObjCRuntime.NativeHandle, ObjCRuntime.NativeHandle&)",
			"Foundation.DictionaryContainerHelper.GetHandle (Foundation.DictionaryContainer)",
			"Foundation.NSArray.FromNativeObjectsImpl`1 (T[], System.IntPtr, System.Boolean)",
			"Foundation.NSArray.FromNSObjects (System.Collections.Generic.IList`1<Foundation.NSObject>)",
			"Foundation.NSArray`1.FromNSObjects`0 (System.Int32, TKey[])",
			"ObjCRuntime.BackingField.Save`1 (T&, T)",
			"ObjCRuntime.BindAs.ConvertManagedArrayToNSArray2`2 (T[], method U *(T), method System.IntPtr *(U))",
			"ObjCRuntime.BindAs.xamarin_bool_to_nsnumber (System.Boolean)",
			"ObjCRuntime.BindAs.xamarin_byte_to_nsnumber (System.Byte)",
			"ObjCRuntime.BindAs.xamarin_double_to_nsnumber (System.Double)",
			"ObjCRuntime.BindAs.xamarin_float_to_nsnumber (System.Single)",
			"ObjCRuntime.BindAs.xamarin_int_to_nsnumber (System.Int32)",
			"ObjCRuntime.BindAs.xamarin_long_to_nsnumber (System.Int64)",
			"ObjCRuntime.BindAs.xamarin_nfloat_to_nsnumber (System.Runtime.InteropServices.NFloat)",
			"ObjCRuntime.BindAs.xamarin_nint_to_nsnumber (System.IntPtr)",
			"ObjCRuntime.BindAs.xamarin_nuint_to_nsnumber (System.UIntPtr)",
			"ObjCRuntime.BindAs.xamarin_nullable_bool_to_nsnumber (System.Nullable`1<System.Boolean>)",
			"ObjCRuntime.BindAs.xamarin_nullable_byte_to_nsnumber (System.Nullable`1<System.Byte>)",
			"ObjCRuntime.BindAs.xamarin_nullable_double_to_nsnumber (System.Nullable`1<System.Double>)",
			"ObjCRuntime.BindAs.xamarin_nullable_float_to_nsnumber (System.Nullable`1<System.Single>)",
			"ObjCRuntime.BindAs.xamarin_nullable_int_to_nsnumber (System.Nullable`1<System.Int32>)",
			"ObjCRuntime.BindAs.xamarin_nullable_long_to_nsnumber (System.Nullable`1<System.Int64>)",
			"ObjCRuntime.BindAs.xamarin_nullable_nfloat_to_nsnumber (System.Nullable`1<System.Runtime.InteropServices.NFloat>)",
			"ObjCRuntime.BindAs.xamarin_nullable_nint_to_nsnumber (System.Nullable`1<System.IntPtr>)",
			"ObjCRuntime.BindAs.xamarin_nullable_nuint_to_nsnumber (System.Nullable`1<System.UIntPtr>)",
			"ObjCRuntime.BindAs.xamarin_nullable_sbyte_to_nsnumber (System.Nullable`1<System.SByte>)",
			"ObjCRuntime.BindAs.xamarin_nullable_short_to_nsnumber (System.Nullable`1<System.Int16>)",
			"ObjCRuntime.BindAs.xamarin_nullable_uint_to_nsnumber (System.Nullable`1<System.UInt32>)",
			"ObjCRuntime.BindAs.xamarin_nullable_ulong_to_nsnumber (System.Nullable`1<System.UInt64>)",
			"ObjCRuntime.BindAs.xamarin_nullable_ushort_to_nsnumber (System.Nullable`1<System.UInt16>)",
			"ObjCRuntime.BindAs.xamarin_sbyte_to_nsnumber (System.SByte)",
			"ObjCRuntime.BindAs.xamarin_short_to_nsnumber (System.Int16)",
			"ObjCRuntime.BindAs.xamarin_uint_to_nsnumber (System.UInt32)",
			"ObjCRuntime.BindAs.xamarin_ulong_to_nsnumber (System.UInt64)",
			"ObjCRuntime.BindAs.xamarin_ushort_to_nsnumber (System.UInt16)",
			"ObjCRuntime.NativeObjectExtensions.GetHandle (ObjCRuntime.INativeObject)",
			"ObjCRuntime.NativeObjectExtensions.GetNonNullHandle (ObjCRuntime.INativeObject, System.String)",
			"ObjCRuntime.RegistrarHelper.INativeObject_managed_to_native (System.IntPtr, ObjCRuntime.INativeObject, ObjCRuntime.INativeObject, System.Boolean)",
			"ObjCRuntime.Runtime.ConvertSmartEnumToNSString (System.IntPtr)",
			"ObjCRuntime.Runtime.GetHandleForINativeObject (System.IntPtr)",
			"ObjCRuntime.Runtime.RetainAndAutoreleaseNativeObject (ObjCRuntime.INativeObject)",
			"ObjCRuntime.Runtime.RetainAndAutoreleaseNSObject (Foundation.NSObject)",
			"ObjCRuntime.Runtime.RetainNativeObject (ObjCRuntime.INativeObject)",
			"ObjCRuntime.Runtime.RetainNSObject (Foundation.NSObject)",
			"ObjCRuntime.Runtime.UnwrapNSException (System.IntPtr)",
			"ReplayKit.RPBroadcastConfiguration.set_VideoCompressionProperties (AVFoundation.AVVideoCodecSettings)",
			"SceneKit.SCNSkinner.ToNSArray (SceneKit.SCNMatrix4[])",
			"Security.SecIdentity.Import (System.Byte[], System.String)",
			"Security.SecRecord.get_ApplicationTag ()",
			"Security.SecRecord.get_CanDecrypt ()",
			"Security.SecRecord.get_CanDerive ()",
			"Security.SecRecord.get_CanEncrypt ()",
			"Security.SecRecord.get_CanSign ()",
			"Security.SecRecord.get_CanUnwrap ()",
			"Security.SecRecord.get_CanVerify ()",
			"Security.SecRecord.get_CanWrap ()",
			"Security.SecRecord.get_EffectiveKeySize ()",
			"Security.SecRecord.get_IsPermanent ()",
			"Security.SecRecord.get_KeySizeInBits ()",
			"Security.SecRecord.get_KeyType ()",
			"Security.SecRecord.get_Label ()",
			"Security.SecRecord.get_TokenID ()",
			"Security.SecRecord.set_AccessControl (Security.SecAccessControl)",
			"Security.SecRecord.set_ApplicationTag (Foundation.NSData)",
			"Security.SecRecord.set_CanDecrypt (System.Boolean)",
			"Security.SecRecord.set_CanDerive (System.Boolean)",
			"Security.SecRecord.set_CanEncrypt (System.Boolean)",
			"Security.SecRecord.set_CanSign (System.Boolean)",
			"Security.SecRecord.set_CanUnwrap (System.Boolean)",
			"Security.SecRecord.set_CanVerify (System.Boolean)",
			"Security.SecRecord.set_CanWrap (System.Boolean)",
			"Security.SecRecord.set_EffectiveKeySize (System.Int32)",
			"Security.SecRecord.set_IsPermanent (System.Boolean)",
			"Security.SecRecord.set_KeySizeInBits (System.Int32)",
			"Security.SecRecord.set_KeyType (Security.SecKeyType)",
			"Security.SecRecord.set_Label (System.String)",
			"Security.SecRecord.set_TokenID (Security.SecTokenID)",
			"Security.SslContext.Bundle (Security.SecIdentity, System.Collections.Generic.IEnumerable`1<Security.SecCertificate>)",
			"System.Boolean ObjCRuntime.DisposableObject.op_Equality (ObjCRuntime.DisposableObject, ObjCRuntime.DisposableObject)",
			"System.Boolean ObjCRuntime.DisposableObject.op_Inequality (ObjCRuntime.DisposableObject, ObjCRuntime.DisposableObject)",
			"System.Boolean ObjCRuntime.NativeHandle.op_Equality (System.IntPtr, ObjCRuntime.NativeHandle)",
			"System.Boolean ObjCRuntime.NativeHandle.op_Inequality (ObjCRuntime.NativeHandle, ObjCRuntime.NativeHandle)",
			"System.Boolean ObjCRuntime.NativeHandle.op_Inequality (System.IntPtr, ObjCRuntime.NativeHandle)",
			"System.Boolean UIKit.UIAppearance.op_Equality (UIKit.UIAppearance, UIKit.UIAppearance)",
			"System.Boolean UIKit.UIFont.op_Equality (UIKit.UIFont, UIKit.UIFont)",
			"System.IntPtr ObjCRuntime.NativeHandle.op_Implicit (ObjCRuntime.NativeHandle)",
			"UIKit.UIAlertView..ctor (System.String, System.String, UIKit.IUIAlertViewDelegate, System.String, System.String[])",
			"UIKit.UIAppearance.Equals (System.Object)",
			"UIKit.UIFontFeature.ObjCRuntime.INativeObject.get_Handle ()",
			"UIKit.UIPasteboard.set_Images (UIKit.UIImage[])",
		};
	}
}
