# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

EXTENSION_KIND=tv-top-shelf
include ../../shared.mk

# Build and run monotouch-test from the top-shelf extension for this platform:
#    make build
#    make run
#
# Select the runtime, registrar and configuration using TEST_VARIATION (run
# 'make help' to see all variations), e.g.:
#    make run TEST_VARIATION=trimmable-static-registrar
#    make run TEST_VARIATION='trimmable-static-registrar|release'
#
# Set TEST_FILTER to run a specific test instead of the full suite.
# Any arguments to 'dotnet build' can be set using the BUILD_PARAMETERS variable.
