<Project Sdk="Microsoft.NET.Sdk">
  <Sdk Name="Microsoft.DotNet.SharedFramework.Sdk" Version="$(MicrosoftDotNetBuildTasksFeedPackageVersionNet10)" />

  <PropertyGroup>
    <_PlatformName>MacCatalyst</_PlatformName>
    <_RuntimeIdentifier>maccatalyst-x64</_RuntimeIdentifier>
  </PropertyGroup>

  <Import Project="../microsoft.runtime.csproj" />
</Project>
