# common steps to download the artifacts from the test results.
parameters:

- name: devicePrefix
  type: string 
  default: 'ios' # default context, since we started dealing with iOS devices. 

steps:

- checkout: self
  persistCredentials: true

# Download the Html Report that was added by the tests job.
- task: DownloadPipelineArtifact@2
  displayName: Download html report 
  inputs:
    patterns: 'HtmlReport-${{ parameters.devicePrefix }}/HtmlReport.zip'
    allowFailedBuilds: true
    path: $(System.DefaultWorkingDirectory)/Reports

# Unzip report.
- task: ExtractFiles@1
  displayName: 'Extract HmlReport'
  inputs:
    archiveFilePatterns: '$(System.DefaultWorkingDirectory)/Reports/HtmlReport-${{ parameters.devicePrefix }}/HtmlReport.zip'
    destinationFolder: '$(System.DefaultWorkingDirectory)/HtmlReport-${{ parameters.devicePrefix }}'

# Download the test report to write the comment.
- task: DownloadPipelineArtifact@2
  displayName: Download Test Summary
  inputs:
    patterns: '**/TestSummary-${{ parameters.devicePrefix }}/TestSummary.md'
    allowFailedBuilds: true
    path: $(System.DefaultWorkingDirectory)\Reports

- powershell: |
    Get-ChildItem -Recurse $Env:SYSTEM_DEFAULTWORKINGDIRECTORY

    Write-Host "##vso[task.setvariable variable=TEST_SUMMARY_PATH]$Env:SYSTEM_DEFAULTWORKINGDIRECTORY\Reports\TestSummary-${{ parameters.devicePrefix }}\TestSummary-${{ parameters.devicePrefix }}.md"
    Write-Host "##vso[task.setvariable variable=HTML_REPORT_PATH]$Env:SYSTEM_DEFAULTWORKINGDIRECTORY\HtmlReport-${{ parameters.devicePrefix }}"
  displayName: Pusblish artifact paths
  name: artifacts # not to be confused with the displayName, this is used to later use the name of the step to access the output variables from an other job
