# Template that gets token to fetch internal .NET builds.

parameters:

- name: federatedServiceConnection
  type: string
  default: 'dotnetbuilds-internal-read'

- name: dotnetInternalBuildContainerTokenVariableName
  type: string
  default: 'dotnetbuilds-internal-container-read-token'

- name: dotnetInternalBuildContainerTokenExpiryInHours
  type: string
  default: 1

- name: dotnetInternalBuildContainerTokenBase64Encode
  type: boolean
  default: false

- name: agentPoolComputed3
  type: string

steps:

- ${{ if endsWith(variables['AGENTPOOLCOMPUTED'], '-Trusted') }}:
  - template: /eng/common/templates-official/steps/enable-internal-sources.yml
    parameters:
      repositoryName: /xamarin-macios
      condition: eq(variables['INTERNAL_DOTNET'],'1')

  - template: /eng/common/templates-official/steps/enable-internal-runtimes.yml
    parameters:
      federatedServiceConnection: ${{ parameters.federatedServiceConnection }}
      outputVariableName: ${{ parameters.dotnetInternalBuildContainerTokenVariableName }}
      expiryInHours: ${{ parameters.dotnetInternalBuildContainerTokenExpiryInHours }}
      base64Encode: ${{ parameters.dotnetInternalBuildContainerTokenBase64Encode }}
      condition: eq(variables['INTERNAL_DOTNET'],'1')
- ${{ else }}:
  - bash: |
      echo "This branch currently requires an internal build of .NET, but that's only supported in CI pipelines/agents, not PR pipelines/agents (agentPoolComputed: ${{ parameters.agentPoolComputed3 }})."
      exit 1
    displayName: "Internal build check (1)"
    condition: eq(variables['INTERNAL_DOTNET'],'1')

- bash: |
    echo "This branch does not requre an internal build of .NET, so we're good to proceed."
    env
  displayName: "Internal build check (2)"
  condition: eq(variables['INTERNAL_DOTNET'],'')
  env:
    ENV_VARIABLES: $[ convertToJson(variables) ]
