# imports the xml to the vsts test results for the job
parameters:

- name: testPrefix
  type: string 
  default: 'ios' # default context, since we started dealing with iOS devices. 

# did the provisioning work?
- name: provisioningFailed
  type: string 
  default: 'False'

- name: isPR
  type: boolean

steps:

- template: checkout.yml
  parameters:
    isPR: ${{ parameters.isPR }}

- ${{ if eq(parameters.provisioningFailed, 'False') }}:
  - template: download-artifacts.yml 
    parameters:
      testPrefix: ${{ parameters.testPrefix }}

- bash: |
    set -ex
    find . -name 'vsts-*.xml' || true
    find . -name 'vsts-*.xml' -ls -exec cat {} \; || true
    VSTS_XML_FILES=$(find . -name 'vsts-*.xml' | wc -l | sed 's/ //g')
    set +x
    echo "##vso[task.setvariable variable=VSTS_XML_FILES]$VSTS_XML_FILES"
    set -x
  name: ListNUnitTestResults
  continueOnError: true
  condition: succeededOrFailed()
  displayName: 'List NUnit test results'

  # Upload test results to vsts.
  - task: PublishTestResults@2
    displayName: 'Publish NUnit Device Test Results'
    inputs:
      testResultsFormat: NUnit
      testResultsFiles: '**/vsts-*.xml'
      failTaskOnFailedTests: true
    continueOnError: true
    condition: and(ne($[VSTS_XML_FILES],0),succeededOrFailed())
