// <auto-generated />

#nullable enable

using AVFoundation;
using Foundation;
using ObjCBindings;
using ObjCRuntime;
using System.Runtime.Versioning;

namespace Microsoft.Macios.Generator.Tests.Protocols.Data;

[SupportedOSPlatform ("macos")]
[SupportedOSPlatform ("ios")]
[SupportedOSPlatform ("tvos")]
[SupportedOSPlatform ("maccatalyst13.1")]
[Protocol (Name = "AVAudio3DMixing", WrapperType = typeof (AVAudio3DMixingWrapper))]
[ProtocolMember (IsRequired = true, IsProperty = true, IsStatic = false, Name = "Obstruction", Selector = "obstruction", PropertyType = typeof (float), GetterSelector = "obstruction", SetterSelector = "setObstruction:", ArgumentSemantic = ArgumentSemantic.None)]
[ProtocolMember (IsRequired = true, IsProperty = true, IsStatic = false, Name = "Occlusion", Selector = "occlusion", PropertyType = typeof (float), GetterSelector = "occlusion", SetterSelector = "setOcclusion:", ArgumentSemantic = ArgumentSemantic.None)]
[ProtocolMember (IsRequired = true, IsProperty = true, IsStatic = false, Name = "PointSourceInHeadMode", Selector = "pointSourceInHeadMode", PropertyType = typeof (global::AVFoundation.AVAudio3DMixingPointSourceInHeadMode), GetterSelector = "pointSourceInHeadMode", SetterSelector = "setPointSourceInHeadMode:", ArgumentSemantic = ArgumentSemantic.Assign)]
[ProtocolMember (IsRequired = true, IsProperty = true, IsStatic = false, Name = "Rate", Selector = "rate", PropertyType = typeof (float), GetterSelector = "rate", SetterSelector = "setRate:", ArgumentSemantic = ArgumentSemantic.None)]
[ProtocolMember (IsRequired = true, IsProperty = true, IsStatic = false, Name = "RenderingAlgorithm", Selector = "renderingAlgorithm", PropertyType = typeof (global::AVFoundation.AVAudio3DMixingRenderingAlgorithm), GetterSelector = "renderingAlgorithm", SetterSelector = "setRenderingAlgorithm:", ArgumentSemantic = ArgumentSemantic.None)]
[ProtocolMember (IsRequired = true, IsProperty = true, IsStatic = false, Name = "ReverbBlend", Selector = "reverbBlend", PropertyType = typeof (float), GetterSelector = "reverbBlend", SetterSelector = "setReverbBlend:", ArgumentSemantic = ArgumentSemantic.None)]
[ProtocolMember (IsRequired = true, IsProperty = true, IsStatic = false, Name = "SourceMode", Selector = "sourceMode", PropertyType = typeof (global::AVFoundation.AVAudio3DMixingSourceMode), GetterSelector = "sourceMode", SetterSelector = "setSourceMode:", ArgumentSemantic = ArgumentSemantic.Assign)]
public interface IAVAudio3DMixing : INativeObject, IDisposable
{

	[DynamicDependency ("Obstruction")]
	[DynamicDependency ("Occlusion")]
	[DynamicDependency ("PointSourceInHeadMode")]
	[DynamicDependency ("Rate")]
	[DynamicDependency ("RenderingAlgorithm")]
	[DynamicDependency ("ReverbBlend")]
	[DynamicDependency ("SourceMode")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	static IAVAudio3DMixing ()
	{
		global::System.GC.KeepAlive (null);
	}
}
