// <auto-generated />

#nullable enable

using AVFoundation;
using Foundation;
using ObjCBindings;
using ObjCRuntime;
using System.Runtime.Versioning;

namespace Microsoft.Macios.Generator.Tests.Protocols.Data;

[SupportedOSPlatform ("macos")]
[SupportedOSPlatform ("ios")]
[SupportedOSPlatform ("tvos")]
[SupportedOSPlatform ("maccatalyst13.1")]
[Protocol (Name = "AVAudioPlayerDelegate", WrapperType = typeof (AVAudioPlayerDelegateWrapper))]
[ProtocolMember (IsRequired = true, IsProperty = false, IsStatic = false, Name = "BeginInterruption", Selector = "audioPlayerBeginInterruption:", ReturnType = typeof (void), ParameterType = new Type [] { typeof (global::AVFoundation.AVAudioPlayer) }, ParameterByRef = new bool [] { false }, ParameterBlockProxy = new Type? [] { null })]
[ProtocolMember (IsRequired = true, IsProperty = false, IsStatic = false, Name = "DecoderError", Selector = "audioPlayerDecodeErrorDidOccur:error:", ReturnType = typeof (void), ParameterType = new Type [] { typeof (global::AVFoundation.AVAudioPlayer), typeof (global::Foundation.NSError) }, ParameterByRef = new bool [] { false, false }, ParameterBlockProxy = new Type? [] { null, null })]
[ProtocolMember (IsRequired = true, IsProperty = false, IsStatic = false, Name = "EndInterruption", Selector = "audioPlayerBeginInterruption:", ReturnType = typeof (void), ParameterType = new Type [] { typeof (global::AVFoundation.AVAudioPlayer) }, ParameterByRef = new bool [] { false }, ParameterBlockProxy = new Type? [] { null })]
[ProtocolMember (IsRequired = true, IsProperty = false, IsStatic = false, Name = "EndInterruption", Selector = "audioPlayerEndInterruption:withOptions:", ReturnType = typeof (void), ParameterType = new Type [] { typeof (global::AVFoundation.AVAudioPlayer), typeof (global::AVFoundation.AVAudioSessionInterruptionOptions) }, ParameterByRef = new bool [] { false, false }, ParameterBlockProxy = new Type? [] { null, null })]
[ProtocolMember (IsRequired = true, IsProperty = false, IsStatic = false, Name = "FinishedPlaying", Selector = "audioPlayerDidFinishPlaying:successfully:", ReturnType = typeof (void), ParameterType = new Type [] { typeof (global::AVFoundation.AVAudioPlayer), typeof (bool) }, ParameterByRef = new bool [] { false, false }, ParameterBlockProxy = new Type? [] { null, null })]
public partial interface IAVAudioPlayerDelegate : INativeObject, IDisposable
{

	[DynamicDependency ("BeginInterruption(AVFoundation.AVAudioPlayer)")]
	[DynamicDependency ("DecoderError(AVFoundation.AVAudioPlayer,Foundation.NSError?)")]
	[DynamicDependency ("EndInterruption(AVFoundation.AVAudioPlayer)")]
	[DynamicDependency ("EndInterruption(AVFoundation.AVAudioPlayer,AVFoundation.AVAudioSessionInterruptionOptions)")]
	[DynamicDependency ("FinishedPlaying(AVFoundation.AVAudioPlayer,bool)")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	static IAVAudioPlayerDelegate ()
	{
		global::System.GC.KeepAlive (null);
	}

	[UnsupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	internal static void _BeginInterruption (this global::Microsoft.Macios.Generator.Tests.Protocols.Data.IAVAudioPlayerDelegate self, global::AVFoundation.AVAudioPlayer player)
	{
		var player__handle__ = player!.GetNonNullHandle (nameof (player));
		global::ObjCRuntime.Messaging.void_objc_msgSend_NativeHandle (self.Handle, global::ObjCRuntime.Selector.GetHandle ("audioPlayerBeginInterruption:"), player__handle__);
		global::System.GC.KeepAlive (self);
		global::System.GC.KeepAlive (player);
	}

	[UnsupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[global::Foundation.RequiredMember]
	public virtual partial void BeginInterruption (global::AVFoundation.AVAudioPlayer player)
	{
		throw new global::Foundation.You_Should_Not_Call_base_In_This_Method ();
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	internal static void _DecoderError (this global::Microsoft.Macios.Generator.Tests.Protocols.Data.IAVAudioPlayerDelegate self, global::AVFoundation.AVAudioPlayer player, global::Foundation.NSError? error)
	{
		var player__handle__ = player!.GetNonNullHandle (nameof (player));
		var error__handle__ = error?.GetHandle ();
		global::ObjCRuntime.Messaging.void_objc_msgSend_NativeHandle_NativeHandle (self.Handle, global::ObjCRuntime.Selector.GetHandle ("audioPlayerDecodeErrorDidOccur:error:"), player__handle__, error__handle__);
		global::System.GC.KeepAlive (self);
		global::System.GC.KeepAlive (player);
		global::System.GC.KeepAlive (error);
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[global::Foundation.RequiredMember]
	public virtual partial void DecoderError (global::AVFoundation.AVAudioPlayer player, global::Foundation.NSError? error)
	{
		throw new global::Foundation.You_Should_Not_Call_base_In_This_Method ();
	}

	[UnsupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	internal static void _EndInterruption (this global::Microsoft.Macios.Generator.Tests.Protocols.Data.IAVAudioPlayerDelegate self, global::AVFoundation.AVAudioPlayer player)
	{
		var player__handle__ = player!.GetNonNullHandle (nameof (player));
		global::ObjCRuntime.Messaging.void_objc_msgSend_NativeHandle (self.Handle, global::ObjCRuntime.Selector.GetHandle ("audioPlayerBeginInterruption:"), player__handle__);
		global::System.GC.KeepAlive (self);
		global::System.GC.KeepAlive (player);
	}

	[UnsupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[global::Foundation.RequiredMember]
	public virtual partial void EndInterruption (global::AVFoundation.AVAudioPlayer player)
	{
		throw new global::Foundation.You_Should_Not_Call_base_In_This_Method ();
	}

	[UnsupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	internal static void _EndInterruption (this global::Microsoft.Macios.Generator.Tests.Protocols.Data.IAVAudioPlayerDelegate self, global::AVFoundation.AVAudioPlayer player, global::AVFoundation.AVAudioSessionInterruptionOptions flags)
	{
		var player__handle__ = player!.GetNonNullHandle (nameof (player));
		global::ObjCRuntime.Messaging.void_objc_msgSend_NativeHandle_UIntPtr (self.Handle, global::ObjCRuntime.Selector.GetHandle ("audioPlayerEndInterruption:withOptions:"), player__handle__, (global::AVFoundation.AVAudioSessionInterruptionOptions) (ulong) flags);
		global::System.GC.KeepAlive (self);
		global::System.GC.KeepAlive (player);
	}

	[UnsupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[global::Foundation.RequiredMember]
	public virtual partial void EndInterruption (global::AVFoundation.AVAudioPlayer player, global::AVFoundation.AVAudioSessionInterruptionOptions flags)
	{
		throw new global::Foundation.You_Should_Not_Call_base_In_This_Method ();
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	internal static void _FinishedPlaying (this global::Microsoft.Macios.Generator.Tests.Protocols.Data.IAVAudioPlayerDelegate self, global::AVFoundation.AVAudioPlayer player, bool flag)
	{
		var player__handle__ = player!.GetNonNullHandle (nameof (player));
		global::ObjCRuntime.Messaging.void_objc_msgSend_NativeHandle_bool (self.Handle, global::ObjCRuntime.Selector.GetHandle ("audioPlayerDidFinishPlaying:successfully:"), player__handle__, flag ? (byte) 1 : (byte) 0);
		global::System.GC.KeepAlive (self);
		global::System.GC.KeepAlive (player);
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[global::Foundation.RequiredMember]
	public virtual partial void FinishedPlaying (global::AVFoundation.AVAudioPlayer player, bool flag)
	{
		throw new global::Foundation.You_Should_Not_Call_base_In_This_Method ();
	}
}

internal unsafe sealed class AVAudioPlayerDelegateWrapper : BaseWrapper, IAVAudioPlayerDelegate
{

	[Preserve (Conditional = true)]
	public AVAudioPlayerDelegateWrapper (NativeHandle handle, bool owns)
		: base (handle, owns)
	{
	}

	[UnsupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[Export<Method> ("audioPlayerBeginInterruption:")]
	public void BeginInterruption (global::AVFoundation.AVAudioPlayer player)
	{
		var player__handle__ = player!.GetNonNullHandle (nameof (player));
		global::ObjCRuntime.Messaging.void_objc_msgSend_NativeHandle (this.Handle, global::ObjCRuntime.Selector.GetHandle ("audioPlayerBeginInterruption:"), player__handle__);
		global::System.GC.KeepAlive (this);
		global::System.GC.KeepAlive (player);
	}


	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[Export<Method> ("audioPlayerDecodeErrorDidOccur:error:")]
	public void DecoderError (global::AVFoundation.AVAudioPlayer player, global::Foundation.NSError? error)
	{
		var player__handle__ = player!.GetNonNullHandle (nameof (player));
		var error__handle__ = error?.GetHandle ();
		global::ObjCRuntime.Messaging.void_objc_msgSend_NativeHandle_NativeHandle (this.Handle, global::ObjCRuntime.Selector.GetHandle ("audioPlayerDecodeErrorDidOccur:error:"), player__handle__, error__handle__);
		global::System.GC.KeepAlive (this);
		global::System.GC.KeepAlive (player);
		global::System.GC.KeepAlive (error);
	}


	[UnsupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[Export<Method> ("audioPlayerBeginInterruption:")]
	public void EndInterruption (global::AVFoundation.AVAudioPlayer player)
	{
		var player__handle__ = player!.GetNonNullHandle (nameof (player));
		global::ObjCRuntime.Messaging.void_objc_msgSend_NativeHandle (this.Handle, global::ObjCRuntime.Selector.GetHandle ("audioPlayerBeginInterruption:"), player__handle__);
		global::System.GC.KeepAlive (this);
		global::System.GC.KeepAlive (player);
	}


	[UnsupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[Export<Method> ("audioPlayerEndInterruption:withOptions:")]
	public void EndInterruption (global::AVFoundation.AVAudioPlayer player, global::AVFoundation.AVAudioSessionInterruptionOptions flags)
	{
		var player__handle__ = player!.GetNonNullHandle (nameof (player));
		global::ObjCRuntime.Messaging.void_objc_msgSend_NativeHandle_UIntPtr (this.Handle, global::ObjCRuntime.Selector.GetHandle ("audioPlayerEndInterruption:withOptions:"), player__handle__, (global::AVFoundation.AVAudioSessionInterruptionOptions) (ulong) flags);
		global::System.GC.KeepAlive (this);
		global::System.GC.KeepAlive (player);
	}


	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[Export<Method> ("audioPlayerDidFinishPlaying:successfully:")]
	public void FinishedPlaying (global::AVFoundation.AVAudioPlayer player, bool flag)
	{
		var player__handle__ = player!.GetNonNullHandle (nameof (player));
		global::ObjCRuntime.Messaging.void_objc_msgSend_NativeHandle_bool (this.Handle, global::ObjCRuntime.Selector.GetHandle ("audioPlayerDidFinishPlaying:successfully:"), player__handle__, flag ? (byte) 1 : (byte) 0);
		global::System.GC.KeepAlive (this);
		global::System.GC.KeepAlive (player);
	}

}

[Register ("Microsoft_Macios_Generator_Tests_Protocols_Data_AVAudioPlayerDelegate", false)]
[Model]
[SupportedOSPlatform ("macos")]
[SupportedOSPlatform ("ios")]
[SupportedOSPlatform ("tvos")]
[SupportedOSPlatform ("maccatalyst13.1")]
public unsafe abstract partial class AVAudioPlayerDelegate : NSObject, IAVAudioPlayerDelegate
{
	[UnsupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[Export<Method> ("audioPlayerBeginInterruption:")]
	public virtual partial void BeginInterruption (global::AVFoundation.AVAudioPlayer player)
	{
		throw new global::Foundation.ModelNotImplementedException ();
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[Export<Method> ("audioPlayerDecodeErrorDidOccur:error:")]
	public virtual partial void DecoderError (global::AVFoundation.AVAudioPlayer player, global::Foundation.NSError? error)
	{
		throw new global::Foundation.ModelNotImplementedException ();
	}

	[UnsupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[Export<Method> ("audioPlayerBeginInterruption:")]
	public virtual partial void EndInterruption (global::AVFoundation.AVAudioPlayer player)
	{
		throw new global::Foundation.ModelNotImplementedException ();
	}

	[UnsupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[Export<Method> ("audioPlayerEndInterruption:withOptions:")]
	public virtual partial void EndInterruption (global::AVFoundation.AVAudioPlayer player, global::AVFoundation.AVAudioSessionInterruptionOptions flags)
	{
		throw new global::Foundation.ModelNotImplementedException ();
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[Export<Method> ("audioPlayerDidFinishPlaying:successfully:")]
	public virtual partial void FinishedPlaying (global::AVFoundation.AVAudioPlayer player, bool flag)
	{
		throw new global::Foundation.ModelNotImplementedException ();
	}

}
