TOP=..

include $(TOP)/Make.config

ifndef NO_XCODE
SUBDIRS += sharpie
endif

SUBDIRS += devops

SUBDIRS += mtouch

SUBDIRS+=mlaunch

SUBDIRS += dotnet-linker

ifndef NO_XCODE
SUBDIRS += spawner
endif

SUBDIRS += assembly-preparer
