# YAML pipeline build definition
# https://devdiv.visualstudio.com/DevDiv/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=13947&view=Tab_Tasks
#
# YAML build pipeline based on the Jenkins multi-stage (main branch) build workflow
# https://jenkins.internalx.com/view/Xamarin.MaciOS/job/macios/job/main/
# https://jenkins.internalx.com/view/Xamarin.MaciOS/job/macios/configure

trigger:
  branches:
    include:
      - '*'
    exclude:
      - refs/heads/locfiles/*
      - refs/heads/dev/*
  paths:
    exclude:
      - .github
      - docs
      - CODEOWNERS
      - ISSUE_TEMPLATE.md
      - LICENSE
      - NOTICE.txt
      - SECURITY.MD
      - README.md
      - src/README.md
      - tools/mtouch/README.md
      - msbuild/Xamarin.Localization.MSBuild/README.md

extends:
  template: templates/pipelines/build-pipeline.yml
  parameters:
    isPR: false
    signingSetupSteps: 
      - template: ./templates/sign-and-notarized/setup.yml
        parameters:
          isPR: false
