# YAML pipeline for publishing the test results as a static gitbub page in a different 
# repository:
# This pipeline will trigger in a succesful build of a build with a prBuild tag.

trigger: none
pr: none

resources:
  repositories:
  - repository: self
    checkoutOptions:
      submodules: false  # no need

  - repository: macios.ci
    type: github
    name: xamarin/macios.ci
    ref: refs/heads/main # get main and create the branch from main
    endpoint: xamarin

  pipelines:
  - pipeline: macios
    source: xamarin-macios
    trigger: true # always do trigger
    tags:
      - prBuild # used to identify builds for PRS, this is a workaround to get it working within vsts limits

variables:
- group: xamops-azdev-secrets
- group: Xamarin-Secrets
- group: Xamarin Release
- name: GitHub.Token                                          # Override the GitHub.Token setting defined in the Xamarin Release group
  value: $(github--pat--vs-mobiletools-engineering-service2)  # Use a token dedicated to critical production workflows and help avoid GitHub throttling
- name: AzDoBuildAccess.Token
  value: $(pat--xamarinc--build-access)
- name: system.debug
  value: true


jobs:
- job: publish_results
  displayName: Publish Results
  pool:
    vmImage: ubuntu-latest
  workspace:
    clean: all

  steps:
  - template: templates/publish-html-result.yml 
    parameters:
      reason: 'pr'
