# YAML pipeline for post build operations. 
# This pipeline will execute the tests for the CI on PR as soon as the workloads have been complited.

trigger: none

pr:
  autoCancel: true
  branches:
    include:
      - '*'  # yes, you do need the quote, * has meaning in yamls
  paths:
    exclude:
      - .github
      - docs
      - CODEOWNERS
      - ISSUE_TEMPLATE.md
      - LICENSE
      - NOTICE.txt
      - SECURITY.MD
      - README.md
      - src/README.md
      - tools/mtouch/README.md
      - msbuild/Xamarin.Localization.MSBuild/README.md

# we need to keep the pipeline resource declaration (without a trigger)
# because templates/common/load_configuration.yml uses 'download: macios'
# to fetch the build-configuration artifact.
resources:
  pipelines:
    - pipeline: macios
      source: \Xamarin\Mac-iOS\pr pipelines\xamarin-macios-pr

extends:
  template: templates/pipelines/run-tests-pipeline.yml
  parameters:
    isPR: true
