# YAML pipeline for post build operations. 
# This pipeline will sign the nugets and will prepare them for a release.

trigger: none
pr: none

parameters:

  - name: pushNugets
    type: boolean
    default: true # default to true until otherwhise

  - name: pushNugetsToMaestro
    type: boolean
    default: true

# we cannot use a template in a pipeline context
resources:
  pipelines:
    - pipeline: macios
      source: \Xamarin\Mac-iOS\ci pipelines\xamarin-macios-ci
      trigger:
        branches:
          include:
            - main
            - release-test/*
            - release/*
            - net7.0
            - net8.0
            - net9.0
            - net10.0
            - xcode??
        stages:
          - build_packages

  repositories:
    - repository: self
      checkoutOptions:
        submodules: true

    - repository: yaml-templates
      type: github
      name: xamarin/yaml-templates
      ref: refs/heads/main
      endpoint: xamarin

    - repository: sdk-insertions
      type: github
      name: xamarin/sdk-insertions
      ref: refs/heads/main
      endpoint: xamarin

    - repository: maccore
      type: github
      name: xamarin/maccore
      ref: refs/heads/main
      endpoint: xamarin

    - repository: CustomPipelineTemplates
      type: git
      name: 1ESPipelineTemplates/MicroBuildTemplate

extends:
  template: azure-pipelines/MicroBuild.1ES.Official.yml@CustomPipelineTemplates
  parameters:
    pool:  # default pool to be used for validation jobs
      name: AzurePipelines-EO
      image: 1ESPT-Windows2022
      os: windows
    sdl:
      baseline:
        baselineFile: '$(System.DefaultWorkingDirectory)\\xamarin-macios\\tools\\devops\\governance\\baselines.gdnbaselines'
      suppression:
        suppressionFile: '$(System.DefaultWorkingDirectory)\\xamarin-macios\\tools\\devops\\governance\\suppress.gdnsuppress'
      sourceAnalysisPool:
        name: AzurePipelines-EO
        image: 1ESPT-Windows2022
        os: windows
      tsa:
        configFile: '$(System.DefaultWorkingDirectory)\\xamarin-macios\\tools\\devops\\governance\\tsa_config.gdntsa'
      sbom:
        enabled: false  # we run our on sbom generation
      credscan:
        suppressionsFile: '$(System.DefaultWorkingDirectory)\\xamarin-macios\\tools\\devops\\governance\\CredScanSuppressions.json'
      policheck:
        exclusionsFile: '$(System.DefaultWorkingDirectory)\\xamarin-macios\\tools\\devops\\governance\\PoliCheckExclusions.xml'
      sourceRepositoriesToScan:
        runInSingleJob: true  # run both maccore and macios in the same job
        include:
          - repository: maccore
        exclude:
          - repository: yaml-templates
          - repository: sdk-insertions
    stages:
      - template: ./templates/release/vs-insertion-prep.yml
        parameters:
          stageDisplayNamePrefix: ''
          isPR: false
          repositoryAlias: self
          commit: HEAD
          pushNugets: ${{ parameters.pushNugets }}
          pushNugetsToMaestro: ${{ parameters.pushNugetsToMaestro }}
