// <auto-generated />

#nullable enable

using ARKit;
using Foundation;
using ObjCBindings;
using ObjCRuntime;
using System;

namespace ObjCRuntime;

static partial class Trampolines
{
	// Generate trampolines for compilation
	[UnmanagedFunctionPointerAttribute (CallingConvention.Cdecl)]
	[UserDelegateType (typeof (global::ARKit.GetGeolocationCallback))]
	unsafe internal delegate void DGetGeolocationCallback (global::System.IntPtr block_ptr, global::CoreLocation.CLLocationCoordinate2D coordinate, double altitude, global::ObjCRuntime.NativeHandle error);

	/// <summary>This class bridges native block invocations that call into C#</summary>
	static internal class SDGetGeolocationCallback
	{
		[Preserve (Conditional = true)]
		[UnmanagedCallersOnly]
		[UserDelegateType (typeof (global::ARKit.GetGeolocationCallback))]
		internal static unsafe void Invoke (global::System.IntPtr block_ptr, global::CoreLocation.CLLocationCoordinate2D coordinate, double altitude, global::ObjCRuntime.NativeHandle error)
		{
			var del = global::ObjCRuntime.BlockLiteral.GetTarget<global::ARKit.GetGeolocationCallback> (block_ptr);
			if (del is not null)
			{
				del (coordinate, altitude, global::ObjCRuntime.Runtime.GetNSObject<global::Foundation.NSError> (error)!);
			}
		}

		internal static unsafe global::ObjCRuntime.BlockLiteral CreateNullableBlock (global::ARKit.GetGeolocationCallback? callback)
		{
			if (callback is null)
				return default (global::ObjCRuntime.BlockLiteral);
			return CreateBlock (callback);
		}

		[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
		internal static unsafe global::ObjCRuntime.BlockLiteral CreateBlock (global::ARKit.GetGeolocationCallback callback)
		{
			delegate* unmanaged<global::System.IntPtr, global::CoreLocation.CLLocationCoordinate2D, double, global::ObjCRuntime.NativeHandle, void> trampoline = &Invoke;
			return new global::ObjCRuntime.BlockLiteral (trampoline, callback, typeof (SDGetGeolocationCallback), nameof (Invoke));
		}
	}
	// TODO: generate trampoline for ARKit.GetGeolocationCallback

}
