// <auto-generated />

#nullable enable

using AVFoundation;
using Foundation;
using ObjCBindings;
using ObjCRuntime;
using System;

namespace ObjCRuntime;

static partial class Trampolines
{
	// Generate trampolines for compilation
	[UnmanagedFunctionPointerAttribute (CallingConvention.Cdecl)]
	[UserDelegateType (typeof (global::AVFoundation.AVAssetImageGenerateAsynchronouslyForTimeCompletionHandler))]
	unsafe internal delegate void DAVAssetImageGenerateAsynchronouslyForTimeCompletionHandler (global::System.IntPtr block_ptr, global::ObjCRuntime.NativeHandle imageRef, global::CoreMedia.CMTime actualTime, global::ObjCRuntime.NativeHandle error);

	/// <summary>This class bridges native block invocations that call into C#</summary>
	static internal class SDAVAssetImageGenerateAsynchronouslyForTimeCompletionHandler
	{
		[Preserve (Conditional = true)]
		[UnmanagedCallersOnly]
		[UserDelegateType (typeof (global::AVFoundation.AVAssetImageGenerateAsynchronouslyForTimeCompletionHandler))]
		internal static unsafe void Invoke (global::System.IntPtr block_ptr, global::ObjCRuntime.NativeHandle imageRef, global::CoreMedia.CMTime actualTime, global::ObjCRuntime.NativeHandle error)
		{
			var del = global::ObjCRuntime.BlockLiteral.GetTarget<global::AVFoundation.AVAssetImageGenerateAsynchronouslyForTimeCompletionHandler> (block_ptr);
			if (del is not null)
			{
				del (global::ObjCRuntime.Runtime.GetINativeObject<global::CoreGraphics.CGImage> (imageRef, false)!, actualTime, global::ObjCRuntime.Runtime.GetNSObject<global::Foundation.NSError> (error)!);
			}
		}

		internal static unsafe global::ObjCRuntime.BlockLiteral CreateNullableBlock (global::AVFoundation.AVAssetImageGenerateAsynchronouslyForTimeCompletionHandler? callback)
		{
			if (callback is null)
				return default (global::ObjCRuntime.BlockLiteral);
			return CreateBlock (callback);
		}

		[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
		internal static unsafe global::ObjCRuntime.BlockLiteral CreateBlock (global::AVFoundation.AVAssetImageGenerateAsynchronouslyForTimeCompletionHandler callback)
		{
			delegate* unmanaged<global::System.IntPtr, global::ObjCRuntime.NativeHandle, global::CoreMedia.CMTime, global::ObjCRuntime.NativeHandle, void> trampoline = &Invoke;
			return new global::ObjCRuntime.BlockLiteral (trampoline, callback, typeof (SDAVAssetImageGenerateAsynchronouslyForTimeCompletionHandler), nameof (Invoke));
		}
	}
	// TODO: generate trampoline for AVFoundation.AVAssetImageGenerateAsynchronouslyForTimeCompletionHandler

	[UnmanagedFunctionPointerAttribute (CallingConvention.Cdecl)]
	[UserDelegateType (typeof (global::AVFoundation.AVAssetImageGeneratorCompletionHandler))]
	unsafe internal delegate void DAVAssetImageGeneratorCompletionHandler (global::System.IntPtr block_ptr, global::CoreMedia.CMTime requestedTime, IntPtr imageRef, global::CoreMedia.CMTime actualTime, global::System.IntPtr result, global::ObjCRuntime.NativeHandle error);

	/// <summary>This class bridges native block invocations that call into C#</summary>
	static internal class SDAVAssetImageGeneratorCompletionHandler
	{
		[Preserve (Conditional = true)]
		[UnmanagedCallersOnly]
		[UserDelegateType (typeof (global::AVFoundation.AVAssetImageGeneratorCompletionHandler))]
		internal static unsafe void Invoke (global::System.IntPtr block_ptr, global::CoreMedia.CMTime requestedTime, IntPtr imageRef, global::CoreMedia.CMTime actualTime, global::System.IntPtr result, global::ObjCRuntime.NativeHandle error)
		{
			var del = global::ObjCRuntime.BlockLiteral.GetTarget<global::AVFoundation.AVAssetImageGeneratorCompletionHandler> (block_ptr);
			if (del is not null)
			{
				del (requestedTime, imageRef, actualTime, (global::AVFoundation.AVAssetImageGeneratorResult) (long) result, global::ObjCRuntime.Runtime.GetNSObject<global::Foundation.NSError> (error)!);
			}
		}

		internal static unsafe global::ObjCRuntime.BlockLiteral CreateNullableBlock (global::AVFoundation.AVAssetImageGeneratorCompletionHandler? callback)
		{
			if (callback is null)
				return default (global::ObjCRuntime.BlockLiteral);
			return CreateBlock (callback);
		}

		[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
		internal static unsafe global::ObjCRuntime.BlockLiteral CreateBlock (global::AVFoundation.AVAssetImageGeneratorCompletionHandler callback)
		{
			delegate* unmanaged<global::System.IntPtr, global::CoreMedia.CMTime, IntPtr, global::CoreMedia.CMTime, global::System.IntPtr, global::ObjCRuntime.NativeHandle, void> trampoline = &Invoke;
			return new global::ObjCRuntime.BlockLiteral (trampoline, callback, typeof (SDAVAssetImageGeneratorCompletionHandler), nameof (Invoke));
		}
	}
	// TODO: generate trampoline for AVFoundation.AVAssetImageGeneratorCompletionHandler

	[UnmanagedFunctionPointerAttribute (CallingConvention.Cdecl)]
	[UserDelegateType (typeof (global::AVFoundation.AVAssetImageGeneratorCompletionHandler2))]
	unsafe internal delegate void DAVAssetImageGeneratorCompletionHandler2 (global::System.IntPtr block_ptr, global::CoreMedia.CMTime requestedTime, global::ObjCRuntime.NativeHandle imageRef, global::CoreMedia.CMTime actualTime, global::System.IntPtr result, global::ObjCRuntime.NativeHandle error);

	/// <summary>This class bridges native block invocations that call into C#</summary>
	static internal class SDAVAssetImageGeneratorCompletionHandler2
	{
		[Preserve (Conditional = true)]
		[UnmanagedCallersOnly]
		[UserDelegateType (typeof (global::AVFoundation.AVAssetImageGeneratorCompletionHandler2))]
		internal static unsafe void Invoke (global::System.IntPtr block_ptr, global::CoreMedia.CMTime requestedTime, global::ObjCRuntime.NativeHandle imageRef, global::CoreMedia.CMTime actualTime, global::System.IntPtr result, global::ObjCRuntime.NativeHandle error)
		{
			var del = global::ObjCRuntime.BlockLiteral.GetTarget<global::AVFoundation.AVAssetImageGeneratorCompletionHandler2> (block_ptr);
			if (del is not null)
			{
				del (requestedTime, global::ObjCRuntime.Runtime.GetINativeObject<global::CoreGraphics.CGImage> (imageRef, false)!, actualTime, (global::AVFoundation.AVAssetImageGeneratorResult) (long) result, global::ObjCRuntime.Runtime.GetNSObject<global::Foundation.NSError> (error)!);
			}
		}

		internal static unsafe global::ObjCRuntime.BlockLiteral CreateNullableBlock (global::AVFoundation.AVAssetImageGeneratorCompletionHandler2? callback)
		{
			if (callback is null)
				return default (global::ObjCRuntime.BlockLiteral);
			return CreateBlock (callback);
		}

		[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
		internal static unsafe global::ObjCRuntime.BlockLiteral CreateBlock (global::AVFoundation.AVAssetImageGeneratorCompletionHandler2 callback)
		{
			delegate* unmanaged<global::System.IntPtr, global::CoreMedia.CMTime, global::ObjCRuntime.NativeHandle, global::CoreMedia.CMTime, global::System.IntPtr, global::ObjCRuntime.NativeHandle, void> trampoline = &Invoke;
			return new global::ObjCRuntime.BlockLiteral (trampoline, callback, typeof (SDAVAssetImageGeneratorCompletionHandler2), nameof (Invoke));
		}
	}
	// TODO: generate trampoline for AVFoundation.AVAssetImageGeneratorCompletionHandler2

	[UnmanagedFunctionPointerAttribute (CallingConvention.Cdecl)]
	[UserDelegateType (typeof (global::AVFoundation.AVAssetPlaybackAssistantLoadPlaybackConfigurationOptionsHandler))]
	unsafe internal delegate void DAVAssetPlaybackAssistantLoadPlaybackConfigurationOptionsHandler (global::System.IntPtr block_ptr, global::ObjCRuntime.NativeHandle playbackConfigurationOptions);

	/// <summary>This class bridges native block invocations that call into C#</summary>
	static internal class SDAVAssetPlaybackAssistantLoadPlaybackConfigurationOptionsHandler
	{
		[Preserve (Conditional = true)]
		[UnmanagedCallersOnly]
		[UserDelegateType (typeof (global::AVFoundation.AVAssetPlaybackAssistantLoadPlaybackConfigurationOptionsHandler))]
		internal static unsafe void Invoke (global::System.IntPtr block_ptr, global::ObjCRuntime.NativeHandle playbackConfigurationOptions)
		{
			var del = global::ObjCRuntime.BlockLiteral.GetTarget<global::AVFoundation.AVAssetPlaybackAssistantLoadPlaybackConfigurationOptionsHandler> (block_ptr);
			if (del is not null)
			{
				del (global::CoreFoundation.CFArray.StringArrayFromHandle (playbackConfigurationOptions)!);
			}
		}

		internal static unsafe global::ObjCRuntime.BlockLiteral CreateNullableBlock (global::AVFoundation.AVAssetPlaybackAssistantLoadPlaybackConfigurationOptionsHandler? callback)
		{
			if (callback is null)
				return default (global::ObjCRuntime.BlockLiteral);
			return CreateBlock (callback);
		}

		[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
		internal static unsafe global::ObjCRuntime.BlockLiteral CreateBlock (global::AVFoundation.AVAssetPlaybackAssistantLoadPlaybackConfigurationOptionsHandler callback)
		{
			delegate* unmanaged<global::System.IntPtr, global::ObjCRuntime.NativeHandle, void> trampoline = &Invoke;
			return new global::ObjCRuntime.BlockLiteral (trampoline, callback, typeof (SDAVAssetPlaybackAssistantLoadPlaybackConfigurationOptionsHandler), nameof (Invoke));
		}
	}
	// TODO: generate trampoline for AVFoundation.AVAssetPlaybackAssistantLoadPlaybackConfigurationOptionsHandler

	[UnmanagedFunctionPointerAttribute (CallingConvention.Cdecl)]
	[UserDelegateType (typeof (global::AVFoundation.AVAudioConverterInputHandler))]
	unsafe internal delegate global::ObjCRuntime.NativeHandle DAVAudioConverterInputHandler (global::System.IntPtr block_ptr, uint inNumberOfPackets, global::System.IntPtr* outStatus);

	/// <summary>This class bridges native block invocations that call into C#</summary>
	static internal class SDAVAudioConverterInputHandler
	{
		[Preserve (Conditional = true)]
		[UnmanagedCallersOnly]
		[UserDelegateType (typeof (global::AVFoundation.AVAudioConverterInputHandler))]
		internal static unsafe global::ObjCRuntime.NativeHandle Invoke (global::System.IntPtr block_ptr, uint inNumberOfPackets, global::System.IntPtr* outStatus)
		{
			var del = global::ObjCRuntime.BlockLiteral.GetTarget<global::AVFoundation.AVAudioConverterInputHandler> (block_ptr);
			if (del is not null)
			{
				var ret = del (inNumberOfPackets, out global::System.Runtime.CompilerServices.Unsafe.AsRef<global::AVFoundation.AVAudioConverterInputStatus> (outStatus));
				return global::ObjCRuntime.Runtime.RetainAndAutoreleaseNSObject (ret);
			}
			return default;
		}

		internal static unsafe global::ObjCRuntime.BlockLiteral CreateNullableBlock (global::AVFoundation.AVAudioConverterInputHandler? callback)
		{
			if (callback is null)
				return default (global::ObjCRuntime.BlockLiteral);
			return CreateBlock (callback);
		}

		[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
		internal static unsafe global::ObjCRuntime.BlockLiteral CreateBlock (global::AVFoundation.AVAudioConverterInputHandler callback)
		{
			delegate* unmanaged<global::System.IntPtr, uint, global::System.IntPtr*, global::ObjCRuntime.NativeHandle> trampoline = &Invoke;
			return new global::ObjCRuntime.BlockLiteral (trampoline, callback, typeof (SDAVAudioConverterInputHandler), nameof (Invoke));
		}
	}
	// TODO: generate trampoline for AVFoundation.AVAudioConverterInputHandler

	[UnmanagedFunctionPointerAttribute (CallingConvention.Cdecl)]
	[UserDelegateType (typeof (global::AVFoundation.AVAudioEngineManualRenderingBlock))]
	unsafe internal delegate global::System.IntPtr DAVAudioEngineManualRenderingBlock (global::System.IntPtr block_ptr, uint numberOfFrames, global::ObjCRuntime.NativeHandle outBuffer, int* outError);

	/// <summary>This class bridges native block invocations that call into C#</summary>
	static internal class SDAVAudioEngineManualRenderingBlock
	{
		[Preserve (Conditional = true)]
		[UnmanagedCallersOnly]
		[UserDelegateType (typeof (global::AVFoundation.AVAudioEngineManualRenderingBlock))]
		internal static unsafe global::System.IntPtr Invoke (global::System.IntPtr block_ptr, uint numberOfFrames, global::ObjCRuntime.NativeHandle outBuffer, int* outError)
		{
			var del = global::ObjCRuntime.BlockLiteral.GetTarget<global::AVFoundation.AVAudioEngineManualRenderingBlock> (block_ptr);
			if (del is not null)
			{
				var ret = del (numberOfFrames, new global::AudioToolbox.AudioBuffers (outBuffer), ref global::System.Runtime.CompilerServices.Unsafe.AsRef<int> (outError));
				return (IntPtr) (long) ret;
			}
			return default;
		}

		internal static unsafe global::ObjCRuntime.BlockLiteral CreateNullableBlock (global::AVFoundation.AVAudioEngineManualRenderingBlock? callback)
		{
			if (callback is null)
				return default (global::ObjCRuntime.BlockLiteral);
			return CreateBlock (callback);
		}

		[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
		internal static unsafe global::ObjCRuntime.BlockLiteral CreateBlock (global::AVFoundation.AVAudioEngineManualRenderingBlock callback)
		{
			delegate* unmanaged<global::System.IntPtr, uint, global::ObjCRuntime.NativeHandle, int*, global::System.IntPtr> trampoline = &Invoke;
			return new global::ObjCRuntime.BlockLiteral (trampoline, callback, typeof (SDAVAudioEngineManualRenderingBlock), nameof (Invoke));
		}
	}
	// TODO: generate trampoline for AVFoundation.AVAudioEngineManualRenderingBlock

	[UnmanagedFunctionPointerAttribute (CallingConvention.Cdecl)]
	[UserDelegateType (typeof (global::AVFoundation.AVAudioIONodeInputBlock))]
	unsafe internal delegate global::ObjCRuntime.NativeHandle DAVAudioIONodeInputBlock (global::System.IntPtr block_ptr, uint frameCount);

	/// <summary>This class bridges native block invocations that call into C#</summary>
	static internal class SDAVAudioIONodeInputBlock
	{
		[Preserve (Conditional = true)]
		[UnmanagedCallersOnly]
		[UserDelegateType (typeof (global::AVFoundation.AVAudioIONodeInputBlock))]
		internal static unsafe global::ObjCRuntime.NativeHandle Invoke (global::System.IntPtr block_ptr, uint frameCount)
		{
			var del = global::ObjCRuntime.BlockLiteral.GetTarget<global::AVFoundation.AVAudioIONodeInputBlock> (block_ptr);
			if (del is not null)
			{
				var ret = del (frameCount);
				return global::ObjCRuntime.Runtime.RetainAndAutoreleaseNativeObject (ret);
			}
			return default;
		}

		internal static unsafe global::ObjCRuntime.BlockLiteral CreateNullableBlock (global::AVFoundation.AVAudioIONodeInputBlock? callback)
		{
			if (callback is null)
				return default (global::ObjCRuntime.BlockLiteral);
			return CreateBlock (callback);
		}

		[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
		internal static unsafe global::ObjCRuntime.BlockLiteral CreateBlock (global::AVFoundation.AVAudioIONodeInputBlock callback)
		{
			delegate* unmanaged<global::System.IntPtr, uint, global::ObjCRuntime.NativeHandle> trampoline = &Invoke;
			return new global::ObjCRuntime.BlockLiteral (trampoline, callback, typeof (SDAVAudioIONodeInputBlock), nameof (Invoke));
		}
	}
	// TODO: generate trampoline for AVFoundation.AVAudioIONodeInputBlock

	[UnmanagedFunctionPointerAttribute (CallingConvention.Cdecl)]
	[UserDelegateType (typeof (global::AVFoundation.AVAudioInputNodeMutedSpeechEventListener))]
	unsafe internal delegate void DAVAudioInputNodeMutedSpeechEventListener (global::System.IntPtr block_ptr, global::System.IntPtr event);

	/// <summary>This class bridges native block invocations that call into C#</summary>
	static internal class SDAVAudioInputNodeMutedSpeechEventListener
	{
		[Preserve (Conditional = true)]
		[UnmanagedCallersOnly]
		[UserDelegateType (typeof (global::AVFoundation.AVAudioInputNodeMutedSpeechEventListener))]
		internal static unsafe void Invoke (global::System.IntPtr block_ptr, global::System.IntPtr event)
		{
			var del = global::ObjCRuntime.BlockLiteral.GetTarget<global::AVFoundation.AVAudioInputNodeMutedSpeechEventListener> (block_ptr);
			if (del is not null)
			{
				del ((global::AVFoundation.AVAudioVoiceProcessingSpeechActivityEvent) (long) event);
			}
		}

		internal static unsafe global::ObjCRuntime.BlockLiteral CreateNullableBlock (global::AVFoundation.AVAudioInputNodeMutedSpeechEventListener? callback)
		{
			if (callback is null)
				return default (global::ObjCRuntime.BlockLiteral);
			return CreateBlock (callback);
		}

		[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
		internal static unsafe global::ObjCRuntime.BlockLiteral CreateBlock (global::AVFoundation.AVAudioInputNodeMutedSpeechEventListener callback)
		{
			delegate* unmanaged<global::System.IntPtr, global::System.IntPtr, void> trampoline = &Invoke;
			return new global::ObjCRuntime.BlockLiteral (trampoline, callback, typeof (SDAVAudioInputNodeMutedSpeechEventListener), nameof (Invoke));
		}
	}
	// TODO: generate trampoline for AVFoundation.AVAudioInputNodeMutedSpeechEventListener

	[UnmanagedFunctionPointerAttribute (CallingConvention.Cdecl)]
	[UserDelegateType (typeof (global::AVFoundation.AVAudioNodeTapBlock))]
	unsafe internal delegate void DAVAudioNodeTapBlock (global::System.IntPtr block_ptr, global::ObjCRuntime.NativeHandle buffer, global::ObjCRuntime.NativeHandle when);

	/// <summary>This class bridges native block invocations that call into C#</summary>
	static internal class SDAVAudioNodeTapBlock
	{
		[Preserve (Conditional = true)]
		[UnmanagedCallersOnly]
		[UserDelegateType (typeof (global::AVFoundation.AVAudioNodeTapBlock))]
		internal static unsafe void Invoke (global::System.IntPtr block_ptr, global::ObjCRuntime.NativeHandle buffer, global::ObjCRuntime.NativeHandle when)
		{
			var del = global::ObjCRuntime.BlockLiteral.GetTarget<global::AVFoundation.AVAudioNodeTapBlock> (block_ptr);
			if (del is not null)
			{
				del (global::ObjCRuntime.Runtime.GetNSObject<global::AVFoundation.AVAudioPcmBuffer> (buffer)!, global::ObjCRuntime.Runtime.GetNSObject<global::AVFoundation.AVAudioTime> (when)!);
			}
		}

		internal static unsafe global::ObjCRuntime.BlockLiteral CreateNullableBlock (global::AVFoundation.AVAudioNodeTapBlock? callback)
		{
			if (callback is null)
				return default (global::ObjCRuntime.BlockLiteral);
			return CreateBlock (callback);
		}

		[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
		internal static unsafe global::ObjCRuntime.BlockLiteral CreateBlock (global::AVFoundation.AVAudioNodeTapBlock callback)
		{
			delegate* unmanaged<global::System.IntPtr, global::ObjCRuntime.NativeHandle, global::ObjCRuntime.NativeHandle, void> trampoline = &Invoke;
			return new global::ObjCRuntime.BlockLiteral (trampoline, callback, typeof (SDAVAudioNodeTapBlock), nameof (Invoke));
		}
	}
	// TODO: generate trampoline for AVFoundation.AVAudioNodeTapBlock

	[UnmanagedFunctionPointerAttribute (CallingConvention.Cdecl)]
	[UserDelegateType (typeof (global::AVFoundation.AVAudioSequencerUserCallback))]
	unsafe internal delegate void DAVAudioSequencerUserCallback (global::System.IntPtr block_ptr, global::ObjCRuntime.NativeHandle track, global::ObjCRuntime.NativeHandle userData, double timeStamp);

	/// <summary>This class bridges native block invocations that call into C#</summary>
	static internal class SDAVAudioSequencerUserCallback
	{
		[Preserve (Conditional = true)]
		[UnmanagedCallersOnly]
		[UserDelegateType (typeof (global::AVFoundation.AVAudioSequencerUserCallback))]
		internal static unsafe void Invoke (global::System.IntPtr block_ptr, global::ObjCRuntime.NativeHandle track, global::ObjCRuntime.NativeHandle userData, double timeStamp)
		{
			var del = global::ObjCRuntime.BlockLiteral.GetTarget<global::AVFoundation.AVAudioSequencerUserCallback> (block_ptr);
			if (del is not null)
			{
				del (global::ObjCRuntime.Runtime.GetNSObject<global::AVFoundation.AVMusicTrack> (track)!, global::ObjCRuntime.Runtime.GetNSObject<global::Foundation.NSData> (userData)!, timeStamp);
			}
		}

		internal static unsafe global::ObjCRuntime.BlockLiteral CreateNullableBlock (global::AVFoundation.AVAudioSequencerUserCallback? callback)
		{
			if (callback is null)
				return default (global::ObjCRuntime.BlockLiteral);
			return CreateBlock (callback);
		}

		[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
		internal static unsafe global::ObjCRuntime.BlockLiteral CreateBlock (global::AVFoundation.AVAudioSequencerUserCallback callback)
		{
			delegate* unmanaged<global::System.IntPtr, global::ObjCRuntime.NativeHandle, global::ObjCRuntime.NativeHandle, double, void> trampoline = &Invoke;
			return new global::ObjCRuntime.BlockLiteral (trampoline, callback, typeof (SDAVAudioSequencerUserCallback), nameof (Invoke));
		}
	}
	// TODO: generate trampoline for AVFoundation.AVAudioSequencerUserCallback

	[UnmanagedFunctionPointerAttribute (CallingConvention.Cdecl)]
	[UserDelegateType (typeof (global::AVFoundation.AVAudioSinkNodeReceiverHandlerRaw))]
	unsafe internal delegate int DAVAudioSinkNodeReceiverHandlerRaw (global::System.IntPtr block_ptr, IntPtr timestamp, uint frameCount, IntPtr inputData);

	/// <summary>This class bridges native block invocations that call into C#</summary>
	static internal class SDAVAudioSinkNodeReceiverHandlerRaw
	{
		[Preserve (Conditional = true)]
		[UnmanagedCallersOnly]
		[UserDelegateType (typeof (global::AVFoundation.AVAudioSinkNodeReceiverHandlerRaw))]
		internal static unsafe int Invoke (global::System.IntPtr block_ptr, IntPtr timestamp, uint frameCount, IntPtr inputData)
		{
			var del = global::ObjCRuntime.BlockLiteral.GetTarget<global::AVFoundation.AVAudioSinkNodeReceiverHandlerRaw> (block_ptr);
			if (del is not null)
			{
				var ret = del (timestamp, frameCount, inputData);
				return ret;
			}
			return default;
		}

		internal static unsafe global::ObjCRuntime.BlockLiteral CreateNullableBlock (global::AVFoundation.AVAudioSinkNodeReceiverHandlerRaw? callback)
		{
			if (callback is null)
				return default (global::ObjCRuntime.BlockLiteral);
			return CreateBlock (callback);
		}

		[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
		internal static unsafe global::ObjCRuntime.BlockLiteral CreateBlock (global::AVFoundation.AVAudioSinkNodeReceiverHandlerRaw callback)
		{
			delegate* unmanaged<global::System.IntPtr, IntPtr, uint, IntPtr, int> trampoline = &Invoke;
			return new global::ObjCRuntime.BlockLiteral (trampoline, callback, typeof (SDAVAudioSinkNodeReceiverHandlerRaw), nameof (Invoke));
		}
	}
	// TODO: generate trampoline for AVFoundation.AVAudioSinkNodeReceiverHandlerRaw

	[UnmanagedFunctionPointerAttribute (CallingConvention.Cdecl)]
	[UserDelegateType (typeof (global::AVFoundation.AVAudioSourceNodeRenderHandlerRaw))]
	unsafe internal delegate int DAVAudioSourceNodeRenderHandlerRaw (global::System.IntPtr block_ptr, IntPtr isSilence, IntPtr timestamp, uint frameCount, IntPtr outputData);

	/// <summary>This class bridges native block invocations that call into C#</summary>
	static internal class SDAVAudioSourceNodeRenderHandlerRaw
	{
		[Preserve (Conditional = true)]
		[UnmanagedCallersOnly]
		[UserDelegateType (typeof (global::AVFoundation.AVAudioSourceNodeRenderHandlerRaw))]
		internal static unsafe int Invoke (global::System.IntPtr block_ptr, IntPtr isSilence, IntPtr timestamp, uint frameCount, IntPtr outputData)
		{
			var del = global::ObjCRuntime.BlockLiteral.GetTarget<global::AVFoundation.AVAudioSourceNodeRenderHandlerRaw> (block_ptr);
			if (del is not null)
			{
				var ret = del (isSilence, timestamp, frameCount, outputData);
				return ret;
			}
			return default;
		}

		internal static unsafe global::ObjCRuntime.BlockLiteral CreateNullableBlock (global::AVFoundation.AVAudioSourceNodeRenderHandlerRaw? callback)
		{
			if (callback is null)
				return default (global::ObjCRuntime.BlockLiteral);
			return CreateBlock (callback);
		}

		[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
		internal static unsafe global::ObjCRuntime.BlockLiteral CreateBlock (global::AVFoundation.AVAudioSourceNodeRenderHandlerRaw callback)
		{
			delegate* unmanaged<global::System.IntPtr, IntPtr, IntPtr, uint, IntPtr, int> trampoline = &Invoke;
			return new global::ObjCRuntime.BlockLiteral (trampoline, callback, typeof (SDAVAudioSourceNodeRenderHandlerRaw), nameof (Invoke));
		}
	}
	// TODO: generate trampoline for AVFoundation.AVAudioSourceNodeRenderHandlerRaw

	[UnmanagedFunctionPointerAttribute (CallingConvention.Cdecl)]
	[UserDelegateType (typeof (global::AVFoundation.AVAudioUnitComponentFilter))]
	unsafe internal delegate byte DAVAudioUnitComponentFilter (global::System.IntPtr block_ptr, global::ObjCRuntime.NativeHandle comp, byte* stop);

	/// <summary>This class bridges native block invocations that call into C#</summary>
	static internal class SDAVAudioUnitComponentFilter
	{
		[Preserve (Conditional = true)]
		[UnmanagedCallersOnly]
		[UserDelegateType (typeof (global::AVFoundation.AVAudioUnitComponentFilter))]
		internal static unsafe byte Invoke (global::System.IntPtr block_ptr, global::ObjCRuntime.NativeHandle comp, byte* stop)
		{
			var del = global::ObjCRuntime.BlockLiteral.GetTarget<global::AVFoundation.AVAudioUnitComponentFilter> (block_ptr);
			if (del is not null)
			{
				bool __xamarin_bool__1 = *stop != 0;
				var ret = del (global::ObjCRuntime.Runtime.GetNSObject<global::AVFoundation.AVAudioUnitComponent> (comp)!, ref __xamarin_bool__1);
				*stop = __xamarin_bool__1 ? (byte)1 : (byte)0;
				return ret ? (byte) 1 : (byte) 0;
			}
			return default;
		}

		internal static unsafe global::ObjCRuntime.BlockLiteral CreateNullableBlock (global::AVFoundation.AVAudioUnitComponentFilter? callback)
		{
			if (callback is null)
				return default (global::ObjCRuntime.BlockLiteral);
			return CreateBlock (callback);
		}

		[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
		internal static unsafe global::ObjCRuntime.BlockLiteral CreateBlock (global::AVFoundation.AVAudioUnitComponentFilter callback)
		{
			delegate* unmanaged<global::System.IntPtr, global::ObjCRuntime.NativeHandle, byte*, byte> trampoline = &Invoke;
			return new global::ObjCRuntime.BlockLiteral (trampoline, callback, typeof (SDAVAudioUnitComponentFilter), nameof (Invoke));
		}
	}
	// TODO: generate trampoline for AVFoundation.AVAudioUnitComponentFilter

	[UnmanagedFunctionPointerAttribute (CallingConvention.Cdecl)]
	[UserDelegateType (typeof (global::AVFoundation.AVCaptureCompletionHandler))]
	unsafe internal delegate void DAVCaptureCompletionHandler (global::System.IntPtr block_ptr, global::ObjCRuntime.NativeHandle imageDataSampleBuffer, global::ObjCRuntime.NativeHandle error);

	/// <summary>This class bridges native block invocations that call into C#</summary>
	static internal class SDAVCaptureCompletionHandler
	{
		[Preserve (Conditional = true)]
		[UnmanagedCallersOnly]
		[UserDelegateType (typeof (global::AVFoundation.AVCaptureCompletionHandler))]
		internal static unsafe void Invoke (global::System.IntPtr block_ptr, global::ObjCRuntime.NativeHandle imageDataSampleBuffer, global::ObjCRuntime.NativeHandle error)
		{
			var del = global::ObjCRuntime.BlockLiteral.GetTarget<global::AVFoundation.AVCaptureCompletionHandler> (block_ptr);
			if (del is not null)
			{
				del (imageDataSampleBuffer == IntPtr.Zero ? null! : new global::CoreMedia.CMSampleBuffer (imageDataSampleBuffer, false), global::ObjCRuntime.Runtime.GetNSObject<global::Foundation.NSError> (error)!);
			}
		}

		internal static unsafe global::ObjCRuntime.BlockLiteral CreateNullableBlock (global::AVFoundation.AVCaptureCompletionHandler? callback)
		{
			if (callback is null)
				return default (global::ObjCRuntime.BlockLiteral);
			return CreateBlock (callback);
		}

		[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
		internal static unsafe global::ObjCRuntime.BlockLiteral CreateBlock (global::AVFoundation.AVCaptureCompletionHandler callback)
		{
			delegate* unmanaged<global::System.IntPtr, global::ObjCRuntime.NativeHandle, global::ObjCRuntime.NativeHandle, void> trampoline = &Invoke;
			return new global::ObjCRuntime.BlockLiteral (trampoline, callback, typeof (SDAVCaptureCompletionHandler), nameof (Invoke));
		}
	}
	// TODO: generate trampoline for AVFoundation.AVCaptureCompletionHandler

	[UnmanagedFunctionPointerAttribute (CallingConvention.Cdecl)]
	[UserDelegateType (typeof (global::AVFoundation.AVCaptureIndexPickerCallback))]
	unsafe internal delegate void DAVCaptureIndexPickerCallback (global::System.IntPtr block_ptr, IntPtr newValue);

	/// <summary>This class bridges native block invocations that call into C#</summary>
	static internal class SDAVCaptureIndexPickerCallback
	{
		[Preserve (Conditional = true)]
		[UnmanagedCallersOnly]
		[UserDelegateType (typeof (global::AVFoundation.AVCaptureIndexPickerCallback))]
		internal static unsafe void Invoke (global::System.IntPtr block_ptr, IntPtr newValue)
		{
			var del = global::ObjCRuntime.BlockLiteral.GetTarget<global::AVFoundation.AVCaptureIndexPickerCallback> (block_ptr);
			if (del is not null)
			{
				del (newValue);
			}
		}

		internal static unsafe global::ObjCRuntime.BlockLiteral CreateNullableBlock (global::AVFoundation.AVCaptureIndexPickerCallback? callback)
		{
			if (callback is null)
				return default (global::ObjCRuntime.BlockLiteral);
			return CreateBlock (callback);
		}

		[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
		internal static unsafe global::ObjCRuntime.BlockLiteral CreateBlock (global::AVFoundation.AVCaptureIndexPickerCallback callback)
		{
			delegate* unmanaged<global::System.IntPtr, IntPtr, void> trampoline = &Invoke;
			return new global::ObjCRuntime.BlockLiteral (trampoline, callback, typeof (SDAVCaptureIndexPickerCallback), nameof (Invoke));
		}
	}
	// TODO: generate trampoline for AVFoundation.AVCaptureIndexPickerCallback

	[UnmanagedFunctionPointerAttribute (CallingConvention.Cdecl)]
	[UserDelegateType (typeof (global::AVFoundation.AVCaptureIndexPickerTitleTransform))]
	unsafe internal delegate global::ObjCRuntime.NativeHandle DAVCaptureIndexPickerTitleTransform (global::System.IntPtr block_ptr, IntPtr index);

	/// <summary>This class bridges native block invocations that call into C#</summary>
	static internal class SDAVCaptureIndexPickerTitleTransform
	{
		[Preserve (Conditional = true)]
		[UnmanagedCallersOnly]
		[UserDelegateType (typeof (global::AVFoundation.AVCaptureIndexPickerTitleTransform))]
		internal static unsafe global::ObjCRuntime.NativeHandle Invoke (global::System.IntPtr block_ptr, IntPtr index)
		{
			var del = global::ObjCRuntime.BlockLiteral.GetTarget<global::AVFoundation.AVCaptureIndexPickerTitleTransform> (block_ptr);
			if (del is not null)
			{
				var ret = del (index);
				return NFString.CreateNative (ret, true);
			}
			return default;
		}

		internal static unsafe global::ObjCRuntime.BlockLiteral CreateNullableBlock (global::AVFoundation.AVCaptureIndexPickerTitleTransform? callback)
		{
			if (callback is null)
				return default (global::ObjCRuntime.BlockLiteral);
			return CreateBlock (callback);
		}

		[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
		internal static unsafe global::ObjCRuntime.BlockLiteral CreateBlock (global::AVFoundation.AVCaptureIndexPickerTitleTransform callback)
		{
			delegate* unmanaged<global::System.IntPtr, IntPtr, global::ObjCRuntime.NativeHandle> trampoline = &Invoke;
			return new global::ObjCRuntime.BlockLiteral (trampoline, callback, typeof (SDAVCaptureIndexPickerTitleTransform), nameof (Invoke));
		}
	}
	// TODO: generate trampoline for AVFoundation.AVCaptureIndexPickerTitleTransform

	[UnmanagedFunctionPointerAttribute (CallingConvention.Cdecl)]
	[UserDelegateType (typeof (global::AVFoundation.AVCaptureSliderCallback))]
	unsafe internal delegate void DAVCaptureSliderCallback (global::System.IntPtr block_ptr, float newValue);

	/// <summary>This class bridges native block invocations that call into C#</summary>
	static internal class SDAVCaptureSliderCallback
	{
		[Preserve (Conditional = true)]
		[UnmanagedCallersOnly]
		[UserDelegateType (typeof (global::AVFoundation.AVCaptureSliderCallback))]
		internal static unsafe void Invoke (global::System.IntPtr block_ptr, float newValue)
		{
			var del = global::ObjCRuntime.BlockLiteral.GetTarget<global::AVFoundation.AVCaptureSliderCallback> (block_ptr);
			if (del is not null)
			{
				del (newValue);
			}
		}

		internal static unsafe global::ObjCRuntime.BlockLiteral CreateNullableBlock (global::AVFoundation.AVCaptureSliderCallback? callback)
		{
			if (callback is null)
				return default (global::ObjCRuntime.BlockLiteral);
			return CreateBlock (callback);
		}

		[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
		internal static unsafe global::ObjCRuntime.BlockLiteral CreateBlock (global::AVFoundation.AVCaptureSliderCallback callback)
		{
			delegate* unmanaged<global::System.IntPtr, float, void> trampoline = &Invoke;
			return new global::ObjCRuntime.BlockLiteral (trampoline, callback, typeof (SDAVCaptureSliderCallback), nameof (Invoke));
		}
	}
	// TODO: generate trampoline for AVFoundation.AVCaptureSliderCallback

	[UnmanagedFunctionPointerAttribute (CallingConvention.Cdecl)]
	[UserDelegateType (typeof (global::AVFoundation.AVCaptureSystemExposureBiasSliderCallback))]
	unsafe internal delegate void DAVCaptureSystemExposureBiasSliderCallback (global::System.IntPtr block_ptr, global::System.Runtime.InteropServices.NFloat exposureTargetBias);

	/// <summary>This class bridges native block invocations that call into C#</summary>
	static internal class SDAVCaptureSystemExposureBiasSliderCallback
	{
		[Preserve (Conditional = true)]
		[UnmanagedCallersOnly]
		[UserDelegateType (typeof (global::AVFoundation.AVCaptureSystemExposureBiasSliderCallback))]
		internal static unsafe void Invoke (global::System.IntPtr block_ptr, global::System.Runtime.InteropServices.NFloat exposureTargetBias)
		{
			var del = global::ObjCRuntime.BlockLiteral.GetTarget<global::AVFoundation.AVCaptureSystemExposureBiasSliderCallback> (block_ptr);
			if (del is not null)
			{
				del (exposureTargetBias);
			}
		}

		internal static unsafe global::ObjCRuntime.BlockLiteral CreateNullableBlock (global::AVFoundation.AVCaptureSystemExposureBiasSliderCallback? callback)
		{
			if (callback is null)
				return default (global::ObjCRuntime.BlockLiteral);
			return CreateBlock (callback);
		}

		[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
		internal static unsafe global::ObjCRuntime.BlockLiteral CreateBlock (global::AVFoundation.AVCaptureSystemExposureBiasSliderCallback callback)
		{
			delegate* unmanaged<global::System.IntPtr, global::System.Runtime.InteropServices.NFloat, void> trampoline = &Invoke;
			return new global::ObjCRuntime.BlockLiteral (trampoline, callback, typeof (SDAVCaptureSystemExposureBiasSliderCallback), nameof (Invoke));
		}
	}
	// TODO: generate trampoline for AVFoundation.AVCaptureSystemExposureBiasSliderCallback

	[UnmanagedFunctionPointerAttribute (CallingConvention.Cdecl)]
	[UserDelegateType (typeof (global::AVFoundation.AVCaptureSystemZoomSliderCallback))]
	unsafe internal delegate void DAVCaptureSystemZoomSliderCallback (global::System.IntPtr block_ptr, global::System.Runtime.InteropServices.NFloat videoZoomFactor);

	/// <summary>This class bridges native block invocations that call into C#</summary>
	static internal class SDAVCaptureSystemZoomSliderCallback
	{
		[Preserve (Conditional = true)]
		[UnmanagedCallersOnly]
		[UserDelegateType (typeof (global::AVFoundation.AVCaptureSystemZoomSliderCallback))]
		internal static unsafe void Invoke (global::System.IntPtr block_ptr, global::System.Runtime.InteropServices.NFloat videoZoomFactor)
		{
			var del = global::ObjCRuntime.BlockLiteral.GetTarget<global::AVFoundation.AVCaptureSystemZoomSliderCallback> (block_ptr);
			if (del is not null)
			{
				del (videoZoomFactor);
			}
		}

		internal static unsafe global::ObjCRuntime.BlockLiteral CreateNullableBlock (global::AVFoundation.AVCaptureSystemZoomSliderCallback? callback)
		{
			if (callback is null)
				return default (global::ObjCRuntime.BlockLiteral);
			return CreateBlock (callback);
		}

		[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
		internal static unsafe global::ObjCRuntime.BlockLiteral CreateBlock (global::AVFoundation.AVCaptureSystemZoomSliderCallback callback)
		{
			delegate* unmanaged<global::System.IntPtr, global::System.Runtime.InteropServices.NFloat, void> trampoline = &Invoke;
			return new global::ObjCRuntime.BlockLiteral (trampoline, callback, typeof (SDAVCaptureSystemZoomSliderCallback), nameof (Invoke));
		}
	}
	// TODO: generate trampoline for AVFoundation.AVCaptureSystemZoomSliderCallback

	[UnmanagedFunctionPointerAttribute (CallingConvention.Cdecl)]
	[UserDelegateType (typeof (global::AVFoundation.AVCompletion))]
	unsafe internal delegate void DAVCompletion (global::System.IntPtr block_ptr, byte finished);

	/// <summary>This class bridges native block invocations that call into C#</summary>
	static internal class SDAVCompletion
	{
		[Preserve (Conditional = true)]
		[UnmanagedCallersOnly]
		[UserDelegateType (typeof (global::AVFoundation.AVCompletion))]
		internal static unsafe void Invoke (global::System.IntPtr block_ptr, byte finished)
		{
			var del = global::ObjCRuntime.BlockLiteral.GetTarget<global::AVFoundation.AVCompletion> (block_ptr);
			if (del is not null)
			{
				del (finished != 0);
			}
		}

		internal static unsafe global::ObjCRuntime.BlockLiteral CreateNullableBlock (global::AVFoundation.AVCompletion? callback)
		{
			if (callback is null)
				return default (global::ObjCRuntime.BlockLiteral);
			return CreateBlock (callback);
		}

		[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
		internal static unsafe global::ObjCRuntime.BlockLiteral CreateBlock (global::AVFoundation.AVCompletion callback)
		{
			delegate* unmanaged<global::System.IntPtr, byte, void> trampoline = &Invoke;
			return new global::ObjCRuntime.BlockLiteral (trampoline, callback, typeof (SDAVCompletion), nameof (Invoke));
		}
	}
	// TODO: generate trampoline for AVFoundation.AVCompletion

	[UnmanagedFunctionPointerAttribute (CallingConvention.Cdecl)]
	[UserDelegateType (typeof (global::AVFoundation.AVExternalStorageDeviceRequestAccessCallback))]
	unsafe internal delegate void DAVExternalStorageDeviceRequestAccessCallback (global::System.IntPtr block_ptr, byte granted);

	/// <summary>This class bridges native block invocations that call into C#</summary>
	static internal class SDAVExternalStorageDeviceRequestAccessCallback
	{
		[Preserve (Conditional = true)]
		[UnmanagedCallersOnly]
		[UserDelegateType (typeof (global::AVFoundation.AVExternalStorageDeviceRequestAccessCallback))]
		internal static unsafe void Invoke (global::System.IntPtr block_ptr, byte granted)
		{
			var del = global::ObjCRuntime.BlockLiteral.GetTarget<global::AVFoundation.AVExternalStorageDeviceRequestAccessCallback> (block_ptr);
			if (del is not null)
			{
				del (granted != 0);
			}
		}

		internal static unsafe global::ObjCRuntime.BlockLiteral CreateNullableBlock (global::AVFoundation.AVExternalStorageDeviceRequestAccessCallback? callback)
		{
			if (callback is null)
				return default (global::ObjCRuntime.BlockLiteral);
			return CreateBlock (callback);
		}

		[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
		internal static unsafe global::ObjCRuntime.BlockLiteral CreateBlock (global::AVFoundation.AVExternalStorageDeviceRequestAccessCallback callback)
		{
			delegate* unmanaged<global::System.IntPtr, byte, void> trampoline = &Invoke;
			return new global::ObjCRuntime.BlockLiteral (trampoline, callback, typeof (SDAVExternalStorageDeviceRequestAccessCallback), nameof (Invoke));
		}
	}
	// TODO: generate trampoline for AVFoundation.AVExternalStorageDeviceRequestAccessCallback

	[UnmanagedFunctionPointerAttribute (CallingConvention.Cdecl)]
	[UserDelegateType (typeof (global::AVFoundation.AVMusicEventEnumerationBlock))]
	unsafe internal delegate void DAVMusicEventEnumerationBlock (global::System.IntPtr block_ptr, global::ObjCRuntime.NativeHandle event, double* timeStamp, byte* removeEvent);

	/// <summary>This class bridges native block invocations that call into C#</summary>
	static internal class SDAVMusicEventEnumerationBlock
	{
		[Preserve (Conditional = true)]
		[UnmanagedCallersOnly]
		[UserDelegateType (typeof (global::AVFoundation.AVMusicEventEnumerationBlock))]
		internal static unsafe void Invoke (global::System.IntPtr block_ptr, global::ObjCRuntime.NativeHandle event, double* timeStamp, byte* removeEvent)
		{
			var del = global::ObjCRuntime.BlockLiteral.GetTarget<global::AVFoundation.AVMusicEventEnumerationBlock> (block_ptr);
			if (del is not null)
			{
				bool __xamarin_bool__2 = *removeEvent != 0;
				del (global::ObjCRuntime.Runtime.GetNSObject<global::AVFoundation.AVMusicEvent> (event)!, out global::System.Runtime.CompilerServices.Unsafe.AsRef<double> (timeStamp), out __xamarin_bool__2);
				*removeEvent = __xamarin_bool__2 ? (byte)1 : (byte)0;
			}
		}

		internal static unsafe global::ObjCRuntime.BlockLiteral CreateNullableBlock (global::AVFoundation.AVMusicEventEnumerationBlock? callback)
		{
			if (callback is null)
				return default (global::ObjCRuntime.BlockLiteral);
			return CreateBlock (callback);
		}

		[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
		internal static unsafe global::ObjCRuntime.BlockLiteral CreateBlock (global::AVFoundation.AVMusicEventEnumerationBlock callback)
		{
			delegate* unmanaged<global::System.IntPtr, global::ObjCRuntime.NativeHandle, double*, byte*, void> trampoline = &Invoke;
			return new global::ObjCRuntime.BlockLiteral (trampoline, callback, typeof (SDAVMusicEventEnumerationBlock), nameof (Invoke));
		}
	}
	// TODO: generate trampoline for AVFoundation.AVMusicEventEnumerationBlock

	[UnmanagedFunctionPointerAttribute (CallingConvention.Cdecl)]
	[UserDelegateType (typeof (global::AVFoundation.AVMutableCompositionInsertHandler))]
	unsafe internal delegate void DAVMutableCompositionInsertHandler (global::System.IntPtr block_ptr, global::ObjCRuntime.NativeHandle error);

	/// <summary>This class bridges native block invocations that call into C#</summary>
	static internal class SDAVMutableCompositionInsertHandler
	{
		[Preserve (Conditional = true)]
		[UnmanagedCallersOnly]
		[UserDelegateType (typeof (global::AVFoundation.AVMutableCompositionInsertHandler))]
		internal static unsafe void Invoke (global::System.IntPtr block_ptr, global::ObjCRuntime.NativeHandle error)
		{
			var del = global::ObjCRuntime.BlockLiteral.GetTarget<global::AVFoundation.AVMutableCompositionInsertHandler> (block_ptr);
			if (del is not null)
			{
				del (global::ObjCRuntime.Runtime.GetNSObject<global::Foundation.NSError?> (error)!);
			}
		}

		internal static unsafe global::ObjCRuntime.BlockLiteral CreateNullableBlock (global::AVFoundation.AVMutableCompositionInsertHandler? callback)
		{
			if (callback is null)
				return default (global::ObjCRuntime.BlockLiteral);
			return CreateBlock (callback);
		}

		[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
		internal static unsafe global::ObjCRuntime.BlockLiteral CreateBlock (global::AVFoundation.AVMutableCompositionInsertHandler callback)
		{
			delegate* unmanaged<global::System.IntPtr, global::ObjCRuntime.NativeHandle, void> trampoline = &Invoke;
			return new global::ObjCRuntime.BlockLiteral (trampoline, callback, typeof (SDAVMutableCompositionInsertHandler), nameof (Invoke));
		}
	}
	// TODO: generate trampoline for AVFoundation.AVMutableCompositionInsertHandler

	[UnmanagedFunctionPointerAttribute (CallingConvention.Cdecl)]
	[UserDelegateType (typeof (global::AVFoundation.AVMutableVideoCompositionCreateApplier))]
	unsafe internal delegate void DAVMutableVideoCompositionCreateApplier (global::System.IntPtr block_ptr, global::ObjCRuntime.NativeHandle request);

	/// <summary>This class bridges native block invocations that call into C#</summary>
	static internal class SDAVMutableVideoCompositionCreateApplier
	{
		[Preserve (Conditional = true)]
		[UnmanagedCallersOnly]
		[UserDelegateType (typeof (global::AVFoundation.AVMutableVideoCompositionCreateApplier))]
		internal static unsafe void Invoke (global::System.IntPtr block_ptr, global::ObjCRuntime.NativeHandle request)
		{
			var del = global::ObjCRuntime.BlockLiteral.GetTarget<global::AVFoundation.AVMutableVideoCompositionCreateApplier> (block_ptr);
			if (del is not null)
			{
				del (global::ObjCRuntime.Runtime.GetNSObject<global::AVFoundation.AVAsynchronousCIImageFilteringRequest> (request)!);
			}
		}

		internal static unsafe global::ObjCRuntime.BlockLiteral CreateNullableBlock (global::AVFoundation.AVMutableVideoCompositionCreateApplier? callback)
		{
			if (callback is null)
				return default (global::ObjCRuntime.BlockLiteral);
			return CreateBlock (callback);
		}

		[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
		internal static unsafe global::ObjCRuntime.BlockLiteral CreateBlock (global::AVFoundation.AVMutableVideoCompositionCreateApplier callback)
		{
			delegate* unmanaged<global::System.IntPtr, global::ObjCRuntime.NativeHandle, void> trampoline = &Invoke;
			return new global::ObjCRuntime.BlockLiteral (trampoline, callback, typeof (SDAVMutableVideoCompositionCreateApplier), nameof (Invoke));
		}
	}
	// TODO: generate trampoline for AVFoundation.AVMutableVideoCompositionCreateApplier

	[UnmanagedFunctionPointerAttribute (CallingConvention.Cdecl)]
	[UserDelegateType (typeof (global::AVFoundation.AVMutableVideoCompositionCreateCallback))]
	unsafe internal delegate void DAVMutableVideoCompositionCreateCallback (global::System.IntPtr block_ptr, global::ObjCRuntime.NativeHandle videoComposition, global::ObjCRuntime.NativeHandle error);

	/// <summary>This class bridges native block invocations that call into C#</summary>
	static internal class SDAVMutableVideoCompositionCreateCallback
	{
		[Preserve (Conditional = true)]
		[UnmanagedCallersOnly]
		[UserDelegateType (typeof (global::AVFoundation.AVMutableVideoCompositionCreateCallback))]
		internal static unsafe void Invoke (global::System.IntPtr block_ptr, global::ObjCRuntime.NativeHandle videoComposition, global::ObjCRuntime.NativeHandle error)
		{
			var del = global::ObjCRuntime.BlockLiteral.GetTarget<global::AVFoundation.AVMutableVideoCompositionCreateCallback> (block_ptr);
			if (del is not null)
			{
				del (global::ObjCRuntime.Runtime.GetNSObject<global::AVFoundation.AVMutableVideoComposition?> (videoComposition)!, global::ObjCRuntime.Runtime.GetNSObject<global::Foundation.NSError?> (error)!);
			}
		}

		internal static unsafe global::ObjCRuntime.BlockLiteral CreateNullableBlock (global::AVFoundation.AVMutableVideoCompositionCreateCallback? callback)
		{
			if (callback is null)
				return default (global::ObjCRuntime.BlockLiteral);
			return CreateBlock (callback);
		}

		[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
		internal static unsafe global::ObjCRuntime.BlockLiteral CreateBlock (global::AVFoundation.AVMutableVideoCompositionCreateCallback callback)
		{
			delegate* unmanaged<global::System.IntPtr, global::ObjCRuntime.NativeHandle, global::ObjCRuntime.NativeHandle, void> trampoline = &Invoke;
			return new global::ObjCRuntime.BlockLiteral (trampoline, callback, typeof (SDAVMutableVideoCompositionCreateCallback), nameof (Invoke));
		}
	}
	// TODO: generate trampoline for AVFoundation.AVMutableVideoCompositionCreateCallback

	[UnmanagedFunctionPointerAttribute (CallingConvention.Cdecl)]
	[UserDelegateType (typeof (global::AVFoundation.AVPermissionGranted))]
	unsafe internal delegate void DAVPermissionGranted (global::System.IntPtr block_ptr, byte granted);

	/// <summary>This class bridges native block invocations that call into C#</summary>
	static internal class SDAVPermissionGranted
	{
		[Preserve (Conditional = true)]
		[UnmanagedCallersOnly]
		[UserDelegateType (typeof (global::AVFoundation.AVPermissionGranted))]
		internal static unsafe void Invoke (global::System.IntPtr block_ptr, byte granted)
		{
			var del = global::ObjCRuntime.BlockLiteral.GetTarget<global::AVFoundation.AVPermissionGranted> (block_ptr);
			if (del is not null)
			{
				del (granted != 0);
			}
		}

		internal static unsafe global::ObjCRuntime.BlockLiteral CreateNullableBlock (global::AVFoundation.AVPermissionGranted? callback)
		{
			if (callback is null)
				return default (global::ObjCRuntime.BlockLiteral);
			return CreateBlock (callback);
		}

		[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
		internal static unsafe global::ObjCRuntime.BlockLiteral CreateBlock (global::AVFoundation.AVPermissionGranted callback)
		{
			delegate* unmanaged<global::System.IntPtr, byte, void> trampoline = &Invoke;
			return new global::ObjCRuntime.BlockLiteral (trampoline, callback, typeof (SDAVPermissionGranted), nameof (Invoke));
		}
	}
	// TODO: generate trampoline for AVFoundation.AVPermissionGranted

	[UnmanagedFunctionPointerAttribute (CallingConvention.Cdecl)]
	[UserDelegateType (typeof (global::AVFoundation.AVPlayerItemIntegratedTimelineAddBoundaryTimeObserverCallback))]
	unsafe internal delegate void DAVPlayerItemIntegratedTimelineAddBoundaryTimeObserverCallback (global::System.IntPtr block_ptr, byte success);

	/// <summary>This class bridges native block invocations that call into C#</summary>
	static internal class SDAVPlayerItemIntegratedTimelineAddBoundaryTimeObserverCallback
	{
		[Preserve (Conditional = true)]
		[UnmanagedCallersOnly]
		[UserDelegateType (typeof (global::AVFoundation.AVPlayerItemIntegratedTimelineAddBoundaryTimeObserverCallback))]
		internal static unsafe void Invoke (global::System.IntPtr block_ptr, byte success)
		{
			var del = global::ObjCRuntime.BlockLiteral.GetTarget<global::AVFoundation.AVPlayerItemIntegratedTimelineAddBoundaryTimeObserverCallback> (block_ptr);
			if (del is not null)
			{
				del (success != 0);
			}
		}

		internal static unsafe global::ObjCRuntime.BlockLiteral CreateNullableBlock (global::AVFoundation.AVPlayerItemIntegratedTimelineAddBoundaryTimeObserverCallback? callback)
		{
			if (callback is null)
				return default (global::ObjCRuntime.BlockLiteral);
			return CreateBlock (callback);
		}

		[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
		internal static unsafe global::ObjCRuntime.BlockLiteral CreateBlock (global::AVFoundation.AVPlayerItemIntegratedTimelineAddBoundaryTimeObserverCallback callback)
		{
			delegate* unmanaged<global::System.IntPtr, byte, void> trampoline = &Invoke;
			return new global::ObjCRuntime.BlockLiteral (trampoline, callback, typeof (SDAVPlayerItemIntegratedTimelineAddBoundaryTimeObserverCallback), nameof (Invoke));
		}
	}
	// TODO: generate trampoline for AVFoundation.AVPlayerItemIntegratedTimelineAddBoundaryTimeObserverCallback

	[UnmanagedFunctionPointerAttribute (CallingConvention.Cdecl)]
	[UserDelegateType (typeof (global::AVFoundation.AVPlayerItemIntegratedTimelineAddPeriodicTimeObserverCallback))]
	unsafe internal delegate void DAVPlayerItemIntegratedTimelineAddPeriodicTimeObserverCallback (global::System.IntPtr block_ptr, global::CoreMedia.CMTime time);

	/// <summary>This class bridges native block invocations that call into C#</summary>
	static internal class SDAVPlayerItemIntegratedTimelineAddPeriodicTimeObserverCallback
	{
		[Preserve (Conditional = true)]
		[UnmanagedCallersOnly]
		[UserDelegateType (typeof (global::AVFoundation.AVPlayerItemIntegratedTimelineAddPeriodicTimeObserverCallback))]
		internal static unsafe void Invoke (global::System.IntPtr block_ptr, global::CoreMedia.CMTime time)
		{
			var del = global::ObjCRuntime.BlockLiteral.GetTarget<global::AVFoundation.AVPlayerItemIntegratedTimelineAddPeriodicTimeObserverCallback> (block_ptr);
			if (del is not null)
			{
				del (time);
			}
		}

		internal static unsafe global::ObjCRuntime.BlockLiteral CreateNullableBlock (global::AVFoundation.AVPlayerItemIntegratedTimelineAddPeriodicTimeObserverCallback? callback)
		{
			if (callback is null)
				return default (global::ObjCRuntime.BlockLiteral);
			return CreateBlock (callback);
		}

		[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
		internal static unsafe global::ObjCRuntime.BlockLiteral CreateBlock (global::AVFoundation.AVPlayerItemIntegratedTimelineAddPeriodicTimeObserverCallback callback)
		{
			delegate* unmanaged<global::System.IntPtr, global::CoreMedia.CMTime, void> trampoline = &Invoke;
			return new global::ObjCRuntime.BlockLiteral (trampoline, callback, typeof (SDAVPlayerItemIntegratedTimelineAddPeriodicTimeObserverCallback), nameof (Invoke));
		}
	}
	// TODO: generate trampoline for AVFoundation.AVPlayerItemIntegratedTimelineAddPeriodicTimeObserverCallback

	[UnmanagedFunctionPointerAttribute (CallingConvention.Cdecl)]
	[UserDelegateType (typeof (global::AVFoundation.AVPlayerItemIntegratedTimelineSeekCallback))]
	unsafe internal delegate void DAVPlayerItemIntegratedTimelineSeekCallback (global::System.IntPtr block_ptr, byte success);

	/// <summary>This class bridges native block invocations that call into C#</summary>
	static internal class SDAVPlayerItemIntegratedTimelineSeekCallback
	{
		[Preserve (Conditional = true)]
		[UnmanagedCallersOnly]
		[UserDelegateType (typeof (global::AVFoundation.AVPlayerItemIntegratedTimelineSeekCallback))]
		internal static unsafe void Invoke (global::System.IntPtr block_ptr, byte success)
		{
			var del = global::ObjCRuntime.BlockLiteral.GetTarget<global::AVFoundation.AVPlayerItemIntegratedTimelineSeekCallback> (block_ptr);
			if (del is not null)
			{
				del (success != 0);
			}
		}

		internal static unsafe global::ObjCRuntime.BlockLiteral CreateNullableBlock (global::AVFoundation.AVPlayerItemIntegratedTimelineSeekCallback? callback)
		{
			if (callback is null)
				return default (global::ObjCRuntime.BlockLiteral);
			return CreateBlock (callback);
		}

		[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
		internal static unsafe global::ObjCRuntime.BlockLiteral CreateBlock (global::AVFoundation.AVPlayerItemIntegratedTimelineSeekCallback callback)
		{
			delegate* unmanaged<global::System.IntPtr, byte, void> trampoline = &Invoke;
			return new global::ObjCRuntime.BlockLiteral (trampoline, callback, typeof (SDAVPlayerItemIntegratedTimelineSeekCallback), nameof (Invoke));
		}
	}
	// TODO: generate trampoline for AVFoundation.AVPlayerItemIntegratedTimelineSeekCallback

	[UnmanagedFunctionPointerAttribute (CallingConvention.Cdecl)]
	[UserDelegateType (typeof (global::AVFoundation.AVRequestAccessStatus))]
	unsafe internal delegate void DAVRequestAccessStatus (global::System.IntPtr block_ptr, byte accessGranted);

	/// <summary>This class bridges native block invocations that call into C#</summary>
	static internal class SDAVRequestAccessStatus
	{
		[Preserve (Conditional = true)]
		[UnmanagedCallersOnly]
		[UserDelegateType (typeof (global::AVFoundation.AVRequestAccessStatus))]
		internal static unsafe void Invoke (global::System.IntPtr block_ptr, byte accessGranted)
		{
			var del = global::ObjCRuntime.BlockLiteral.GetTarget<global::AVFoundation.AVRequestAccessStatus> (block_ptr);
			if (del is not null)
			{
				del (accessGranted != 0);
			}
		}

		internal static unsafe global::ObjCRuntime.BlockLiteral CreateNullableBlock (global::AVFoundation.AVRequestAccessStatus? callback)
		{
			if (callback is null)
				return default (global::ObjCRuntime.BlockLiteral);
			return CreateBlock (callback);
		}

		[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
		internal static unsafe global::ObjCRuntime.BlockLiteral CreateBlock (global::AVFoundation.AVRequestAccessStatus callback)
		{
			delegate* unmanaged<global::System.IntPtr, byte, void> trampoline = &Invoke;
			return new global::ObjCRuntime.BlockLiteral (trampoline, callback, typeof (SDAVRequestAccessStatus), nameof (Invoke));
		}
	}
	// TODO: generate trampoline for AVFoundation.AVRequestAccessStatus

	[UnmanagedFunctionPointerAttribute (CallingConvention.Cdecl)]
	[UserDelegateType (typeof (global::AVFoundation.AVSampleBufferGeneratorBatchMakeReadyCallback))]
	unsafe internal delegate void DAVSampleBufferGeneratorBatchMakeReadyCallback (global::System.IntPtr block_ptr, global::ObjCRuntime.NativeHandle error);

	/// <summary>This class bridges native block invocations that call into C#</summary>
	static internal class SDAVSampleBufferGeneratorBatchMakeReadyCallback
	{
		[Preserve (Conditional = true)]
		[UnmanagedCallersOnly]
		[UserDelegateType (typeof (global::AVFoundation.AVSampleBufferGeneratorBatchMakeReadyCallback))]
		internal static unsafe void Invoke (global::System.IntPtr block_ptr, global::ObjCRuntime.NativeHandle error)
		{
			var del = global::ObjCRuntime.BlockLiteral.GetTarget<global::AVFoundation.AVSampleBufferGeneratorBatchMakeReadyCallback> (block_ptr);
			if (del is not null)
			{
				del (global::ObjCRuntime.Runtime.GetNSObject<global::Foundation.NSError?> (error)!);
			}
		}

		internal static unsafe global::ObjCRuntime.BlockLiteral CreateNullableBlock (global::AVFoundation.AVSampleBufferGeneratorBatchMakeReadyCallback? callback)
		{
			if (callback is null)
				return default (global::ObjCRuntime.BlockLiteral);
			return CreateBlock (callback);
		}

		[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
		internal static unsafe global::ObjCRuntime.BlockLiteral CreateBlock (global::AVFoundation.AVSampleBufferGeneratorBatchMakeReadyCallback callback)
		{
			delegate* unmanaged<global::System.IntPtr, global::ObjCRuntime.NativeHandle, void> trampoline = &Invoke;
			return new global::ObjCRuntime.BlockLiteral (trampoline, callback, typeof (SDAVSampleBufferGeneratorBatchMakeReadyCallback), nameof (Invoke));
		}
	}
	// TODO: generate trampoline for AVFoundation.AVSampleBufferGeneratorBatchMakeReadyCallback

	[UnmanagedFunctionPointerAttribute (CallingConvention.Cdecl)]
	[UserDelegateType (typeof (global::AVFoundation.AVSampleBufferVideoRendererLoadVideoPerformanceMetricsCallback))]
	unsafe internal delegate void DAVSampleBufferVideoRendererLoadVideoPerformanceMetricsCallback (global::System.IntPtr block_ptr, global::ObjCRuntime.NativeHandle videoPerformanceMetrics);

	/// <summary>This class bridges native block invocations that call into C#</summary>
	static internal class SDAVSampleBufferVideoRendererLoadVideoPerformanceMetricsCallback
	{
		[Preserve (Conditional = true)]
		[UnmanagedCallersOnly]
		[UserDelegateType (typeof (global::AVFoundation.AVSampleBufferVideoRendererLoadVideoPerformanceMetricsCallback))]
		internal static unsafe void Invoke (global::System.IntPtr block_ptr, global::ObjCRuntime.NativeHandle videoPerformanceMetrics)
		{
			var del = global::ObjCRuntime.BlockLiteral.GetTarget<global::AVFoundation.AVSampleBufferVideoRendererLoadVideoPerformanceMetricsCallback> (block_ptr);
			if (del is not null)
			{
				del (global::ObjCRuntime.Runtime.GetNSObject<global::AVFoundation.AVVideoPerformanceMetrics?> (videoPerformanceMetrics)!);
			}
		}

		internal static unsafe global::ObjCRuntime.BlockLiteral CreateNullableBlock (global::AVFoundation.AVSampleBufferVideoRendererLoadVideoPerformanceMetricsCallback? callback)
		{
			if (callback is null)
				return default (global::ObjCRuntime.BlockLiteral);
			return CreateBlock (callback);
		}

		[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
		internal static unsafe global::ObjCRuntime.BlockLiteral CreateBlock (global::AVFoundation.AVSampleBufferVideoRendererLoadVideoPerformanceMetricsCallback callback)
		{
			delegate* unmanaged<global::System.IntPtr, global::ObjCRuntime.NativeHandle, void> trampoline = &Invoke;
			return new global::ObjCRuntime.BlockLiteral (trampoline, callback, typeof (SDAVSampleBufferVideoRendererLoadVideoPerformanceMetricsCallback), nameof (Invoke));
		}
	}
	// TODO: generate trampoline for AVFoundation.AVSampleBufferVideoRendererLoadVideoPerformanceMetricsCallback

	[UnmanagedFunctionPointerAttribute (CallingConvention.Cdecl)]
	[UserDelegateType (typeof (global::AVFoundation.AVSpeechSynthesisProviderOutputBlock))]
	unsafe internal delegate void DAVSpeechSynthesisProviderOutputBlock (global::System.IntPtr block_ptr, global::ObjCRuntime.NativeHandle markers, global::ObjCRuntime.NativeHandle request);

	/// <summary>This class bridges native block invocations that call into C#</summary>
	static internal class SDAVSpeechSynthesisProviderOutputBlock
	{
		[Preserve (Conditional = true)]
		[UnmanagedCallersOnly]
		[UserDelegateType (typeof (global::AVFoundation.AVSpeechSynthesisProviderOutputBlock))]
		internal static unsafe void Invoke (global::System.IntPtr block_ptr, global::ObjCRuntime.NativeHandle markers, global::ObjCRuntime.NativeHandle request)
		{
			var del = global::ObjCRuntime.BlockLiteral.GetTarget<global::AVFoundation.AVSpeechSynthesisProviderOutputBlock> (block_ptr);
			if (del is not null)
			{
				del (global::CoreFoundation.CFArray.ArrayFromHandle<global::AVFoundation.AVSpeechSynthesisMarker> (markers)!, global::ObjCRuntime.Runtime.GetNSObject<global::AVFoundation.AVSpeechSynthesisProviderRequest> (request)!);
			}
		}

		internal static unsafe global::ObjCRuntime.BlockLiteral CreateNullableBlock (global::AVFoundation.AVSpeechSynthesisProviderOutputBlock? callback)
		{
			if (callback is null)
				return default (global::ObjCRuntime.BlockLiteral);
			return CreateBlock (callback);
		}

		[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
		internal static unsafe global::ObjCRuntime.BlockLiteral CreateBlock (global::AVFoundation.AVSpeechSynthesisProviderOutputBlock callback)
		{
			delegate* unmanaged<global::System.IntPtr, global::ObjCRuntime.NativeHandle, global::ObjCRuntime.NativeHandle, void> trampoline = &Invoke;
			return new global::ObjCRuntime.BlockLiteral (trampoline, callback, typeof (SDAVSpeechSynthesisProviderOutputBlock), nameof (Invoke));
		}
	}
	// TODO: generate trampoline for AVFoundation.AVSpeechSynthesisProviderOutputBlock

	[UnmanagedFunctionPointerAttribute (CallingConvention.Cdecl)]
	[UserDelegateType (typeof (global::AVFoundation.AVSpeechSynthesizerBufferCallback))]
	unsafe internal delegate void DAVSpeechSynthesizerBufferCallback (global::System.IntPtr block_ptr, global::ObjCRuntime.NativeHandle buffer);

	/// <summary>This class bridges native block invocations that call into C#</summary>
	static internal class SDAVSpeechSynthesizerBufferCallback
	{
		[Preserve (Conditional = true)]
		[UnmanagedCallersOnly]
		[UserDelegateType (typeof (global::AVFoundation.AVSpeechSynthesizerBufferCallback))]
		internal static unsafe void Invoke (global::System.IntPtr block_ptr, global::ObjCRuntime.NativeHandle buffer)
		{
			var del = global::ObjCRuntime.BlockLiteral.GetTarget<global::AVFoundation.AVSpeechSynthesizerBufferCallback> (block_ptr);
			if (del is not null)
			{
				del (global::ObjCRuntime.Runtime.GetNSObject<global::AVFoundation.AVAudioBuffer> (buffer)!);
			}
		}

		internal static unsafe global::ObjCRuntime.BlockLiteral CreateNullableBlock (global::AVFoundation.AVSpeechSynthesizerBufferCallback? callback)
		{
			if (callback is null)
				return default (global::ObjCRuntime.BlockLiteral);
			return CreateBlock (callback);
		}

		[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
		internal static unsafe global::ObjCRuntime.BlockLiteral CreateBlock (global::AVFoundation.AVSpeechSynthesizerBufferCallback callback)
		{
			delegate* unmanaged<global::System.IntPtr, global::ObjCRuntime.NativeHandle, void> trampoline = &Invoke;
			return new global::ObjCRuntime.BlockLiteral (trampoline, callback, typeof (SDAVSpeechSynthesizerBufferCallback), nameof (Invoke));
		}
	}
	// TODO: generate trampoline for AVFoundation.AVSpeechSynthesizerBufferCallback

	[UnmanagedFunctionPointerAttribute (CallingConvention.Cdecl)]
	[UserDelegateType (typeof (global::AVFoundation.AVSpeechSynthesizerMarkerCallback))]
	unsafe internal delegate void DAVSpeechSynthesizerMarkerCallback (global::System.IntPtr block_ptr, global::ObjCRuntime.NativeHandle markers);

	/// <summary>This class bridges native block invocations that call into C#</summary>
	static internal class SDAVSpeechSynthesizerMarkerCallback
	{
		[Preserve (Conditional = true)]
		[UnmanagedCallersOnly]
		[UserDelegateType (typeof (global::AVFoundation.AVSpeechSynthesizerMarkerCallback))]
		internal static unsafe void Invoke (global::System.IntPtr block_ptr, global::ObjCRuntime.NativeHandle markers)
		{
			var del = global::ObjCRuntime.BlockLiteral.GetTarget<global::AVFoundation.AVSpeechSynthesizerMarkerCallback> (block_ptr);
			if (del is not null)
			{
				del (global::CoreFoundation.CFArray.ArrayFromHandle<global::AVFoundation.AVSpeechSynthesisMarker> (markers)!);
			}
		}

		internal static unsafe global::ObjCRuntime.BlockLiteral CreateNullableBlock (global::AVFoundation.AVSpeechSynthesizerMarkerCallback? callback)
		{
			if (callback is null)
				return default (global::ObjCRuntime.BlockLiteral);
			return CreateBlock (callback);
		}

		[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
		internal static unsafe global::ObjCRuntime.BlockLiteral CreateBlock (global::AVFoundation.AVSpeechSynthesizerMarkerCallback callback)
		{
			delegate* unmanaged<global::System.IntPtr, global::ObjCRuntime.NativeHandle, void> trampoline = &Invoke;
			return new global::ObjCRuntime.BlockLiteral (trampoline, callback, typeof (SDAVSpeechSynthesizerMarkerCallback), nameof (Invoke));
		}
	}
	// TODO: generate trampoline for AVFoundation.AVSpeechSynthesizerMarkerCallback

	[UnmanagedFunctionPointerAttribute (CallingConvention.Cdecl)]
	[UserDelegateType (typeof (global::AVFoundation.AVSpeechSynthesizerRequestPersonalVoiceAuthorizationCallback))]
	unsafe internal delegate void DAVSpeechSynthesizerRequestPersonalVoiceAuthorizationCallback (global::System.IntPtr block_ptr, global::System.UIntPtr status);

	/// <summary>This class bridges native block invocations that call into C#</summary>
	static internal class SDAVSpeechSynthesizerRequestPersonalVoiceAuthorizationCallback
	{
		[Preserve (Conditional = true)]
		[UnmanagedCallersOnly]
		[UserDelegateType (typeof (global::AVFoundation.AVSpeechSynthesizerRequestPersonalVoiceAuthorizationCallback))]
		internal static unsafe void Invoke (global::System.IntPtr block_ptr, global::System.UIntPtr status)
		{
			var del = global::ObjCRuntime.BlockLiteral.GetTarget<global::AVFoundation.AVSpeechSynthesizerRequestPersonalVoiceAuthorizationCallback> (block_ptr);
			if (del is not null)
			{
				del ((global::AVFoundation.AVSpeechSynthesisPersonalVoiceAuthorizationStatus) (ulong) status);
			}
		}

		internal static unsafe global::ObjCRuntime.BlockLiteral CreateNullableBlock (global::AVFoundation.AVSpeechSynthesizerRequestPersonalVoiceAuthorizationCallback? callback)
		{
			if (callback is null)
				return default (global::ObjCRuntime.BlockLiteral);
			return CreateBlock (callback);
		}

		[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
		internal static unsafe global::ObjCRuntime.BlockLiteral CreateBlock (global::AVFoundation.AVSpeechSynthesizerRequestPersonalVoiceAuthorizationCallback callback)
		{
			delegate* unmanaged<global::System.IntPtr, global::System.UIntPtr, void> trampoline = &Invoke;
			return new global::ObjCRuntime.BlockLiteral (trampoline, callback, typeof (SDAVSpeechSynthesizerRequestPersonalVoiceAuthorizationCallback), nameof (Invoke));
		}
	}
	// TODO: generate trampoline for AVFoundation.AVSpeechSynthesizerRequestPersonalVoiceAuthorizationCallback

	[UnmanagedFunctionPointerAttribute (CallingConvention.Cdecl)]
	[UserDelegateType (typeof (global::AVFoundation.AVVideoCompositionCreateApplier))]
	unsafe internal delegate void DAVVideoCompositionCreateApplier (global::System.IntPtr block_ptr, global::ObjCRuntime.NativeHandle applier);

	/// <summary>This class bridges native block invocations that call into C#</summary>
	static internal class SDAVVideoCompositionCreateApplier
	{
		[Preserve (Conditional = true)]
		[UnmanagedCallersOnly]
		[UserDelegateType (typeof (global::AVFoundation.AVVideoCompositionCreateApplier))]
		internal static unsafe void Invoke (global::System.IntPtr block_ptr, global::ObjCRuntime.NativeHandle applier)
		{
			var del = global::ObjCRuntime.BlockLiteral.GetTarget<global::AVFoundation.AVVideoCompositionCreateApplier> (block_ptr);
			if (del is not null)
			{
				del (global::ObjCRuntime.Runtime.GetNSObject<global::AVFoundation.AVAsynchronousCIImageFilteringRequest> (applier)!);
			}
		}

		internal static unsafe global::ObjCRuntime.BlockLiteral CreateNullableBlock (global::AVFoundation.AVVideoCompositionCreateApplier? callback)
		{
			if (callback is null)
				return default (global::ObjCRuntime.BlockLiteral);
			return CreateBlock (callback);
		}

		[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
		internal static unsafe global::ObjCRuntime.BlockLiteral CreateBlock (global::AVFoundation.AVVideoCompositionCreateApplier callback)
		{
			delegate* unmanaged<global::System.IntPtr, global::ObjCRuntime.NativeHandle, void> trampoline = &Invoke;
			return new global::ObjCRuntime.BlockLiteral (trampoline, callback, typeof (SDAVVideoCompositionCreateApplier), nameof (Invoke));
		}
	}
	// TODO: generate trampoline for AVFoundation.AVVideoCompositionCreateApplier

	[UnmanagedFunctionPointerAttribute (CallingConvention.Cdecl)]
	[UserDelegateType (typeof (global::AVFoundation.AVVideoCompositionCreateCallback))]
	unsafe internal delegate void DAVVideoCompositionCreateCallback (global::System.IntPtr block_ptr, global::ObjCRuntime.NativeHandle videoComposition, global::ObjCRuntime.NativeHandle error);

	/// <summary>This class bridges native block invocations that call into C#</summary>
	static internal class SDAVVideoCompositionCreateCallback
	{
		[Preserve (Conditional = true)]
		[UnmanagedCallersOnly]
		[UserDelegateType (typeof (global::AVFoundation.AVVideoCompositionCreateCallback))]
		internal static unsafe void Invoke (global::System.IntPtr block_ptr, global::ObjCRuntime.NativeHandle videoComposition, global::ObjCRuntime.NativeHandle error)
		{
			var del = global::ObjCRuntime.BlockLiteral.GetTarget<global::AVFoundation.AVVideoCompositionCreateCallback> (block_ptr);
			if (del is not null)
			{
				del (global::ObjCRuntime.Runtime.GetNSObject<global::AVFoundation.AVVideoComposition?> (videoComposition)!, global::ObjCRuntime.Runtime.GetNSObject<global::Foundation.NSError?> (error)!);
			}
		}

		internal static unsafe global::ObjCRuntime.BlockLiteral CreateNullableBlock (global::AVFoundation.AVVideoCompositionCreateCallback? callback)
		{
			if (callback is null)
				return default (global::ObjCRuntime.BlockLiteral);
			return CreateBlock (callback);
		}

		[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
		internal static unsafe global::ObjCRuntime.BlockLiteral CreateBlock (global::AVFoundation.AVVideoCompositionCreateCallback callback)
		{
			delegate* unmanaged<global::System.IntPtr, global::ObjCRuntime.NativeHandle, global::ObjCRuntime.NativeHandle, void> trampoline = &Invoke;
			return new global::ObjCRuntime.BlockLiteral (trampoline, callback, typeof (SDAVVideoCompositionCreateCallback), nameof (Invoke));
		}
	}
	// TODO: generate trampoline for AVFoundation.AVVideoCompositionCreateCallback

	[UnmanagedFunctionPointerAttribute (CallingConvention.Cdecl)]
	[UserDelegateType (typeof (global::AVFoundation.AVVideoCompositionDetermineValidityCallback))]
	unsafe internal delegate void DAVVideoCompositionDetermineValidityCallback (global::System.IntPtr block_ptr, byte isValid, global::ObjCRuntime.NativeHandle error);

	/// <summary>This class bridges native block invocations that call into C#</summary>
	static internal class SDAVVideoCompositionDetermineValidityCallback
	{
		[Preserve (Conditional = true)]
		[UnmanagedCallersOnly]
		[UserDelegateType (typeof (global::AVFoundation.AVVideoCompositionDetermineValidityCallback))]
		internal static unsafe void Invoke (global::System.IntPtr block_ptr, byte isValid, global::ObjCRuntime.NativeHandle error)
		{
			var del = global::ObjCRuntime.BlockLiteral.GetTarget<global::AVFoundation.AVVideoCompositionDetermineValidityCallback> (block_ptr);
			if (del is not null)
			{
				del (isValid != 0, global::ObjCRuntime.Runtime.GetNSObject<global::Foundation.NSError?> (error)!);
			}
		}

		internal static unsafe global::ObjCRuntime.BlockLiteral CreateNullableBlock (global::AVFoundation.AVVideoCompositionDetermineValidityCallback? callback)
		{
			if (callback is null)
				return default (global::ObjCRuntime.BlockLiteral);
			return CreateBlock (callback);
		}

		[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
		internal static unsafe global::ObjCRuntime.BlockLiteral CreateBlock (global::AVFoundation.AVVideoCompositionDetermineValidityCallback callback)
		{
			delegate* unmanaged<global::System.IntPtr, byte, global::ObjCRuntime.NativeHandle, void> trampoline = &Invoke;
			return new global::ObjCRuntime.BlockLiteral (trampoline, callback, typeof (SDAVVideoCompositionDetermineValidityCallback), nameof (Invoke));
		}
	}
	// TODO: generate trampoline for AVFoundation.AVVideoCompositionDetermineValidityCallback

}
