// <auto-generated />

#nullable enable

using AVFoundation;
using Foundation;
using ObjCBindings;
using ObjCRuntime;
using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Drawing;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;
using System.Threading.Tasks;

namespace TestNamespace;

[Register ("AVFoundationTrampolines", true)]
public class AVFoundationTrampolines
{
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selAvAssetImageGenerateAsynchronouslyForTimeCompletionHandlerX = "avAssetImageGenerateAsynchronouslyForTimeCompletionHandler";
	static readonly global::ObjCRuntime.NativeHandle selAvAssetImageGenerateAsynchronouslyForTimeCompletionHandlerXHandle = global::ObjCRuntime.Selector.GetHandle ("avAssetImageGenerateAsynchronouslyForTimeCompletionHandler");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selSetAvAssetImageGenerateAsynchronouslyForTimeCompletionHandler_X = "setAvAssetImageGenerateAsynchronouslyForTimeCompletionHandler:";
	static readonly global::ObjCRuntime.NativeHandle selSetAvAssetImageGenerateAsynchronouslyForTimeCompletionHandler_XHandle = global::ObjCRuntime.Selector.GetHandle ("setAvAssetImageGenerateAsynchronouslyForTimeCompletionHandler:");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selAvAssetImageGeneratorCompletionHandlerX = "avAssetImageGeneratorCompletionHandler";
	static readonly global::ObjCRuntime.NativeHandle selAvAssetImageGeneratorCompletionHandlerXHandle = global::ObjCRuntime.Selector.GetHandle ("avAssetImageGeneratorCompletionHandler");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selSetAvAssetImageGeneratorCompletionHandler_X = "setAvAssetImageGeneratorCompletionHandler:";
	static readonly global::ObjCRuntime.NativeHandle selSetAvAssetImageGeneratorCompletionHandler_XHandle = global::ObjCRuntime.Selector.GetHandle ("setAvAssetImageGeneratorCompletionHandler:");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selAvAssetImageGeneratorCompletionHandler2X = "avAssetImageGeneratorCompletionHandler2";
	static readonly global::ObjCRuntime.NativeHandle selAvAssetImageGeneratorCompletionHandler2XHandle = global::ObjCRuntime.Selector.GetHandle ("avAssetImageGeneratorCompletionHandler2");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selSetAvAssetImageGeneratorCompletionHandler2_X = "setAvAssetImageGeneratorCompletionHandler2:";
	static readonly global::ObjCRuntime.NativeHandle selSetAvAssetImageGeneratorCompletionHandler2_XHandle = global::ObjCRuntime.Selector.GetHandle ("setAvAssetImageGeneratorCompletionHandler2:");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selAvAssetPlaybackAssistantLoadPlaybackConfigurationOptionsHandlerX = "avAssetPlaybackAssistantLoadPlaybackConfigurationOptionsHandler";
	static readonly global::ObjCRuntime.NativeHandle selAvAssetPlaybackAssistantLoadPlaybackConfigurationOptionsHandlerXHandle = global::ObjCRuntime.Selector.GetHandle ("avAssetPlaybackAssistantLoadPlaybackConfigurationOptionsHandler");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selSetAvAssetPlaybackAssistantLoadPlaybackConfigurationOptionsHandler_X = "setAvAssetPlaybackAssistantLoadPlaybackConfigurationOptionsHandler:";
	static readonly global::ObjCRuntime.NativeHandle selSetAvAssetPlaybackAssistantLoadPlaybackConfigurationOptionsHandler_XHandle = global::ObjCRuntime.Selector.GetHandle ("setAvAssetPlaybackAssistantLoadPlaybackConfigurationOptionsHandler:");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selAvAudioConverterInputHandlerX = "avAudioConverterInputHandler";
	static readonly global::ObjCRuntime.NativeHandle selAvAudioConverterInputHandlerXHandle = global::ObjCRuntime.Selector.GetHandle ("avAudioConverterInputHandler");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selSetAvAudioConverterInputHandler_X = "setAvAudioConverterInputHandler:";
	static readonly global::ObjCRuntime.NativeHandle selSetAvAudioConverterInputHandler_XHandle = global::ObjCRuntime.Selector.GetHandle ("setAvAudioConverterInputHandler:");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selAvAudioEngineManualRenderingBlockX = "avAudioEngineManualRenderingBlock";
	static readonly global::ObjCRuntime.NativeHandle selAvAudioEngineManualRenderingBlockXHandle = global::ObjCRuntime.Selector.GetHandle ("avAudioEngineManualRenderingBlock");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selSetAvAudioEngineManualRenderingBlock_X = "setAvAudioEngineManualRenderingBlock:";
	static readonly global::ObjCRuntime.NativeHandle selSetAvAudioEngineManualRenderingBlock_XHandle = global::ObjCRuntime.Selector.GetHandle ("setAvAudioEngineManualRenderingBlock:");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selAvAudioIONodeInputBlockX = "avAudioIONodeInputBlock";
	static readonly global::ObjCRuntime.NativeHandle selAvAudioIONodeInputBlockXHandle = global::ObjCRuntime.Selector.GetHandle ("avAudioIONodeInputBlock");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selSetAvAudioIONodeInputBlock_X = "setAvAudioIONodeInputBlock:";
	static readonly global::ObjCRuntime.NativeHandle selSetAvAudioIONodeInputBlock_XHandle = global::ObjCRuntime.Selector.GetHandle ("setAvAudioIONodeInputBlock:");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selAvAudioInputNodeMutedSpeechEventListenerX = "avAudioInputNodeMutedSpeechEventListener";
	static readonly global::ObjCRuntime.NativeHandle selAvAudioInputNodeMutedSpeechEventListenerXHandle = global::ObjCRuntime.Selector.GetHandle ("avAudioInputNodeMutedSpeechEventListener");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selSetAvAudioInputNodeMutedSpeechEventListener_X = "setAvAudioInputNodeMutedSpeechEventListener:";
	static readonly global::ObjCRuntime.NativeHandle selSetAvAudioInputNodeMutedSpeechEventListener_XHandle = global::ObjCRuntime.Selector.GetHandle ("setAvAudioInputNodeMutedSpeechEventListener:");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selAvAudioNodeTapBlockX = "avAudioNodeTapBlock";
	static readonly global::ObjCRuntime.NativeHandle selAvAudioNodeTapBlockXHandle = global::ObjCRuntime.Selector.GetHandle ("avAudioNodeTapBlock");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selSetAvAudioNodeTapBlock_X = "setAvAudioNodeTapBlock:";
	static readonly global::ObjCRuntime.NativeHandle selSetAvAudioNodeTapBlock_XHandle = global::ObjCRuntime.Selector.GetHandle ("setAvAudioNodeTapBlock:");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selAvAudioSequencerUserCallbackX = "avAudioSequencerUserCallback";
	static readonly global::ObjCRuntime.NativeHandle selAvAudioSequencerUserCallbackXHandle = global::ObjCRuntime.Selector.GetHandle ("avAudioSequencerUserCallback");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selSetAvAudioSequencerUserCallback_X = "setAvAudioSequencerUserCallback:";
	static readonly global::ObjCRuntime.NativeHandle selSetAvAudioSequencerUserCallback_XHandle = global::ObjCRuntime.Selector.GetHandle ("setAvAudioSequencerUserCallback:");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selAvAudioSinkNodeReceiverHandlerRawX = "avAudioSinkNodeReceiverHandlerRaw";
	static readonly global::ObjCRuntime.NativeHandle selAvAudioSinkNodeReceiverHandlerRawXHandle = global::ObjCRuntime.Selector.GetHandle ("avAudioSinkNodeReceiverHandlerRaw");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selSetAvAudioSinkNodeReceiverHandlerRaw_X = "setAvAudioSinkNodeReceiverHandlerRaw:";
	static readonly global::ObjCRuntime.NativeHandle selSetAvAudioSinkNodeReceiverHandlerRaw_XHandle = global::ObjCRuntime.Selector.GetHandle ("setAvAudioSinkNodeReceiverHandlerRaw:");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selAvAudioSourceNodeRenderHandlerRawX = "avAudioSourceNodeRenderHandlerRaw";
	static readonly global::ObjCRuntime.NativeHandle selAvAudioSourceNodeRenderHandlerRawXHandle = global::ObjCRuntime.Selector.GetHandle ("avAudioSourceNodeRenderHandlerRaw");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selSetAvAudioSourceNodeRenderHandlerRaw_X = "setAvAudioSourceNodeRenderHandlerRaw:";
	static readonly global::ObjCRuntime.NativeHandle selSetAvAudioSourceNodeRenderHandlerRaw_XHandle = global::ObjCRuntime.Selector.GetHandle ("setAvAudioSourceNodeRenderHandlerRaw:");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selAvAudioUnitComponentFilterX = "avAudioUnitComponentFilter";
	static readonly global::ObjCRuntime.NativeHandle selAvAudioUnitComponentFilterXHandle = global::ObjCRuntime.Selector.GetHandle ("avAudioUnitComponentFilter");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selSetAvAudioUnitComponentFilter_X = "setAvAudioUnitComponentFilter:";
	static readonly global::ObjCRuntime.NativeHandle selSetAvAudioUnitComponentFilter_XHandle = global::ObjCRuntime.Selector.GetHandle ("setAvAudioUnitComponentFilter:");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selAvCaptureCompletionHandlerX = "avCaptureCompletionHandler";
	static readonly global::ObjCRuntime.NativeHandle selAvCaptureCompletionHandlerXHandle = global::ObjCRuntime.Selector.GetHandle ("avCaptureCompletionHandler");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selSetAvCaptureCompletionHandler_X = "setAvCaptureCompletionHandler:";
	static readonly global::ObjCRuntime.NativeHandle selSetAvCaptureCompletionHandler_XHandle = global::ObjCRuntime.Selector.GetHandle ("setAvCaptureCompletionHandler:");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selAvCaptureIndexPickerCallbackX = "avCaptureIndexPickerCallback";
	static readonly global::ObjCRuntime.NativeHandle selAvCaptureIndexPickerCallbackXHandle = global::ObjCRuntime.Selector.GetHandle ("avCaptureIndexPickerCallback");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selSetAvCaptureIndexPickerCallback_X = "setAvCaptureIndexPickerCallback:";
	static readonly global::ObjCRuntime.NativeHandle selSetAvCaptureIndexPickerCallback_XHandle = global::ObjCRuntime.Selector.GetHandle ("setAvCaptureIndexPickerCallback:");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selAvCaptureIndexPickerTitleTransformX = "avCaptureIndexPickerTitleTransform";
	static readonly global::ObjCRuntime.NativeHandle selAvCaptureIndexPickerTitleTransformXHandle = global::ObjCRuntime.Selector.GetHandle ("avCaptureIndexPickerTitleTransform");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selSetAvCaptureIndexPickerTitleTransform_X = "setAvCaptureIndexPickerTitleTransform:";
	static readonly global::ObjCRuntime.NativeHandle selSetAvCaptureIndexPickerTitleTransform_XHandle = global::ObjCRuntime.Selector.GetHandle ("setAvCaptureIndexPickerTitleTransform:");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selAvCaptureSliderCallbackX = "avCaptureSliderCallback";
	static readonly global::ObjCRuntime.NativeHandle selAvCaptureSliderCallbackXHandle = global::ObjCRuntime.Selector.GetHandle ("avCaptureSliderCallback");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selSetAvCaptureSliderCallback_X = "setAvCaptureSliderCallback:";
	static readonly global::ObjCRuntime.NativeHandle selSetAvCaptureSliderCallback_XHandle = global::ObjCRuntime.Selector.GetHandle ("setAvCaptureSliderCallback:");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selAvCaptureSystemExposureBiasSliderCallbackX = "avCaptureSystemExposureBiasSliderCallback";
	static readonly global::ObjCRuntime.NativeHandle selAvCaptureSystemExposureBiasSliderCallbackXHandle = global::ObjCRuntime.Selector.GetHandle ("avCaptureSystemExposureBiasSliderCallback");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selSetAvCaptureSystemExposureBiasSliderCallback_X = "setAvCaptureSystemExposureBiasSliderCallback:";
	static readonly global::ObjCRuntime.NativeHandle selSetAvCaptureSystemExposureBiasSliderCallback_XHandle = global::ObjCRuntime.Selector.GetHandle ("setAvCaptureSystemExposureBiasSliderCallback:");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selAvCaptureSystemZoomSliderCallbackX = "avCaptureSystemZoomSliderCallback";
	static readonly global::ObjCRuntime.NativeHandle selAvCaptureSystemZoomSliderCallbackXHandle = global::ObjCRuntime.Selector.GetHandle ("avCaptureSystemZoomSliderCallback");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selSetAvCaptureSystemZoomSliderCallback_X = "setAvCaptureSystemZoomSliderCallback:";
	static readonly global::ObjCRuntime.NativeHandle selSetAvCaptureSystemZoomSliderCallback_XHandle = global::ObjCRuntime.Selector.GetHandle ("setAvCaptureSystemZoomSliderCallback:");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selAvCompletionX = "avCompletion";
	static readonly global::ObjCRuntime.NativeHandle selAvCompletionXHandle = global::ObjCRuntime.Selector.GetHandle ("avCompletion");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selSetAvCompletion_X = "setAvCompletion:";
	static readonly global::ObjCRuntime.NativeHandle selSetAvCompletion_XHandle = global::ObjCRuntime.Selector.GetHandle ("setAvCompletion:");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selAvExternalStorageDeviceRequestAccessCallbackX = "avExternalStorageDeviceRequestAccessCallback";
	static readonly global::ObjCRuntime.NativeHandle selAvExternalStorageDeviceRequestAccessCallbackXHandle = global::ObjCRuntime.Selector.GetHandle ("avExternalStorageDeviceRequestAccessCallback");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selSetAvExternalStorageDeviceRequestAccessCallback_X = "setAvExternalStorageDeviceRequestAccessCallback:";
	static readonly global::ObjCRuntime.NativeHandle selSetAvExternalStorageDeviceRequestAccessCallback_XHandle = global::ObjCRuntime.Selector.GetHandle ("setAvExternalStorageDeviceRequestAccessCallback:");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selAvMusicEventEnumerationBlockX = "avMusicEventEnumerationBlock";
	static readonly global::ObjCRuntime.NativeHandle selAvMusicEventEnumerationBlockXHandle = global::ObjCRuntime.Selector.GetHandle ("avMusicEventEnumerationBlock");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selSetAvMusicEventEnumerationBlock_X = "setAvMusicEventEnumerationBlock:";
	static readonly global::ObjCRuntime.NativeHandle selSetAvMusicEventEnumerationBlock_XHandle = global::ObjCRuntime.Selector.GetHandle ("setAvMusicEventEnumerationBlock:");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selAvMutableCompositionInsertHandlerX = "avMutableCompositionInsertHandler";
	static readonly global::ObjCRuntime.NativeHandle selAvMutableCompositionInsertHandlerXHandle = global::ObjCRuntime.Selector.GetHandle ("avMutableCompositionInsertHandler");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selSetAvMutableCompositionInsertHandler_X = "setAvMutableCompositionInsertHandler:";
	static readonly global::ObjCRuntime.NativeHandle selSetAvMutableCompositionInsertHandler_XHandle = global::ObjCRuntime.Selector.GetHandle ("setAvMutableCompositionInsertHandler:");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selAvMutableVideoCompositionCreateApplierX = "avMutableVideoCompositionCreateApplier";
	static readonly global::ObjCRuntime.NativeHandle selAvMutableVideoCompositionCreateApplierXHandle = global::ObjCRuntime.Selector.GetHandle ("avMutableVideoCompositionCreateApplier");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selSetAvMutableVideoCompositionCreateApplier_X = "setAvMutableVideoCompositionCreateApplier:";
	static readonly global::ObjCRuntime.NativeHandle selSetAvMutableVideoCompositionCreateApplier_XHandle = global::ObjCRuntime.Selector.GetHandle ("setAvMutableVideoCompositionCreateApplier:");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selAvMutableVideoCompositionCreateCallbackX = "avMutableVideoCompositionCreateCallback";
	static readonly global::ObjCRuntime.NativeHandle selAvMutableVideoCompositionCreateCallbackXHandle = global::ObjCRuntime.Selector.GetHandle ("avMutableVideoCompositionCreateCallback");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selSetAvMutableVideoCompositionCreateCallback_X = "setAvMutableVideoCompositionCreateCallback:";
	static readonly global::ObjCRuntime.NativeHandle selSetAvMutableVideoCompositionCreateCallback_XHandle = global::ObjCRuntime.Selector.GetHandle ("setAvMutableVideoCompositionCreateCallback:");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selAvPlayerItemIntegratedTimelineAddBoundaryTimeObserverCallbackX = "avPlayerItemIntegratedTimelineAddBoundaryTimeObserverCallback";
	static readonly global::ObjCRuntime.NativeHandle selAvPlayerItemIntegratedTimelineAddBoundaryTimeObserverCallbackXHandle = global::ObjCRuntime.Selector.GetHandle ("avPlayerItemIntegratedTimelineAddBoundaryTimeObserverCallback");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selSetAvPlayerItemIntegratedTimelineAddBoundaryTimeObserverCallback_X = "setAvPlayerItemIntegratedTimelineAddBoundaryTimeObserverCallback:";
	static readonly global::ObjCRuntime.NativeHandle selSetAvPlayerItemIntegratedTimelineAddBoundaryTimeObserverCallback_XHandle = global::ObjCRuntime.Selector.GetHandle ("setAvPlayerItemIntegratedTimelineAddBoundaryTimeObserverCallback:");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selAvPlayerItemIntegratedTimelineAddPeriodicTimeObserverCallbackX = "avPlayerItemIntegratedTimelineAddPeriodicTimeObserverCallback";
	static readonly global::ObjCRuntime.NativeHandle selAvPlayerItemIntegratedTimelineAddPeriodicTimeObserverCallbackXHandle = global::ObjCRuntime.Selector.GetHandle ("avPlayerItemIntegratedTimelineAddPeriodicTimeObserverCallback");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selSetAvPlayerItemIntegratedTimelineAddPeriodicTimeObserverCallback_X = "setAvPlayerItemIntegratedTimelineAddPeriodicTimeObserverCallback:";
	static readonly global::ObjCRuntime.NativeHandle selSetAvPlayerItemIntegratedTimelineAddPeriodicTimeObserverCallback_XHandle = global::ObjCRuntime.Selector.GetHandle ("setAvPlayerItemIntegratedTimelineAddPeriodicTimeObserverCallback:");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selAvPlayerItemIntegratedTimelineSeekCallbackX = "avPlayerItemIntegratedTimelineSeekCallback";
	static readonly global::ObjCRuntime.NativeHandle selAvPlayerItemIntegratedTimelineSeekCallbackXHandle = global::ObjCRuntime.Selector.GetHandle ("avPlayerItemIntegratedTimelineSeekCallback");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selSetAvPlayerItemIntegratedTimelineSeekCallback_X = "setAvPlayerItemIntegratedTimelineSeekCallback:";
	static readonly global::ObjCRuntime.NativeHandle selSetAvPlayerItemIntegratedTimelineSeekCallback_XHandle = global::ObjCRuntime.Selector.GetHandle ("setAvPlayerItemIntegratedTimelineSeekCallback:");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selAvRequestAccessStatusX = "avRequestAccessStatus";
	static readonly global::ObjCRuntime.NativeHandle selAvRequestAccessStatusXHandle = global::ObjCRuntime.Selector.GetHandle ("avRequestAccessStatus");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selSetAvRequestAccessStatus_X = "setAvRequestAccessStatus:";
	static readonly global::ObjCRuntime.NativeHandle selSetAvRequestAccessStatus_XHandle = global::ObjCRuntime.Selector.GetHandle ("setAvRequestAccessStatus:");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selAvSampleBufferGeneratorBatchMakeReadyCallbackX = "avSampleBufferGeneratorBatchMakeReadyCallback";
	static readonly global::ObjCRuntime.NativeHandle selAvSampleBufferGeneratorBatchMakeReadyCallbackXHandle = global::ObjCRuntime.Selector.GetHandle ("avSampleBufferGeneratorBatchMakeReadyCallback");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selSetAvSampleBufferGeneratorBatchMakeReadyCallback_X = "setAvSampleBufferGeneratorBatchMakeReadyCallback:";
	static readonly global::ObjCRuntime.NativeHandle selSetAvSampleBufferGeneratorBatchMakeReadyCallback_XHandle = global::ObjCRuntime.Selector.GetHandle ("setAvSampleBufferGeneratorBatchMakeReadyCallback:");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selAvSampleBufferVideoRendererLoadVideoPerformanceMetricsCallbackX = "avSampleBufferVideoRendererLoadVideoPerformanceMetricsCallback";
	static readonly global::ObjCRuntime.NativeHandle selAvSampleBufferVideoRendererLoadVideoPerformanceMetricsCallbackXHandle = global::ObjCRuntime.Selector.GetHandle ("avSampleBufferVideoRendererLoadVideoPerformanceMetricsCallback");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selSetAvSampleBufferVideoRendererLoadVideoPerformanceMetricsCallback_X = "setAvSampleBufferVideoRendererLoadVideoPerformanceMetricsCallback:";
	static readonly global::ObjCRuntime.NativeHandle selSetAvSampleBufferVideoRendererLoadVideoPerformanceMetricsCallback_XHandle = global::ObjCRuntime.Selector.GetHandle ("setAvSampleBufferVideoRendererLoadVideoPerformanceMetricsCallback:");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selAvSpeechSynthesisProviderOutputBlockX = "avSpeechSynthesisProviderOutputBlock";
	static readonly global::ObjCRuntime.NativeHandle selAvSpeechSynthesisProviderOutputBlockXHandle = global::ObjCRuntime.Selector.GetHandle ("avSpeechSynthesisProviderOutputBlock");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selSetAvSpeechSynthesisProviderOutputBlock_X = "setAvSpeechSynthesisProviderOutputBlock:";
	static readonly global::ObjCRuntime.NativeHandle selSetAvSpeechSynthesisProviderOutputBlock_XHandle = global::ObjCRuntime.Selector.GetHandle ("setAvSpeechSynthesisProviderOutputBlock:");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selAvSpeechSynthesizerBufferCallbackX = "avSpeechSynthesizerBufferCallback";
	static readonly global::ObjCRuntime.NativeHandle selAvSpeechSynthesizerBufferCallbackXHandle = global::ObjCRuntime.Selector.GetHandle ("avSpeechSynthesizerBufferCallback");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selSetAvSpeechSynthesizerBufferCallback_X = "setAvSpeechSynthesizerBufferCallback:";
	static readonly global::ObjCRuntime.NativeHandle selSetAvSpeechSynthesizerBufferCallback_XHandle = global::ObjCRuntime.Selector.GetHandle ("setAvSpeechSynthesizerBufferCallback:");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selAvSpeechSynthesizerMarkerCallbackX = "avSpeechSynthesizerMarkerCallback";
	static readonly global::ObjCRuntime.NativeHandle selAvSpeechSynthesizerMarkerCallbackXHandle = global::ObjCRuntime.Selector.GetHandle ("avSpeechSynthesizerMarkerCallback");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selSetAvSpeechSynthesizerMarkerCallback_X = "setAvSpeechSynthesizerMarkerCallback:";
	static readonly global::ObjCRuntime.NativeHandle selSetAvSpeechSynthesizerMarkerCallback_XHandle = global::ObjCRuntime.Selector.GetHandle ("setAvSpeechSynthesizerMarkerCallback:");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selAvSpeechSynthesizerRequestPersonalVoiceAuthorizationCallbackX = "avSpeechSynthesizerRequestPersonalVoiceAuthorizationCallback";
	static readonly global::ObjCRuntime.NativeHandle selAvSpeechSynthesizerRequestPersonalVoiceAuthorizationCallbackXHandle = global::ObjCRuntime.Selector.GetHandle ("avSpeechSynthesizerRequestPersonalVoiceAuthorizationCallback");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selSetAvSpeechSynthesizerRequestPersonalVoiceAuthorizationCallback_X = "setAvSpeechSynthesizerRequestPersonalVoiceAuthorizationCallback:";
	static readonly global::ObjCRuntime.NativeHandle selSetAvSpeechSynthesizerRequestPersonalVoiceAuthorizationCallback_XHandle = global::ObjCRuntime.Selector.GetHandle ("setAvSpeechSynthesizerRequestPersonalVoiceAuthorizationCallback:");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selAvVideoCompositionCreateApplierX = "avVideoCompositionCreateApplier";
	static readonly global::ObjCRuntime.NativeHandle selAvVideoCompositionCreateApplierXHandle = global::ObjCRuntime.Selector.GetHandle ("avVideoCompositionCreateApplier");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selSetAvVideoCompositionCreateApplier_X = "setAvVideoCompositionCreateApplier:";
	static readonly global::ObjCRuntime.NativeHandle selSetAvVideoCompositionCreateApplier_XHandle = global::ObjCRuntime.Selector.GetHandle ("setAvVideoCompositionCreateApplier:");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selAvVideoCompositionCreateCallbackX = "avVideoCompositionCreateCallback";
	static readonly global::ObjCRuntime.NativeHandle selAvVideoCompositionCreateCallbackXHandle = global::ObjCRuntime.Selector.GetHandle ("avVideoCompositionCreateCallback");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selSetAvVideoCompositionCreateCallback_X = "setAvVideoCompositionCreateCallback:";
	static readonly global::ObjCRuntime.NativeHandle selSetAvVideoCompositionCreateCallback_XHandle = global::ObjCRuntime.Selector.GetHandle ("setAvVideoCompositionCreateCallback:");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selAvVideoCompositionDetermineValidityCallbackX = "avVideoCompositionDetermineValidityCallback";
	static readonly global::ObjCRuntime.NativeHandle selAvVideoCompositionDetermineValidityCallbackXHandle = global::ObjCRuntime.Selector.GetHandle ("avVideoCompositionDetermineValidityCallback");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selSetAvVideoCompositionDetermineValidityCallback_X = "setAvVideoCompositionDetermineValidityCallback:";
	static readonly global::ObjCRuntime.NativeHandle selSetAvVideoCompositionDetermineValidityCallback_XHandle = global::ObjCRuntime.Selector.GetHandle ("setAvVideoCompositionDetermineValidityCallback:");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	static readonly global::ObjCRuntime.NativeHandle class_ptr = global::ObjCRuntime.Class.GetHandle ("AVFoundationTrampolines");

	/// <summary>The Objective-C class handle for this class.</summary>
	/// <value>The pointer to the Objective-C class.</value>
	/// <remarks>
	///     Each managed class mirrors an unmanaged Objective-C class.
	///     This value contains the pointer to the Objective-C class.
	///     It is similar to calling the managed <see cref=\"ObjCRuntime.Class.GetHandle(string)\" /> or the native <see href=\"https://developer.apple.com/documentation/objectivec/1418952-objc_getclass\">objc_getClass</see> method with the type name.
	/// </remarks>
	public override global::ObjCRuntime.NativeHandle ClassHandle => class_ptr;

	/// <summary>Creates a new <see cref="AVFoundationTrampolines" /> with default values.</summary>
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[DesignatedInitializer]
	[Export ("init")]
	public AVFoundationTrampolines () : base (global::Foundation.NSObjectFlag.Empty)
	{
		if (IsDirectBinding)
			InitializeHandle (global::ObjCRuntime.Messaging.IntPtr_objc_msgSend (this.Handle, global::ObjCRuntime.Selector.GetHandle ("init")), "init");
		else
			InitializeHandle (global::ObjCRuntime.Messaging.IntPtr_objc_msgSendSuper (this.SuperHandle, global::ObjCRuntime.Selector.GetHandle ("init")), "init");
	}

	/// <summary>Constructor to call on derived classes to skip initialization and merely allocate the object.</summary>
	/// <param name="t">Unused sentinel value, pass NSObjectFlag.Empty.</param>
	/// <remarks>
	///     <para>
	///         This constructor should be called by derived classes when they completely construct the object in managed code and merely want the runtime to allocate and initialize the <see cref="Foundation.NSObject" />.
	///         This is required to implement the two-step initialization process that Objective-C uses, the first step is to perform the object allocation, the second step is to initialize the object.
	///         When developers invoke this constructor, they take advantage of a direct path that goes all the way up to <see cref="Foundation.NSObject" /> to merely allocate the object's memory and bind the Objective-C and C# objects together.
	///         The actual initialization of the object is up to the developer.
	///     </para>
	///     <para>
	///         This constructor is typically used by the binding generator to allocate the object, but prevent the actual initialization to take place.
	///         Once the allocation has taken place, the constructor has to initialize the object.
	///         With constructors generated by the binding generator this means that it manually invokes one of the "init" methods to initialize the object.
	///     </para>
	///     <para>It is the developer's responsibility to completely initialize the object if they chain up using this constructor chain.</para>
	///     <para>
	///         In general, if the developer's constructor invokes the corresponding base implementation, then it should also call an Objective-C init method.
	///         If this is not the case, developers should instead chain to the proper constructor in their class.
	///     </para>
	///     <para>
	///         The argument value is ignored and merely ensures that the only code that is executed is the construction phase is the basic <see cref="Foundation.NSObject" /> allocation and runtime type registration.
	///         Typically the chaining would look like this:
	///     </para>
	///     <example>
	///             <code lang="csharp lang-csharp"><![CDATA[
	/// //
	/// // The NSObjectFlag constructor merely allocates the object and registers the C# class with the Objective-C runtime if necessary.
	/// // No actual initXxx method is invoked, that is done later in the constructor
	/// //
	/// // This is taken from the iOS SDK's source code for the UIView class:
	/// //
	/// [Export ("initWithFrame:")]
	/// public UIView (System.Drawing.RectangleF frame) : base (NSObjectFlag.Empty)
	/// {
	///     // Invoke the init method now.
	///     var initWithFrame = new Selector ("initWithFrame:").Handle;
	///     if (IsDirectBinding) {
	///         Handle = ObjCRuntime.Messaging.IntPtr_objc_msgSend_CGRect (this.Handle, initWithFrame, frame);
	///     } else {
	///         Handle = ObjCRuntime.Messaging.IntPtr_objc_msgSendSuper_CGRect (this.SuperHandle, initWithFrame, frame);
	///     }
	/// }
	/// ]]></code>
	///     </example>
	/// </remarks>
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[EditorBrowsable (EditorBrowsableState.Advanced)]
	protected AVFoundationTrampolines (global::Foundation.NSObjectFlag t) : base (t) {}

	/// <summary>A constructor used when creating managed representations of unmanaged objects. Called by the runtime.</summary>
	/// <param name="handle">Pointer (handle) to the unmanaged object.</param>
	/// <remarks>
	///     <para>
	///         This constructor is invoked by the runtime infrastructure (<see cref="ObjCRuntime.Runtime.GetNSObject(System.IntPtr)" />) to create a new managed representation for a pointer to an unmanaged Objective-C object.
	///         Developers should not invoke this method directly, instead they should call <see cref="ObjCRuntime.Runtime.GetNSObject(System.IntPtr)" /> as it will prevent two instances of a managed object pointing to the same native object.
	///     </para>
	/// </remarks>
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[EditorBrowsable (EditorBrowsableState.Advanced)]
	protected internal AVFoundationTrampolines (global::ObjCRuntime.NativeHandle handle) : base (handle) {}

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public partial global::AVFoundation.AVAssetImageGenerateAsynchronouslyForTimeCompletionHandler AVAssetImageGenerateAsynchronouslyForTimeCompletionHandler
	{
		get
		{
			global::AVFoundation.AVAssetImageGenerateAsynchronouslyForTimeCompletionHandler ret;
			if (IsDirectBinding) {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avAssetImageGenerateAsynchronouslyForTimeCompletionHandler"));
			} else {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSendSuper (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avAssetImageGenerateAsynchronouslyForTimeCompletionHandler"));
			}
			GC.KeepAlive (this);
			return ret;
		}

		set
		{
			throw new NotImplementedException();
		}
	}

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public partial global::AVFoundation.AVAssetImageGeneratorCompletionHandler AVAssetImageGeneratorCompletionHandler
	{
		get
		{
			global::AVFoundation.AVAssetImageGeneratorCompletionHandler ret;
			if (IsDirectBinding) {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avAssetImageGeneratorCompletionHandler"));
			} else {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSendSuper (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avAssetImageGeneratorCompletionHandler"));
			}
			GC.KeepAlive (this);
			return ret;
		}

		set
		{
			throw new NotImplementedException();
		}
	}

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public partial global::AVFoundation.AVAssetImageGeneratorCompletionHandler2 AVAssetImageGeneratorCompletionHandler2
	{
		get
		{
			global::AVFoundation.AVAssetImageGeneratorCompletionHandler2 ret;
			if (IsDirectBinding) {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avAssetImageGeneratorCompletionHandler2"));
			} else {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSendSuper (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avAssetImageGeneratorCompletionHandler2"));
			}
			GC.KeepAlive (this);
			return ret;
		}

		set
		{
			throw new NotImplementedException();
		}
	}

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public partial global::AVFoundation.AVAssetPlaybackAssistantLoadPlaybackConfigurationOptionsHandler AVAssetPlaybackAssistantLoadPlaybackConfigurationOptionsHandler
	{
		get
		{
			global::AVFoundation.AVAssetPlaybackAssistantLoadPlaybackConfigurationOptionsHandler ret;
			if (IsDirectBinding) {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avAssetPlaybackAssistantLoadPlaybackConfigurationOptionsHandler"));
			} else {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSendSuper (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avAssetPlaybackAssistantLoadPlaybackConfigurationOptionsHandler"));
			}
			GC.KeepAlive (this);
			return ret;
		}

		set
		{
			throw new NotImplementedException();
		}
	}

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public partial global::AVFoundation.AVAudioConverterInputHandler AVAudioConverterInputHandler
	{
		get
		{
			global::AVFoundation.AVAudioConverterInputHandler ret;
			if (IsDirectBinding) {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avAudioConverterInputHandler"));
			} else {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSendSuper (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avAudioConverterInputHandler"));
			}
			GC.KeepAlive (this);
			return ret;
		}

		set
		{
			throw new NotImplementedException();
		}
	}

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public partial global::AVFoundation.AVAudioEngineManualRenderingBlock AVAudioEngineManualRenderingBlock
	{
		get
		{
			global::AVFoundation.AVAudioEngineManualRenderingBlock ret;
			if (IsDirectBinding) {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avAudioEngineManualRenderingBlock"));
			} else {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSendSuper (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avAudioEngineManualRenderingBlock"));
			}
			GC.KeepAlive (this);
			return ret;
		}

		set
		{
			throw new NotImplementedException();
		}
	}

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public partial global::AVFoundation.AVAudioInputNodeMutedSpeechEventListener AVAudioInputNodeMutedSpeechEventListener
	{
		get
		{
			global::AVFoundation.AVAudioInputNodeMutedSpeechEventListener ret;
			if (IsDirectBinding) {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avAudioInputNodeMutedSpeechEventListener"));
			} else {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSendSuper (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avAudioInputNodeMutedSpeechEventListener"));
			}
			GC.KeepAlive (this);
			return ret;
		}

		set
		{
			throw new NotImplementedException();
		}
	}

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public partial global::AVFoundation.AVAudioIONodeInputBlock AVAudioIONodeInputBlock
	{
		get
		{
			global::AVFoundation.AVAudioIONodeInputBlock ret;
			if (IsDirectBinding) {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avAudioIONodeInputBlock"));
			} else {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSendSuper (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avAudioIONodeInputBlock"));
			}
			GC.KeepAlive (this);
			return ret;
		}

		set
		{
			throw new NotImplementedException();
		}
	}

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public partial global::AVFoundation.AVAudioNodeTapBlock AVAudioNodeTapBlock
	{
		get
		{
			global::AVFoundation.AVAudioNodeTapBlock ret;
			if (IsDirectBinding) {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avAudioNodeTapBlock"));
			} else {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSendSuper (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avAudioNodeTapBlock"));
			}
			GC.KeepAlive (this);
			return ret;
		}

		set
		{
			throw new NotImplementedException();
		}
	}

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public partial global::AVFoundation.AVAudioSequencerUserCallback AVAudioSequencerUserCallback
	{
		get
		{
			global::AVFoundation.AVAudioSequencerUserCallback ret;
			if (IsDirectBinding) {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avAudioSequencerUserCallback"));
			} else {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSendSuper (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avAudioSequencerUserCallback"));
			}
			GC.KeepAlive (this);
			return ret;
		}

		set
		{
			throw new NotImplementedException();
		}
	}

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public partial global::AVFoundation.AVAudioSinkNodeReceiverHandlerRaw AVAudioSinkNodeReceiverHandlerRaw
	{
		get
		{
			global::AVFoundation.AVAudioSinkNodeReceiverHandlerRaw ret;
			if (IsDirectBinding) {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avAudioSinkNodeReceiverHandlerRaw"));
			} else {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSendSuper (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avAudioSinkNodeReceiverHandlerRaw"));
			}
			GC.KeepAlive (this);
			return ret;
		}

		set
		{
			throw new NotImplementedException();
		}
	}

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public partial global::AVFoundation.AVAudioSourceNodeRenderHandlerRaw AVAudioSourceNodeRenderHandlerRaw
	{
		get
		{
			global::AVFoundation.AVAudioSourceNodeRenderHandlerRaw ret;
			if (IsDirectBinding) {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avAudioSourceNodeRenderHandlerRaw"));
			} else {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSendSuper (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avAudioSourceNodeRenderHandlerRaw"));
			}
			GC.KeepAlive (this);
			return ret;
		}

		set
		{
			throw new NotImplementedException();
		}
	}

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public partial global::AVFoundation.AVAudioUnitComponentFilter AVAudioUnitComponentFilter
	{
		get
		{
			global::AVFoundation.AVAudioUnitComponentFilter ret;
			if (IsDirectBinding) {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avAudioUnitComponentFilter"));
			} else {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSendSuper (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avAudioUnitComponentFilter"));
			}
			GC.KeepAlive (this);
			return ret;
		}

		set
		{
			throw new NotImplementedException();
		}
	}

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public partial global::AVFoundation.AVCaptureCompletionHandler AVCaptureCompletionHandler
	{
		get
		{
			global::AVFoundation.AVCaptureCompletionHandler ret;
			if (IsDirectBinding) {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avCaptureCompletionHandler"));
			} else {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSendSuper (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avCaptureCompletionHandler"));
			}
			GC.KeepAlive (this);
			return ret;
		}

		set
		{
			throw new NotImplementedException();
		}
	}

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public partial global::AVFoundation.AVCaptureIndexPickerCallback AVCaptureIndexPickerCallback
	{
		get
		{
			global::AVFoundation.AVCaptureIndexPickerCallback ret;
			if (IsDirectBinding) {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avCaptureIndexPickerCallback"));
			} else {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSendSuper (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avCaptureIndexPickerCallback"));
			}
			GC.KeepAlive (this);
			return ret;
		}

		set
		{
			throw new NotImplementedException();
		}
	}

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public partial global::AVFoundation.AVCaptureIndexPickerTitleTransform AVCaptureIndexPickerTitleTransform
	{
		get
		{
			global::AVFoundation.AVCaptureIndexPickerTitleTransform ret;
			if (IsDirectBinding) {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avCaptureIndexPickerTitleTransform"));
			} else {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSendSuper (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avCaptureIndexPickerTitleTransform"));
			}
			GC.KeepAlive (this);
			return ret;
		}

		set
		{
			throw new NotImplementedException();
		}
	}

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public partial global::AVFoundation.AVCaptureSliderCallback AVCaptureSliderCallback
	{
		get
		{
			global::AVFoundation.AVCaptureSliderCallback ret;
			if (IsDirectBinding) {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avCaptureSliderCallback"));
			} else {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSendSuper (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avCaptureSliderCallback"));
			}
			GC.KeepAlive (this);
			return ret;
		}

		set
		{
			throw new NotImplementedException();
		}
	}

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public partial global::AVFoundation.AVCaptureSystemExposureBiasSliderCallback AVCaptureSystemExposureBiasSliderCallback
	{
		get
		{
			global::AVFoundation.AVCaptureSystemExposureBiasSliderCallback ret;
			if (IsDirectBinding) {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avCaptureSystemExposureBiasSliderCallback"));
			} else {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSendSuper (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avCaptureSystemExposureBiasSliderCallback"));
			}
			GC.KeepAlive (this);
			return ret;
		}

		set
		{
			throw new NotImplementedException();
		}
	}

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public partial global::AVFoundation.AVCaptureSystemZoomSliderCallback AVCaptureSystemZoomSliderCallback
	{
		get
		{
			global::AVFoundation.AVCaptureSystemZoomSliderCallback ret;
			if (IsDirectBinding) {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avCaptureSystemZoomSliderCallback"));
			} else {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSendSuper (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avCaptureSystemZoomSliderCallback"));
			}
			GC.KeepAlive (this);
			return ret;
		}

		set
		{
			throw new NotImplementedException();
		}
	}

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public partial global::AVFoundation.AVCompletion AVCompletion
	{
		get
		{
			global::AVFoundation.AVCompletion ret;
			if (IsDirectBinding) {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avCompletion"));
			} else {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSendSuper (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avCompletion"));
			}
			GC.KeepAlive (this);
			return ret;
		}

		set
		{
			throw new NotImplementedException();
		}
	}

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public partial global::AVFoundation.AVExternalStorageDeviceRequestAccessCallback AVExternalStorageDeviceRequestAccessCallback
	{
		get
		{
			global::AVFoundation.AVExternalStorageDeviceRequestAccessCallback ret;
			if (IsDirectBinding) {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avExternalStorageDeviceRequestAccessCallback"));
			} else {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSendSuper (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avExternalStorageDeviceRequestAccessCallback"));
			}
			GC.KeepAlive (this);
			return ret;
		}

		set
		{
			throw new NotImplementedException();
		}
	}

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public partial global::AVFoundation.AVMusicEventEnumerationBlock AVMusicEventEnumerationBlock
	{
		get
		{
			global::AVFoundation.AVMusicEventEnumerationBlock ret;
			if (IsDirectBinding) {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avMusicEventEnumerationBlock"));
			} else {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSendSuper (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avMusicEventEnumerationBlock"));
			}
			GC.KeepAlive (this);
			return ret;
		}

		set
		{
			throw new NotImplementedException();
		}
	}

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public partial global::AVFoundation.AVMutableCompositionInsertHandler AVMutableCompositionInsertHandler
	{
		get
		{
			global::AVFoundation.AVMutableCompositionInsertHandler ret;
			if (IsDirectBinding) {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avMutableCompositionInsertHandler"));
			} else {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSendSuper (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avMutableCompositionInsertHandler"));
			}
			GC.KeepAlive (this);
			return ret;
		}

		set
		{
			throw new NotImplementedException();
		}
	}

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public partial global::AVFoundation.AVMutableVideoCompositionCreateApplier AVMutableVideoCompositionCreateApplier
	{
		get
		{
			global::AVFoundation.AVMutableVideoCompositionCreateApplier ret;
			if (IsDirectBinding) {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avMutableVideoCompositionCreateApplier"));
			} else {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSendSuper (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avMutableVideoCompositionCreateApplier"));
			}
			GC.KeepAlive (this);
			return ret;
		}

		set
		{
			throw new NotImplementedException();
		}
	}

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public partial global::AVFoundation.AVMutableVideoCompositionCreateCallback AVMutableVideoCompositionCreateCallback
	{
		get
		{
			global::AVFoundation.AVMutableVideoCompositionCreateCallback ret;
			if (IsDirectBinding) {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avMutableVideoCompositionCreateCallback"));
			} else {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSendSuper (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avMutableVideoCompositionCreateCallback"));
			}
			GC.KeepAlive (this);
			return ret;
		}

		set
		{
			throw new NotImplementedException();
		}
	}

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public partial global::AVFoundation.AVPlayerItemIntegratedTimelineAddBoundaryTimeObserverCallback AVPlayerItemIntegratedTimelineAddBoundaryTimeObserverCallback
	{
		get
		{
			global::AVFoundation.AVPlayerItemIntegratedTimelineAddBoundaryTimeObserverCallback ret;
			if (IsDirectBinding) {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avPlayerItemIntegratedTimelineAddBoundaryTimeObserverCallback"));
			} else {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSendSuper (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avPlayerItemIntegratedTimelineAddBoundaryTimeObserverCallback"));
			}
			GC.KeepAlive (this);
			return ret;
		}

		set
		{
			throw new NotImplementedException();
		}
	}

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public partial global::AVFoundation.AVPlayerItemIntegratedTimelineAddPeriodicTimeObserverCallback AVPlayerItemIntegratedTimelineAddPeriodicTimeObserverCallback
	{
		get
		{
			global::AVFoundation.AVPlayerItemIntegratedTimelineAddPeriodicTimeObserverCallback ret;
			if (IsDirectBinding) {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avPlayerItemIntegratedTimelineAddPeriodicTimeObserverCallback"));
			} else {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSendSuper (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avPlayerItemIntegratedTimelineAddPeriodicTimeObserverCallback"));
			}
			GC.KeepAlive (this);
			return ret;
		}

		set
		{
			throw new NotImplementedException();
		}
	}

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public partial global::AVFoundation.AVPlayerItemIntegratedTimelineSeekCallback AVPlayerItemIntegratedTimelineSeekCallback
	{
		get
		{
			global::AVFoundation.AVPlayerItemIntegratedTimelineSeekCallback ret;
			if (IsDirectBinding) {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avPlayerItemIntegratedTimelineSeekCallback"));
			} else {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSendSuper (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avPlayerItemIntegratedTimelineSeekCallback"));
			}
			GC.KeepAlive (this);
			return ret;
		}

		set
		{
			throw new NotImplementedException();
		}
	}

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public partial global::AVFoundation.AVRequestAccessStatus AVRequestAccessStatus
	{
		get
		{
			global::AVFoundation.AVRequestAccessStatus ret;
			if (IsDirectBinding) {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avRequestAccessStatus"));
			} else {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSendSuper (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avRequestAccessStatus"));
			}
			GC.KeepAlive (this);
			return ret;
		}

		set
		{
			throw new NotImplementedException();
		}
	}

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public partial global::AVFoundation.AVSampleBufferGeneratorBatchMakeReadyCallback AVSampleBufferGeneratorBatchMakeReadyCallback
	{
		get
		{
			global::AVFoundation.AVSampleBufferGeneratorBatchMakeReadyCallback ret;
			if (IsDirectBinding) {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avSampleBufferGeneratorBatchMakeReadyCallback"));
			} else {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSendSuper (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avSampleBufferGeneratorBatchMakeReadyCallback"));
			}
			GC.KeepAlive (this);
			return ret;
		}

		set
		{
			throw new NotImplementedException();
		}
	}

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public partial global::AVFoundation.AVSampleBufferVideoRendererLoadVideoPerformanceMetricsCallback AVSampleBufferVideoRendererLoadVideoPerformanceMetricsCallback
	{
		get
		{
			global::AVFoundation.AVSampleBufferVideoRendererLoadVideoPerformanceMetricsCallback ret;
			if (IsDirectBinding) {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avSampleBufferVideoRendererLoadVideoPerformanceMetricsCallback"));
			} else {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSendSuper (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avSampleBufferVideoRendererLoadVideoPerformanceMetricsCallback"));
			}
			GC.KeepAlive (this);
			return ret;
		}

		set
		{
			throw new NotImplementedException();
		}
	}

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public partial global::AVFoundation.AVSpeechSynthesisProviderOutputBlock AVSpeechSynthesisProviderOutputBlock
	{
		get
		{
			global::AVFoundation.AVSpeechSynthesisProviderOutputBlock ret;
			if (IsDirectBinding) {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avSpeechSynthesisProviderOutputBlock"));
			} else {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSendSuper (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avSpeechSynthesisProviderOutputBlock"));
			}
			GC.KeepAlive (this);
			return ret;
		}

		set
		{
			throw new NotImplementedException();
		}
	}

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public partial global::AVFoundation.AVSpeechSynthesizerBufferCallback AVSpeechSynthesizerBufferCallback
	{
		get
		{
			global::AVFoundation.AVSpeechSynthesizerBufferCallback ret;
			if (IsDirectBinding) {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avSpeechSynthesizerBufferCallback"));
			} else {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSendSuper (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avSpeechSynthesizerBufferCallback"));
			}
			GC.KeepAlive (this);
			return ret;
		}

		set
		{
			throw new NotImplementedException();
		}
	}

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public partial global::AVFoundation.AVSpeechSynthesizerMarkerCallback AVSpeechSynthesizerMarkerCallback
	{
		get
		{
			global::AVFoundation.AVSpeechSynthesizerMarkerCallback ret;
			if (IsDirectBinding) {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avSpeechSynthesizerMarkerCallback"));
			} else {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSendSuper (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avSpeechSynthesizerMarkerCallback"));
			}
			GC.KeepAlive (this);
			return ret;
		}

		set
		{
			throw new NotImplementedException();
		}
	}

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public partial global::AVFoundation.AVSpeechSynthesizerRequestPersonalVoiceAuthorizationCallback AVSpeechSynthesizerRequestPersonalVoiceAuthorizationCallback
	{
		get
		{
			global::AVFoundation.AVSpeechSynthesizerRequestPersonalVoiceAuthorizationCallback ret;
			if (IsDirectBinding) {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avSpeechSynthesizerRequestPersonalVoiceAuthorizationCallback"));
			} else {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSendSuper (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avSpeechSynthesizerRequestPersonalVoiceAuthorizationCallback"));
			}
			GC.KeepAlive (this);
			return ret;
		}

		set
		{
			throw new NotImplementedException();
		}
	}

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public partial global::AVFoundation.AVVideoCompositionCreateApplier AVVideoCompositionCreateApplier
	{
		get
		{
			global::AVFoundation.AVVideoCompositionCreateApplier ret;
			if (IsDirectBinding) {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avVideoCompositionCreateApplier"));
			} else {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSendSuper (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avVideoCompositionCreateApplier"));
			}
			GC.KeepAlive (this);
			return ret;
		}

		set
		{
			throw new NotImplementedException();
		}
	}

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public partial global::AVFoundation.AVVideoCompositionCreateCallback AVVideoCompositionCreateCallback
	{
		get
		{
			global::AVFoundation.AVVideoCompositionCreateCallback ret;
			if (IsDirectBinding) {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avVideoCompositionCreateCallback"));
			} else {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSendSuper (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avVideoCompositionCreateCallback"));
			}
			GC.KeepAlive (this);
			return ret;
		}

		set
		{
			throw new NotImplementedException();
		}
	}

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public partial global::AVFoundation.AVVideoCompositionDetermineValidityCallback AVVideoCompositionDetermineValidityCallback
	{
		get
		{
			global::AVFoundation.AVVideoCompositionDetermineValidityCallback ret;
			if (IsDirectBinding) {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avVideoCompositionDetermineValidityCallback"));
			} else {
				ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSendSuper (this.Handle, global::ObjCRuntime.Selector.GetHandle ("avVideoCompositionDetermineValidityCallback"));
			}
			GC.KeepAlive (this);
			return ret;
		}

		set
		{
			throw new NotImplementedException();
		}
	}
	// TODO: add binding code here
}
