name: Labels verification
on:
  pull_request:
    types: [opened, reopened, labeled, unlabeled, synchronize]

jobs:
  check_pr_labels:
    runs-on: ubuntu-latest
    name: Labels verification

    if: github.actor != 'monojenkins' && join(github.event.pull_request.labels, ',') == ''

    # only execute when the user is not our bot and we have no labels
    steps:
    - run: exit 1
