name: Labels verification
on:
  pull_request:
    types: [opened, reopened, labeled, unlabeled, synchronize]

jobs:
  labels-check:
    runs-on: ubuntu-latest
    name: Labels verification

    steps:
    - run: exit 0
      # always happy if monojenkins
      if: github.actor == 'monojenkins'

    - run: exit 1
      # failure if not monojenkins and no labels
      if: github.actor != 'monojenkins' && join(github.event.pull_request.labels, ',') == ''

    - run: exit 0
      # success if not monojenkins but labels
      if: github.actor != 'monojenkins' && join(github.event.pull_request.labels, ',') != ''
