name: Labels verification
on:
  pull_request:
    types: [opened, reopened, labeled, unlabeled, synchronize]

jobs:
  monojenkins-pr:
    runs-on: ubuntu-latest
    name: Mono Jenkins

    if: github.actor == 'monojenkins'

    steps:
    - run: exit 0

  empty_pr_labels:
    runs-on: ubuntu-latest
    name: Labels missing 

    if: github.actor != 'monojenkins' && join(github.event.pull_request.labels, ',') == ''

    # only execute when the user is not our bot and we have no labels
    steps:
    - run: exit 1

  present_labels:
    runs-on: ubuntu-latest
    name: Labels present
    if: actor != 'monojenkins' && join(github.event.pull_request.labels, ',') != ''
    # only execute when the user is not our bot and we have no labels
    steps:
    - run: exit 0
