name: Sync Localization Branch
on:
  pull_request:
    branches:
      - 'TJ-TestingSyncLocalization'
    types: [closed]

concurrency: 
  group: 'Localization-Sync'
  cancel-in-progress: false

jobs:
  replaceLocalizationBranch:
    name: 'Replace Localization Branch'
    runs-on: ubuntu-latest
    steps:
    # Print debugging info
    - name: 'Information'
      script:
        - |
          echo "This commit came from {{ github.event.pull_request.head.repo.full_name }}. This commit is pushing to {{ github.repository }}."
          echo "The delete action wants to make sure that the merged event is true, it is - {{ github.event.pull_request.merged }}."
          echo "The delete action also wants to make sure that the labels contain the localization bot label, it is - {{ contains(github.event.pull_request.labels.*.names, 'localization_bot') }}."

    # Perhaps Print better debugging info
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    # We only want to run this GHA if not on a fork but don't want to trigger email failures if we are on fork using exit codes
    - name: 'Confirm not on a Fork'
      if: ${{ github.event.pull_request.head.repo.full_name == github.repository  }}
      run: echo "Good, we are not on a fork."

    - uses: dawidd6/action-delete-branch@v3
      name: 'delete'
      if: ${{ success() && github.event.pull_request.merged == true && github.event.pull_request.user.login == 'github-actions[bot]' && contains(github.event.pull_request.labels.*.names, 'localization_bot') }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branches: Localization
        soft_fail: true

    - uses: peterjgrainger/action-create-branch@v2.0.1
      name: 'Create Localization Branch'
      if: ${{ success() && github.event.pull_request.merged == true && github.event.pull_request.user.login == 'github-actions[bot]' && contains(github.event.pull_request.labels.*.names, 'localization_bot') }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: 'Localization'

    - name: 'Print message if on a Fork'
      if: ${{ github.event.pull_request.head.repo.full_name != github.repository  }}
      run: echo "This Github Action does not need to run on a fork."
