name: Sync Localization Branch
on:
  pull_request:
    branches:
      - 'AutomatingLocalizationGHATest'
    types: [closed]

jobs:
  print_info:
    name: 'Print Information'
    runs-on: ubuntu-latest
    steps:
    - name: "Get Pull Request Status"
      run: |
        echo "${{ github.event.pull_request.merged }}"
    - name: "Get Username"
      run: |
        echo "${{ github.event.pull_request.user.login }}"
    - name: "Get label names"
      run: |
        echo "${{ github.event.pull_request.labels.*.names }}"
    - name: "Get labels"
      run: |
        echo "${{ github.event.pull_request.labels }}"
    - name: "Get if using Localization-bot label"
      run: |
        echo "${{ contains(github.event.pull_request.labels.*.names, 'localization_bot') }}"
    - name: "FROM_LEGO"
      run: |
        echo "${{ github.event.pull_request.merged == true && github.event.pull_request.user.login == 'github-actions[bot]' && contains(github.event.pull_request.labels.*.names, 'localization_bot') }}"


  delete_branch:
    name: 'Delete Localization branch'
    runs-on: ubuntu-latest
    env:
      # We want to do the sync if we merged the pull request, the author was 'github-actions', and it has the correct label
      FROM_LEGO: ${{ github.event.pull_request.merged == true && github.event.pull_request.user.login == 'github-actions[bot]' && contains(github.event.pull_request.labels.*.names, 'localization_bot') }}
    steps:
    - uses: dawidd6/action-delete-branch@v3
      name: 'delete'
      if: ${{ env.FROM_LEGO == true }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branches: AutomatingLocalizationGHATest2

  checkout_localization_branch:
    name: 'Checkout the Localization branch'
    runs-on: ubuntu-latest
    needs: delete_branch
    env:
      FROM_LEGO: ${{ github.event.pull_request.merged == true && github.event.pull_request.user.login == 'github-actions' && contains(github.event.pull_request.labels.*.names, 'localization_bot') }}
    steps:
    - uses: actions/checkout@v2
      name: 'checkout'
      if: ${{ env.FROM_LEGO == true }}
      with:
        repository: ${{ github.repository }}
        ref: 'AutomatingLocalizationGHATest2'

  push_to_localization_branch:
    name: 'Push to Localization branch'
    runs-on: ubuntu-latest
    needs: checkout_localization_branch
    env:
      FROM_LEGO: ${{ github.event.pull_request.merged == true && github.event.pull_request.user.login == 'github-actions' && contains(github.event.pull_request.labels.*.names, 'localization_bot') }}
    steps:
    - uses: ad-m/github-push-action@master
      name: push
      if: ${{ env.FROM_LEGO == true }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: 'AutomatingLocalizationGHATest2'
