name: Sync Localization Branch
on:
  pull_request:
    branches:
      - 'AutomatingLocalizationGHATest'
    types: [closed]

jobs:
  print_info:
    name: 'Print Information'
    runs-on: ubuntu-latest
    env:
      # We want to do the sync if we merged the pull request, the author was 'github-actions', and it has the correct label
      FROM_LEGO: ${{ github.event.pull_request.merged == true && github.event.pull_request.user.login == 'github-actions[bot]' }} # && contains(github.event.pull_request.labels.*.names, 'localization_bot') }}
    steps:
    - name: "Get Pull Request Status"
      run: |
        echo "${{ github.event.pull_request.merged }}"
    - name: "Get Username"
      run: |
        echo "${{ github.event.pull_request.user.login }}"
    - name: "Get label names"
      run: |
        echo "${{ github.event.pull_request.labels.*.names }}"
    - name: "Get labels"
      run: |
        echo "${{ github.event.pull_request.labels }}"
    - name: "Get if using Localization-bot label"
      run: |
        echo "${{ contains(github.event.pull_request.labels.*.names, 'localization_bot') }}"
    - name: "new FROM_LEGO"
      run: |
        echo "${{ github.event.pull_request.merged == true && github.event.pull_request.user.login == 'github-actions[bot]' }}"
    - name: "Merged is true"
      run: |
        echo "${{ github.event.pull_request.merged == true  }}"
    - name: "login is correct"
      run: |
        echo "${{ github.event.pull_request.user.login == 'github-actions[bot]' }}"
    - name: "Can we access the variable?"
      run: |
        echo "${{ env.FROM_LEGO == true }}"

  delete_branch:
    name: 'Delete Localization branch'
    runs-on: ubuntu-latest
    steps:
    - uses: dawidd6/action-delete-branch@v3
      name: 'delete'
      if: ${{ github.event.pull_request.merged == true && github.event.pull_request.user.login == 'github-actions[bot]' }} # && contains(github.event.pull_request.labels.*.names, 'localization_bot') }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branches: AutomatingLocalizationGHATest2

  recreate_localization_branch:
    name: 'Create the Localization branch'
    runs-on: ubuntu-latest
    needs: delete_branch
    steps:
    - uses: peterjgrainger/action-create-branch@v2.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: 'AutomatingLocalizationGHATest2'

  push_to_localization_branch:
    name: 'Push to Localization branch'
    runs-on: ubuntu-latest
    needs: recreate_localization_branch
    steps:
    - uses: ad-m/github-push-action@master
      name: push
      if: ${{ github.event.pull_request.merged == true && github.event.pull_request.user.login == 'github-actions[bot]' }} # && contains(github.event.pull_request.labels.*.names, 'localization_bot') }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: 'AutomatingLocalizationGHATest2'
