name: Notify release branch change

on: repository_dispatch


jobs:
  updateRemote:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: 'Debug context'
        run: echo "$GITHUB_CONTEXT"

      - name: 'Add remotes'
        run: |
          git add remote public "http://$Env:GITHUB_TOKEN@github.com/xamarin/xamarin-macios.git"
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.access-token }}

      - name: 'Fetch remote'
        run: git fetch public

