# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

TOP=../../../../..
DOTNET_TEST_PLATFORMS=$(filter macOS MacCatalyst iOS,$(DOTNET_PLATFORMS))
DOTNET_TEST_DESKTOP_PLATFORMS=$(filter macOS MacCatalyst,$(DOTNET_DESKTOP_PLATFORMS))

include $(TOP)/tests/common/shared-dotnet-test.mk

TESTNAME=monotouch-test-audio-unit-extension
